### ISSUE TITLE
Support Native AMQP 1.0 in RabitMQ 4.0

### ISSUE THREAD

**Issue by mehdihadeli** [JasperFx/wolverine#1001]
Hi,
[RabbitMQ 4 now support AMQP 1.0](https://www.rabbitmq.com/blog/2024/08/05/native-amqp) directly without using a separated plugin for translating. Do you have a plan for supporting that in the RabbitMQ module?

They support this with separated RabbitMQ client library:
[https://github.com/rabbitmq/rabbitmq-amqp-dotnet-client](https://github.com/rabbitmq/rabbitmq-amqp-dotnet-client)

**Comment by jeremydmiller** [comment]
@mehdihadeli Hey, if you don't mind, use Discord for questions please. And if you look in the `main` branch that's already Wolverine 3.0 you'll see that we're already incorporating the RC of the latest Rabbit MQ client, so yes.
