### ISSUE TITLE
[SQL Server] High fragmentation of GUID primary keys

### ISSUE THREAD

**Issue by vasicvuk** [JasperFx/wolverine#1006]
**Describe the bug**

When using Wolverine with SQL Server with a large number of incoming envelopes there is a performance degradation because of GUIDs used for ID:

![image](https://github.com/user-attachments/assets/2e87e945-2630-42a2-bff7-1c62dc39f350)

I see that the current implementation uses: `CombGuidIdGeneration` from Marten which is based on the COMB algorithm that does not guarantee the best sorting if it's based on DateTime.UtcNow.

https://davecallan.com/generating-sequential-guids-which-sort-sql-server-in-net/

I would recommend using https://www.nuget.org/packages/NewId instead or at least give option for someone to implement custom ID generator instead.

**Comment by jeremydmiller** [comment]
@vasicvuk I take pull requests, and this sounds like a valuable one. That incoming envelopes table should never get that big though, so what's happening that it's getting that big in the first place?

**Comment by vasicvuk** [comment]
@jeremydmiller I will make a PR to change it with NewId :) 

Regarding the table size, we did the performance test of the app, the idea of the app is to process some financial messages, and the throughput was about 200 messages/s, it ran for 3 hours and I guess the table was filing faster then it could process.

**Comment by vasicvuk** [comment]
Link to PR https://github.com/JasperFx/wolverine/pull/1009

**Comment by vasicvuk** [comment]
Hmm, reading the comment on NewId it uses different Guid generation for different database:

https://github.com/phatboyg/NewId/issues/34

So i guess we need an interface and ability to configure a custom provider for Guids instead :/
