### ISSUE TITLE
Help with Durability mode configuration

### ISSUE THREAD

**Issue by vasicvuk** [JasperFx/wolverine#1019]
**Describe the bug**
I am using the latest `2.17.0` version of Wolverine, when I configure Durability mode to `Solo` for some reason the Wolverine does not follow the configured Execution timeout, instead, if the request is not made within 5 seconds, it sends the message for processing to handler again.

When I switch to `Balanced` everything works fine and as expected. What can be the issue here?

Thanks

**Comment by vasicvuk** [comment]
`DurabilityAgentEnabled` set to `false` resolved the issue for Solo. But some explanation would be helpful :)

**Comment by jeremydmiller** [comment]
@vasicvuk I'm going to need a bit more information from you about what you're observing. I can't think of any reason why the execution timeout behavior would have anything to do with the solo vs. balanced mode

**Comment by vasicvuk** [comment]
Sure, for some reason when setting to Solo mode without DurabilityAgentEnabled set to false my event handler gets called multiple times, this does not happen if the handler does work quickly and update incoming envelopes so that status is Handled, but if there is some longer duration of execution it gets called multiple times and Retries column does not increment. It seems like it is being called every 5 seconds.

When DurabilityAgentEnabled is set to false it works normally and handler gets executed once or retries after execution timeout.

On the balanced mode everything works also as expected.

**Comment by jeremydmiller** [comment]
What version btw?

**Comment by vasicvuk** [comment]
Tried from 2.13.0 to 2.17.0 and got same behavior.

**Comment by jeremydmiller** [comment]
Okay, but haven't tried with 3, that was the real question I guess

**Comment by vasicvuk** [comment]
No, I wanted to try it also but I had some compatibility issues in order to run it. I need to invest more time in compatibility part I guess

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/wolverine/commit/d1c99b4abccb684d42dd15b89bc76d54dce86db0
