### ISSUE TITLE
Code generation errors end to end with lightweight saga persistence

### ISSUE THREAD

**Issue by CaptainPaella** [JasperFx/wolverine#1055]
**Describe the bug**
I created a Visual Studio solution containing 3 projects:
- OrderIntegration.Api
- OrderIntegration.Worker

I spin up the Api + worker projects together using Docker compose. 
The OrderIntegration.Worker project is connected to a SQL server database, which runs in a docker container.

OrderIntegration.Api sends a message to an Azure ServiceBus queue that get picked up by OrderIntegration.Worker.
The Worker project handles the message and send a new "StartOrder" message that should kick off an OrderTestSaga (which should be persisted in SqlServer using [lightweight-saga-storage](https://wolverinefx.net/guide/durability/sagas.html#lightweight-saga-storage) 

When trying to handle the `StartOrder` message to create the Saga an exception is thrown:

> Wolverine.Runtime.WolverineRuntime[0]
> Exception detected: System.InvalidOperationException: Compilation failures!
> CS0128: A local variable or function named 'sqlTransaction' is already defined in this scope
> CS0128: A local variable or function named 'dbTransaction' is already defined in this scope
> CS0128: A local variable or function named 'envelopeTransaction' is already defined in this scope
> CS0128: A local variable or function named 'dbtx' is already defined in this scope

The `HandleAsync `method of the generated `StartOrderHandler ` class contains duplicate variables

**I provided the Saga class + generated handler code as attachments.**

**Additional context**
- WolverineFx 3.0.0-rc-2
- WolverineFx.SqlServer 3.0.0-rc-2
- SqlServer container image : mcr.microsoft.com/mssql/server:2022-latest
- Worker project uses image: mcr.microsoft.com/dotnet/sdk:8.0  

**Attachments**
[OrderTestSaga.txt](https://github.com/user-attachments/files/17294867/OrderTestSaga.txt)
[Generated StartOrderHandler.txt](https://github.com/user-attachments/files/17294941/Generated.StartOrderHandler.txt)

**Comment by jeremydmiller** [comment]
Impacted PostgreSQL too. Just needed to make the attachment of the transactional middleware by idempotent. Lack of testing was an issue here. Addressing this now.

**Comment by jeremydmiller** [comment]
This was nothing but incompetence and a lack of testing. At least it only went out in an RC release. Fixed now.
