### ISSUE TITLE
New static interfaces for Configure(HttpChain) & Configure(IChain) & Configure(HandlerChain)

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#1075]
Wasn't possible before, now is. Just a convenience.

**Comment by jeremydmiller** [comment]
Doesn't work the way I was envisioning, nobody cares anyway:)

**Comment by cbodin** [comment]
@jeremydmiller I care! What were the issues with adding static interfaces?

We’re currently adding a custom interface to all our handlers that need to configure the chain:

```csharp
public interface IHandlerChainConfiguration
{
    abstract static void Configure(HandlerChain chain);
}
```

The [docs](https://wolverinefx.net/guide/handlers/middleware.html#using-configure-chain-methods) label this feature as experimental with a warning. Is that still the case?
