### ISSUE TITLE
Batch message processing doesn't work with Kafka transport

### ISSUE THREAD

**Issue by adamzalesak** [JasperFx/wolverine#1076]
**Describe the bug**
Batch message handlers are not used when consuming Kafka messages. (No known handler for TestMessage#08dced17-0b69-27bf-54d7-e075bf020000 from kafka://topic/topic_0)

**To Reproduce**
https://github.com/adamzalesak/WolverineOutboxIssue/blob/main/WolverineOutboxIssue/Program.cs

**Expected behavior**
When `BatchMessagesOf<T>` is configured, the batch handler is called for the T message received from Kafka.

**Comment by jeremydmiller** [comment]
@adamzalesak I'm looking at this now
