### ISSUE TITLE
System.MissingMethodException: Method not found: '!!0 Wolverine.TransportCollection.GetOrCreate()'.

### ISSUE THREAD

**Issue by Guillaume-Music-Action** [JasperFx/wolverine#1107]
**Describe the bug**
i try to follow the tutorial
when I start my app (regulard .net core web api)

**To Reproduce**
I have added the package refs
        PackageReference Include="WolverineFx" Version="3.1.0" /
        PackageReference Include="WolverineFx.Pubsub" Version="3.1.0" /
        PackageReference Include="WolverineFx.RabbitMQ" Version="2.17.2" /

I write the code that is given in the quickstart

     builder.Host.UseWolverine(opts =>
        {
            opts.UseRabbitMq()

**Expected behavior**
not an exception

**Output**
System.MissingMethodException: Method not found: '!!0 Wolverine.TransportCollection.GetOrCreate()'.
   at Wolverine.RabbitMQ.RabbitMqTransportExtensions.RabbitMqTransport(WolverineOptions endpoints)
   at Wolverine.RabbitMQ.RabbitMqTransportExtensions.UseRabbitMq(WolverineOptions options, Action`1 configure) in /home/runner/work/wolverine/wolverine/src/Transports/RabbitMQ/Wolverine.RabbitMQ/RabbitMqTransportExtensions.cs:line 55
   at Icp4.Orchestrator.Utilities.BootUtilities.<>c__DisplayClass0_0.<InitializeWolverine>b__0(WolverineOptions opts) in 

**Desktop (please complete the following information):**
 - OS:  Mac OS sonoma 14.16.1
 - .Net SDK 8.0

**Additional context**
the DDLs are present in my output dir
Wolverine.RabbitMQ.dll 
Wolverine.dll

**Comment by Guillaume-Music-Action** [comment]
my projects also refers to         <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />

**Comment by Guillaume-Music-Action** [comment]
error fixed:
you should not use the latest version if you plan to use RabbitMq with Wolverine.
Use 2.17.2 , not 3...

that config works:
        <PackageReference Include="WolverineFx" Version="2.17.2" />
        <PackageReference Include="WolverineFx.RabbitMQ" Version="2.17.2" />

**Comment by Guillaume-Music-Action** [comment]
when do you plan to provide 
WolverineFx.RabbitMQ v3.1.0 ?

**Comment by dreammaster38** [comment]
Hi,

have you guys tried to use the Pre-Release Version of WolverineFx.RabbitMQ 3.1.0-rc-3 with Wolverine V3.1.0?
It'S running fine on our side if you not tryining to use masstransit compatibility features.

With Visual Studio 2022 of course you must include PrElease version while searching for nuget packages...

**Comment by jeremydmiller** [comment]
@Guillaume-Music-Action `PackageReference Include="WolverineFx.RabbitMQ" Version="2.17.2" />` -- that's never going to fly. You'll have to use the pre-release version of the RabbitMQ transport for 3.0. I know this isn't ideal, but OSS world and the rabbit client we're depending on is RC, so we're staying back on RC for just the Rabbit MQ client

@dreammaster38 Version conflict with MassTransit? Chris is usually pretty slow on updates, and the Rabbit MQ client changed a *lot*. Are you using MassTransit & Wolverine in the same codebase? I'm not aware of any issues with the MT compliance in 3.*, but that just means I don't know.

Folks, there's nothing actionable here, I'm closing this.
