### ISSUE TITLE
[Wolverine.Http] Support System.Text.Json source generation (JsonSerializerContext)

### ISSUE THREAD

**Issue by richardszalay** [JasperFx/wolverine#1112]
**Is your feature request related to a problem? Please describe.**
I'm unable to make use of System.Text.Json source generators using Wolverine.Http because `WolverineHttpOptions.JsonSerializerOptions` is marked as `internal`.

(I'm sure you're familiar with source generation, but for completeness: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/reflection-vs-source-generation)

**Describe the solution you'd like**
The simplest solution would be to Wolverine.Http to, by default or by configuration, share JsonSerializerOptions with Wolverine core as source-generation users are likely to already using that to register their source generated message contract.

As an alternative, making JsonSerializerOptions public so it can be configured via AddWolverineHttp / MapWolverineEndpoints?

To take this a step further (though technically outside the scope of this request), you could add some configuration extension methods that show intent to use source generation so Wolverine.Http can register its own (e.g. for ProblemDetails). Wolverine core could do something similar (e.g. for Envelope)

**Describe alternatives you've considered**
Nothing viable

**Comment by jeremydmiller** [comment]
You don't want Wolverine & Wolverine.HTTP to automatically use the same STJ settings. Wolverine.HTTP's JSON settings comes from `IOptions<JsonOptions>`. You can happily modify that through `IServiceCollection.Configure<JsonOptions>()`.

I don't think what you want is going to require any changes to Wolverine itself.

**Comment by richardszalay** [comment]
Ah yes, you're right. I got fixated on the default value of `WolverineHttpOptions.JsonSerializerOptions` and missed that it wasn't a read-only property.
