### ISSUE TITLE
 .IntegrateWithWolverine() in Marten config causes loss of response for invoked command

### ISSUE THREAD

**Issue by AlexZeitler** [JasperFx/wolverine#1114]
**Describe the bug**

## Scenario

Projects in a .NET 8 solution:

- RetailClient: Console App which places new orders in Order Service via Wolverine/RabbitMQ (3.1.0/3.1.0-rc-3) by invoking `PlaceOrder` commands (`RetailClient/Worker.cs`)
- Orders: Service, which receives the `PlaceOrder` commands, creates a pending `PurchaseOrder` (Inline SingleStreamProjection `PurchaseOrderProjection`) from it, sends the order back to the client and publishes a `OrderPlaced` event. `OrderPlaced` is consumed by the `Orders/Sagas/Order.cs` Saga and will invoke the `ReserveCredit` command - which already should matter for the issue described below.
- Messages: shared message types

The client is expected to receive an `PurchaseOrder` instance back from the `Orders/PlaceOrderHandler.cs` after invoking the `PlaceOrder` command.

This works fine until this line is added to the `Orders/Program.cs` Marten Configuration in line 38:

```csharp
 .IntegrateWithWolverine();
```

As soon as this line is being added, invoking the `PlaceOrder` command fails with this error message in the RetailClient:

```text
fail: Wolverine.Runtime.RemoteInvocation.FailureAcknowledgementHandler[0]
Received failure acknowledgement on reply for message 08dcfa93-7a7d-c24c-d843-ae60e95c0000 from service Orders with message 'No response was created for expected response 'Orders.PurchaseOrder''
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
BackgroundService failed
Wolverine.Runtime.RemoteInvocation.WolverineRequestReplyException: Request failed: No response was created for expected response 'Orders.PurchaseOrder'
at Wolverine.Runtime.Routing.MessageRoute.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRoute.cs:line 151
```

**To Reproduce**
Follow the description in this repro repository:
https://github.com/AlexZeitler/repro-marten-wolverine-integration-no-response

**Expected behavior**
Response is sent to client even with  `.IntegrateWithWolverine()` being called in Marten config.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 24.04)

**Additional context**
Tested with Wolverine `3.1.0` and `2.17.0`

**Comment by AlexZeitler** [comment]
I've been debugging a little:

The `Envelope.ReplyUri` in https://github.com/JasperFx/wolverine/blob/main/src/Wolverine/Runtime/MessageContext.cs#L400 does not exist in RabbitMQ - not sure if this is expected.

**Comment by AlexZeitler** [comment]
While debugging, I noticed this behavior:

When setting a breakpoint in https://github.com/JasperFx/wolverine/blob/main/src/Wolverine/Runtime/MessageContext.cs#L400 and waiting there, the client already crashed with the exception posted initially without even hitting Line 402.

This doesn't happen when ` .IntegrateWithWolverine()` is not used in Orders.

**Comment by AlexZeitler** [comment]
I tried  moving this block below the `hostBuilder.UseWolverine()` call:

```cs
hostBuilder.ConfigureServices(
  services =>
  {
    services.AddMarten(
        options =>
        {
          options.Connection(
            new NpgsqlConnectionStringBuilder()
            {
              Host = "localhost",
              Password = "123456",
              Database = "orders",
              Port = 5401,
              Username = "orders"
            }.ToString()
          );
          options.Events.StreamIdentity = StreamIdentity.AsString;
          options.Projections.Add<OrderProjection>(ProjectionLifecycle.Inline);
          options.DisableNpgsqlLogging = true;
        }
      )
      .IntegrateWithWolverine()
      .UseLightweightSessions();
  }
```

And I tried using to call `AddMarten` inside `UseWolverine()` like this:

```cs
options.Services.AddMarten(
          mo =>
          {
            mo.Connection(
              new NpgsqlConnectionStringBuilder()
              {
                Host = "localhost",
                Password = "123456",
                Database = "orders",
                Port = 5401,
                Username = "orders"
              }.ToString()
            );
            mo.Events.StreamIdentity = StreamIdentity.AsString;
            mo.Projections.Add<OrderProjection>(ProjectionLifecycle.Inline);
            mo.DisableNpgsqlLogging = true;
          }
        )
        .IntegrateWithWolverine()
        .UseLightweightSessions();
```

Neither fixed it.

**Comment by jeremydmiller** [comment]
@AlexZeitler I think you're getting burned on a timeout, especially over cold starts. Jack up the timeout a bit like so:

```csharp
                var order = await _bus.InvokeAsync<PurchaseOrder?>(
                    new PlaceOrder(
                        $"{Guid.NewGuid()}",
                        randomCustomer.Id,
                        randomAmount
                    ), timeout:30.Seconds()
                );
```

**Comment by AlexZeitler** [comment]
Ok, I'll work around this by consuming the `OrderPlaced` message in the client and pull the order via HTTP
