### ISSUE TITLE
Populate HTTP API metadata from compound handlers

### ISSUE THREAD

**Issue by OwnageIsMagic** [JasperFx/wolverine#1139]
```cs
public class EditMyEndpoint
{
    public async Task<(MyObj?, NotFound?)> LoadAsync(Guid id, AppDbContext context)
    {
        var ce = await context.My.FirstOrDefaultAsync(x => x.Id == id);
        if (ce is null)
            return (null, TypedResults.NotFound());

        return (ce, null);
    }

    [WolverinePut("/my/{id}")]
    public async Task<Results<
        Ok, ValidationProblem, ProblemHttpResult
        >> Edit(MyObj ce)
    {
        if (...)
            return TypedResults.ValidationProblem(errors);
        if (...)
            return TypedResults.Problem(...);

        return TypedResults.Ok();
    }
}
```
Produces following api schema with missing 404 NotFound from `LoadAsync`
```json
...
"put": {
  "responses": {
    "200": {
      "description": "OK"
    },
    "400": {
      "description": "Bad Request",
      "content": {
        "application/problem+json": {
          "schema": {
            "$ref": "#/components/schemas/Microsoft.AspNetCore.Http.HttpValidationProblemDetails"
          }
        }
      }
    }
  }
},
...

**Comment by jeremydmiller** [comment]
Use the `[Required]` attribute if you want too

**Comment by OwnageIsMagic** [comment]
`null` as `404` is not documented in https://wolverine.netlify.app/guide/handlers/return-values.html nor in https://wolverine.netlify.app/guide/http/endpoints.html
`[Required]` is actually what I wanted, but docs are slightly confusing
https://wolverine.netlify.app/guide/http/middleware.html#required-inputs
in the example `[Required] Todo? todo)` it's typed as nullable.
And it's not covering my another case like 
```cs
public async Task<(MyObj?, NotFound<ErrorDto>?)> LoadAsync(Guid id, string name, AppDbContext context)
{
    var e = await context.My.Include(x => x.Props.Where(c => c.Name == name)).FirstOrDefaultAsync(x => x.Id == id);
    if (e == null)
        return (null, TypedResults.NotFound(new ErrorDto("id not found")));
    if (!e.Docs.Any())
        return (null, TypedResults.NotFound(new ErrorDto($"'{name}' not found")));
    return e;
}
```

**Comment by jeremydmiller** [comment]
"docs are slightly confusing"

It's a community OSS project, and that comment is an automatic "I take pull requests" for any suggestions you might have to make that clearer and easier to fine.

What exactly is it you want to happen for that signature? Wolverine.HTTP today doesn't have any smarts around specific types of `IResult`. Do you have a specific suggestion for how you want it to work? And again, "I take pull requests"

**Comment by OwnageIsMagic** [comment]
>  "I take pull requests"

I'm sorry, I can't POST to github.com from my workplace due to DPI.
https://github.com/JasperFx/wolverine/blob/65ca00cf04e53cc475c59e8093cd1e8e161389ef/docs/guide/http/middleware.md?plain=1#L232
I meant here `Todo` marked as nullable, but since it's `[Required]` it should not be `null`.

> doesn't have any smarts around specific types of IResult

It work's ok (NotFound result from LoadAsync executed), but only main handler inspected for `IEndpointMetadataProvider`. I suggest calling `tryApplyAsEndpointMetadataProvider` on all return types in http chain, not only `ResourceType`
https://github.com/JasperFx/wolverine/blob/65ca00cf04e53cc475c59e8093cd1e8e161389ef/src/Http/Wolverine.Http/HttpChain.EndpointBuilder.cs#L105
