### ISSUE TITLE
When using RabbitMq transport and setting ListenerCount to x on the queue then it actually creates x^2 listeners on it

### ISSUE THREAD

**Issue by alekbarszczewski** [JasperFx/wolverine#1152]
**Describe the bug**
When using RabbitMq transport and setting queue ListenerCount to x then it actually adds x^2 consumers on the RabbitMq queue and it processes x^2 messages at once (in parallel).
 
**To Reproduce**

```
using Microsoft.Extensions.Hosting;
using Oakton;
using Oakton.Resources;
using Wolverine;
using Wolverine.RabbitMQ;

var builder = Host.CreateDefaultBuilder(args);

builder.UseWolverine(opts =>
{
    opts
        .UseRabbitMq(new Uri("amqp://guest:guest@localhost:5672"))
        .AutoProvision();

    opts
        .ListenToRabbitQueue("test_queue")
        .ProcessInline()
        .ListenerCount(4);  // -> causes queue to have 16 consumers and processes 16 messages at once
});

builder.ConfigureServices(services =>
{
    services.AddResourceSetupOnStartup();
});

var host = builder.Build();

return await host.RunOaktonCommands(args);
```

Then go to RabbitMq admin panel / queues / test_queue and see number of consumers on the queue - it will be 16 instead of 4.

Here is docker-compose.yml to run RabbitMq:
```
version: "3.8"
name: wolverine_listener_count_test
services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    tmpfs:
      - /var/lib/rabbitmq
      - /var/log/rabbitmq
```

**Expected behavior**
When setting ListenerCount to x it should add x consumers on RabbitMq queue and process at most x messages at once (in parallel).

**Screenshots**
![RabbitMQ_Management](https://github.com/user-attachments/assets/f83394a3-613a-4f12-bc93-0462162e324b)
![RabbitMqQueue_cs-2](https://github.com/user-attachments/assets/d0706224-47dd-493b-8394-d8bf51c21f1d)

**Desktop (please complete the following information):**
 - OS: macos
 - WolverineFx  / WolverineFx.RabbitMq Versions: 3.3.0
 - RabbitMq Version: 3.12.14

**Additional context**
Generally the code I provided creates 2 connections to RabbitMq - one is for sending I think and has 0 channels and second one is for listening and it has 17 channels (1 channel is consumer of wolverine response queue and 16 are consumers on test_queue).

I did some debugging and it looks like this:
https://github.com/JasperFx/wolverine/blob/a78f71516e0cdfd10b25a320dcd76cc47cb88209/src/Wolverine/Transports/ListeningAgent.cs#L160 **ListeningAgent** has ListenerCount = 4 and ListeningAgent.StarAsync is called which in for loop calls **Endpoint.BuildListenerAsync**. Endpoint is actually **RabitMqQueue** (https://github.com/JasperFx/wolverine/blob/a78f71516e0cdfd10b25a320dcd76cc47cb88209/src/Transports/RabbitMQ/Wolverine.RabbitMQ/Internal/RabbitMqQueue.cs#L326) and it **also has ListenerCount = 4** and in for loop creates actual RabbitMqListeners.

So essentially it comes to this more or less:
```
for (var i = 0; i < ListenerCount; i++) // in ListeningAgent
{
    for (var i = 0; i < ListenerCount; i++) // in RabitMqQueue
    {
         var listener = new RabbitMqListener(runtime, this, _parent, receiver);
     }
}
```

Possible workaround: set listener count to square root of desired listener count 🤔

**Comment by jeremydmiller** [comment]
Oh, that's just flat out a bug that must have snuck in during the 3.0 changes. No big deal.
