### ISSUE TITLE
Easy ability to return the current state of the aggregate as part of an aggregate handler workflow or start new stream action

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#1161]
## Problem statement

Folks frequently want the current state of the aggregate that is having events captured as a result of an aggregate handler workflow. We need the *final* state of the aggregate as either:

1. HTTP response for Wolverine HTTP endpoints
2. Response as part of IMessageBus.InvokeAsync<T>(message) where "T" is the aggregate

## Thoughts

* Might need a lighter weight "read only" version of `FetchForWriting()`

## Proposal for Inline Handlers

**No change in client's code**

Make it magic in the inline handler if using `InvokeAsync<T>` with extra codegen to get at the current aggregate state. 

`[AggregateHandler(PublishResult = true)]` -- this can be done at the class level. Generate this the most efficient way possible:

1. If aggregate is `Inline`, pull it out of the identity map of the current session
2. If live, gotta do aggregate stream async
3. If async, be nice to have a lighter weight version of FetchForWriting. 

## Proposal for HTTP

New convention maybe to express a different response than what comes out of the main endpoint handler method

Respond() : Whatever, and whatever is the actual response? Or `Write() : REeponse`, and `Response` is the return. 

### Alternative 1, use response type

```csharp
public static class SomeEndpoint
{
    public static (CurrentState, Events) Handle(SomeCommand, Order)
    {
        return (new CurrentState(order), [some events]);
    }
}
```

And Wolverine "knows" to write out the order in its current state.

```csharp
public static class SomeEndpoint
{
    public static IEnumerable<object> Handle(SomeCommand, [Aggregate(RespondWithCurrentState = true)] Order)
    {
        return [some events];
    }
}
```

or 

```csharp
public static class SomeEndpoint
{
    [RespondWithCurrentState]
    public static IEnumerable<object> Handle(SomeCommand, [Aggregate(RespondWithCurrentState = true)] Order)
    {
        return [some events];
    }
}
```

**Comment by erdtsieck** [comment]
What happens if command execution succeeds, but aggregate state retrieval fails?

**Comment by jeremydmiller** [comment]
@erdtsieck Meh, good catch. We'll have to beat this by documentation that users will have to handle this by idempotency checks. I don't think it's going to be very likely though with the FetchLatest API coming in Marten

**Comment by jeremydmiller** [comment]
## Notes

* In `HttpChain`, look for `IResponse` in the `tryFindResourceType` method, look for a response that implements `IResponseAware` and use that to alter the chain. Nah, let's say it's just a static `IResponse` interface that will configure the chain
* Might have to have a generic way to mark a chain as having an aggregate type. Use IChain.Tags?
* Maybe a generic `IChain.UseReturnAsResponse(MethodCall)`. That would allow us to create the response type for HttpChain & the HandlerChain
* `Latest` implements `IResponseAware` and adds an IDocumentSession.Events.FetchLatest()



## Test Cases

- [ ] `Latest` from HttpChain, that's the response
- [ ] `Latest` from HandlerChain, used as a response message for InvokeAsync<T>()
- [ ] `Latest` from handler, used as a cascading message
