### ISSUE TITLE
Store multiple documents with StoreDoc bug

### ISSUE THREAD

**Issue by davidst** [JasperFx/wolverine#1162]
**Describe the bug**
In the Wolverine [V3.4.0](https://github.com/JasperFx/wolverine/releases/tag/V3.4.0) `StoreDoc<T>` now stores an `object[]` with one element of type `T[]`.

**To Reproduce**
```
public recod Foo;

public void MartenOps_store_test()
{
    var docs = new[] { new Foo(), new Foo() };

    var storeOp = MartenOps.Store<Foo>(docs);

    storeOp.Documents.ShouldBe(docs);
}

```

**Expected behavior**
`StoreDoc<T>` should store an `object[]` with elements of type `T`.

**Additional context**
- The bug was introduced in [this commit](https://github.com/JasperFx/wolverine/commit/e3906fd026596c8bd6c73bb71b9002ae1182498d).
- The initial change from [this commit](https://github.com/JasperFx/wolverine/commit/c1eec8ec71c0ba8095bf87503c9a3f77fef3c126) introduced a breaking change in a minor version.

**Comment by haefele** [comment]
Fix is already prepared in #1158

**Comment by davidst** [comment]
The bug is still there in the `public StoreManyDocs(params T[] documents) : base(documents)` constructor calling the base constructor, because there is no implicit conversion from `T[]` to `object[]`.

**Comment by jay-zahiri** [comment]
I missed it while reorganizing; it's fixed now. [Here's a quick demo](https://dotnetfiddle.net/ah4hXJ)

**Comment by davidst** [comment]
Yes, that fixes the issue, but it's missing the `params` keyword which would make the usage nicer.

**Comment by jeremydmiller** [comment]
Fixes coming late today / early tomorrow
