### ISSUE TITLE
Codegen goes into endless loop for always-retry handler

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#1182]
**Describe the bug**
`Requeue(int.MaxValue)` or with just a large enough number blocks the codegen at 100% CPU, looks like an endless loop.

**To Reproduce**

```csharp
public static class SomeHandler
{
  public static void Configure(HandlerChain chain)
  {
    chain.OnException<Exception>().Requeue(int.MaxValue);
  }

  public static void Handle(SomeCommand command)
  {
  }
}
```

```sh
$ dotnet run -- codegen write
```

**Expected behavior**
`dotnet run` terminates

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Wolverine 3.5.1, .NET 9

**Comment by jeremydmiller** [comment]
@agross This is getting "fixed" by Wolverine throwing an `ArgumentOutOfRangeException` if there's more than 25 attempts specified, **but**, there's a new usage coming in 3.5:

```csharp
                // Obviously use this with caution, but this allows you
                // to tell Wolverine to requeue an exception on failures no
                // matter how many attempts have been made already
                opts.OnException<NotReadyException>()
                    .RequeueIndefinitely();
```
