### ISSUE TITLE
Ability to work with AggregateHandler attribute on "BeforeMethods", at least Validate/ValidateAsync

### ISSUE THREAD

**Issue by NeussConsulting** [JasperFx/wolverine#1183]
**Is your feature request related to a problem? Please describe.**
I can put already the command/request object into ValidateAsync and it get's correctly filled, but using the attribute and the aggregate in the method, it get's not filled.
But the ValidateAsync method would be perfect in my opinion 
 to call some MyAggregate.BusinessValidation(command.GreatValue) and return a good error response or continue to the handler.

**Describe the solution you'd like**
I want to be able to use the Attribute not just on the Handle method itself, but also on the BeforeMethods.
Maybe something challenging on that feature, if I get the Aggregate already in the BeforeMethod, then it would not be performant to get it again for the Handle method, so the already loaded Aggregate would have to be passed to the Handle method IF it has the Aggregate as a parameter.  
Maybe also a Validation that the AggregateHandler attribute is just used once in the compounding class?!
```csharp
public static class GreatEndpoint
{
    [AggregateHandler]
    public static IResult ValidateAsync(MyCommand command, MyAggregate aggregate)
    {
        return MyAggregate.BusinessValidation(command.GreatValue) ? WolverineContinue.Result() : Results.BadRequest();
    }

    [HttpPost("/todoitems")]
    // [AggregateHandler] <-- If this also here maybe Wolverine Exception?!
    public static (IResult, PostedEvent) Post(MyCommand command, MyAggregate aggregate)
    {
        return (Results.Created($"/api/aggregate/{aggregate.Id}", null), new PostedEvent());
    }
}
```

**Describe alternatives you've considered**
It's possible to use the AggregateHandler attribute on the class, then everything is working.
What I don't know is if the aggregate get's loaded twice for each method or if it's reused.
```csharp
[AggregateHandler]
public static class GreatEndpoint
{
    public static IResult ValidateAsync(MyCommand command, MyAggregate aggregate)
    {
        return MyAggregate.BusinessValidation(command.GreatValue) ? WolverineContinue.Result() : Results.BadRequest();
    }

    [HttpPost("/todoitems")]
    public static (IResult, PostedEvent) Post(MyCommand command, MyAggregate aggregate)
    {
        return (Results.Created($"/api/aggregate/{aggregate.Id}", null), new PostedEvent());
    }
}
```

**Additional context**
No

**Comment by NeussConsulting** [comment]
If this is not wanted, what I would understand because the Attribute is named "AggregateHANDLER" I would throw a Wolverine Exception if the Attribute is used on a BeforeMethod and say give the tip "Use it on the class instead"

**Comment by jeremydmiller** [comment]
Oh, I think this is a very valid thing to want to be able to do. Also don't think this is going to be very much work to address.

**Comment by jeremydmiller** [comment]
@NeussConsulting I think I'm going to close this. What you *can* do right now is use the aggregate type as an argument to a Before/Validate/LoadAsync method as long as the main aggregate handler method is decorated with that attribute. I think that's good enough. I'm updating the documentation for that and closing this.
