### ISSUE TITLE
WolverineHttp Endpoints with Transactional behavior & Durable queues don't trigger handlers

### ISSUE THREAD

**Issue by blashbul** [JasperFx/wolverine#1184]
**Describe the bug**
When using Wolverine Http endpoint, that return an event message, havingTransactional Attribute set ( Using AutoApplyTransactions give same results),  using durable local queues, the message is written to database in the wolverine_incoming_envelopes table, but is never procedded and thus never triggers the handlers bound to the event.

**To Reproduce**
1. Clone Wolverine repos
2. Launch Samples/EfCoreSample/ItemService project in debug mode
3. Put a breakpoint on Handle method of ItemCreatedHandler class
4. Make an http request to /items/create4 endpoint
5. Breakpoint is never reached

**Expected behavior**
Code execution shoud stop on breakpoint, the handler shoud have been called.

**Additional context**
Wolverine 3.5.1

**Comment by jeremydmiller** [comment]
@blashbul Thanks for the report. Nuget dependency problems, but then, this was a real Wolverine.HTTP + EF Core permutation problem. Fix in 3.6 soon.
