### ISSUE TITLE
FluentValidation: ValidateAsync

### ISSUE THREAD

**Issue by afmuller** [JasperFx/wolverine#152]
I have scenarios where I use have asynchronous rules to test if a record already exists in the database. 

As detailed here [(https://docs.fluentvalidation.net/en/latest/async.html)](https://docs.fluentvalidation.net/en/latest/async.html) FluentValidation requires calling ValidateAsync if the validator contains asynchronous rules. 

I've noted that the FluentValidationExecutor calls Validate - which causes an exception if any async rules exist. 

Is there a possibility of opting into calling ValidateAsync instead of Validate? 

Thanks
Andrew

**Comment by Vertygo** [comment]
@jeremydmiller I guess we can call ValidateAsync instead of Validate in FluentValidationExecutor.ExecuteOne/ExecuteMany?

**Comment by jeremydmiller** [comment]
Sounds like a good PR! I'm fine with that

**Comment by jeremydmiller** [comment]
Fixed by #155
