### ISSUE TITLE
Support multiple bindings between RabbitMQ exchanges and queues

### ISSUE THREAD

**Issue by p-fx** [JasperFx/wolverine#163]
Allow a RabbitMQ queue to have more than 1 binding to an exchange.

That would for example enable to set up a queue with 2 topic-patterns to a single topic exchange as shown in the  [topics RabbitMQ tutorial](https://www.rabbitmq.com/tutorials/tutorial-five-python.html).

Currently, only the first binding is being created, but not any subsequent ones.

---

Steps to reproduce

In below example code, the `color.cyan` topic binding does not get created.

```
theSender = Host.CreateDefaultBuilder()
    .UseWolverine(opts =>
    {
        opts.UseRabbitMq().AutoProvision();
        opts.PublishAllMessages().ToRabbitTopics("wolverine.topics", exchange =>
        {
            exchange.BindTopic("color.green").ToQueue("green");
            exchange.BindTopic("color.blue").ToQueue("blue");
            exchange.BindTopic("color.cyan").ToQueue("blue");
            exchange.BindTopic("color.*").ToQueue("all");            
        });
    }).Start();
```

**Comment by jeremydmiller** [comment]
Fixed in 0.9.12
