### ISSUE TITLE
Let [MartenCommandWorkflow] work with commands without Version

### ISSUE THREAD

**Issue by dgrozenok** [JasperFx/wolverine#202]
In some cases the command handler should be able to start with the latest version of the aggregate and not provide a specific expected version. The handler would validate if the command is applicable to that state. [MartenCommandWorkflow] requires the expected version to be provided in the command as the Version property. However, it is still very valuable and applicable in that scenario as it would make sure that while the command is handled the state of the aggregate is not changed before committing.

Would it be possible in case the command doesn't have the Version property to generate the code with the FetchForWriting<> method without the expectedVersion parameter?

```csharp
Task<IEventStream<T>> FetchForWriting<T>(string key, CancellationToken cancellation = default (CancellationToken))
```

**Comment by jeremydmiller** [comment]
Got it.

duplicate with #191 

Two reports moves this up the priority list...

**Comment by dgrozenok** [comment]
Thanks! Sorry, was trying to search by MartenCommandWorkflow and couldn't find any.
