### ISSUE TITLE
Optimized local Minimal API delegation to InvokeAsync() and InvokeAsync<T>()

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#205]
I bleeping *hate* that folks seem primarily interested in using Wolverine as a MediatR replacement and want this:

```
app.MapGet((Body body, IMessageBus bus) => bus.InvokeAsync<Response>(body));

// or

app.MapPost((Command cmd, IMessageBus bus) => bus.InvokeAsync(cmd)); 
```

It'd be nice to have a little more performant relay of ASP.Net Core to Wolverine w/o having to bounce through the dictionary lookups you do by calling InvokeAsync().

Instead, what if the Wolverine.Http package had a `MapGetToWolverine<TRequest, TResponse>(url pattern)` and

`MapPostToWolverine<TCommand>(url)`?

Also getting requests to relay metadata about TenantId to Wolverine innards that would be detected somehow on the HttpContext.

**Comment by dgrozenok** [comment]
That would be great! Already doing something like that as extension methods. One challenge though is with parameters. If following REST approach to the endpoints we usually have {id} parameter for the entity the command/query operate upon. What is your recommendation to the endpoint URLs design? Especially if they are mostly for supporting the UI and not really a public Web API of some sort.

**Comment by dgrozenok** [comment]
Just read this post https://www.freecodecamp.org/news/rest-is-the-new-soap-97ff6c09896d/
Will try to minimize RESTfullness of my apis moving forward. Just the command/query name as the URL and the payload in the body should be enough with small exceptions of really simple getters by id, which would not even need any mediators.

**Comment by lulzhipsters** [comment]
I note there's no `MapGetToWolverine` method, is this a deliberate choice, or would you be open to a PR to add one?
