### ISSUE TITLE
Erroneously getting a FailureAcknowledgement from InvokeAsync<T>()

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#215]
Use Marten transactional middleware on a message handler, then call InvokeAsync<T>(). Prove there is no FailureAck being sent.

**Comment by kirill-gerasimenko-da** [comment]
Hi @jeremydmiller, I'm getting same kind of errors on the latest 1.6.0. I'm not using Marten for persistence, but rather EF Core, maybe it makes difference.
