### ISSUE TITLE
Transport: PostgreSQL Implementation

### ISSUE THREAD

**Issue by PascalSenn** [JasperFx/wolverine#224]
# Transport: PostgreSQL Implementation
## Introduction
The goal is to implement a transport layer for wolverine, using PostgreSQL as a transport layer. This implementation aims to reduce dependencies in smaller projects by using the existing database to avoid adding extra costs and complexity of a dedicated messaging infrasstructure. 

Even though there is no focus on achieving similar throughput to a dedicated messaging system, this implementation has to be reliable, with no message loss or similar issues.

# Design Overview
Inspired by Azure Service Bus, the messaging infrastructure will support:

1. Queues for sending messages to a single consumer.
2. Topics and subscriptions for addressing multiple consumers.

The first iteration of this project will focus on implementing the queue, with topics and subscriptions to be added later.

# Implementation of a Queue in PostgreSQL
The base of a queue is a simple table. When a message is sent to a consumer, a row is inserted into this table. A trigger that runs after the insert will call a function using `pg_notify` to `NOTIFY` a channel. The consumer listens to this channel and receives information about new items in the queue this way.

After the consumer is notified over the channel, it opens a transaction and reads from the queue table, using the "SKIP LOCKED" feature to ensure that all messages that might already be in another transaction are skipped. After the consumer's handler executes and completes, the transaction is committed.

The table includes several native columns such as `Id`, `CorrelationId`, `MessageType`, etc. The data is stored in a `BYTEA` column, additional headers in a `JSONB `column, and the attempts are tracked in a separate column.

# Scheduling Messages
The provider natively supports scheduled messages, which can be utilized for various features in the future. The Queue Table has a "scheduled time" column to hold the scheduled time for messages. This allows messages that are due to be read and skips those that are not yet due.

A simple timer controls the wakeup. After reading and processing the messages, the queue fetches the next wakeup time. The queue "wakes up" after a notification over the channel or when the timestamp is reached.

# Managing Database Objects
A trigger is created to fire on the event of the queue's deletion. This trigger ensures that all database objects are dropped when the table is dropped, making management easier and cleanly removing dependencies.

# Reply Queue
The reply queue can be used by multiple instances, with the option to override and use a dedicated reply endpoint. A "SenderId" field is used to filter new replies. Although not as efficient as dedicated queues, this approach simplifies management by avoiding the need to create a new dedicated queue and clean old ones after each start.

# Topics and Subscribers
Implementing topics and subscribers is different from queues. A subscription is essentially another queue, while a topic is a table with a trigger that deletes messages after they are added. The topic table is always empty.
When a subscription is created, a trigger is added to the Topic table. The trigger adds all items to the created subscription table before inserting them to the topic table and notifies the consumers over a dedicated channel. Deleting a topic will delete all subscribers, and deleting a subscriber will delete all related triggers.

# Auto Delete
To create something like auto deletion, a keep-alive mechanism can be implemented based on scheduled messages. Postgres itself does unfortunately not have a task scheduiler.
For example, if the auto-delete option is set to delete objects after 5 minutes of inactivity, a keep-alive message is scheduled upon startup. This message is periodically rescheduled by one of the consumers to maintain the object's active status. If there are no consumers left to reschedule the message, the queue is considered inactive and can be deleted, provided it is empty. Each client connected to the broker regularly checks the auto-delete configuration for database objects. If the keep-alive message is not up to date, the queue can be safely deleted, ensuring efficient resource management and minimizing the impact on system performance.

# A queue in postgres
```mermaid
graph TD
  A[queue_somenamespace_pingmessage] -- AFTER INSERT OR UPDATE --> B[queue_somenamespace_pingmessage_trigger]
  B -- EXECUTE --> C[queue_somenamespace_pingmessage_trigger_function]
  C -- pg_notify --> D[notify_somenamespace_pingmessage]


```

<details>

```sql
 CREATE TABLE IF NOT EXISTS queue_somenamespace_pingmessage
(
    Id UUID NOT NULL,
    CorrelationId VARCHAR(256),
    MessageType VARCHAR(256),
    ContentType VARCHAR(256),
    ScheduledTime TIMESTAMP WITH TIME ZONE,
    Data BYTEA,
    Headers jsonb,
    Attempts INT,
    PRIMARY KEY (Id)
);

--- create a index for the scheduled time to speed up the query
CREATE INDEX IF NOT EXISTS queue_somenamespace_pingmessage_scheduled_time_idx ON queue_somenamespace_pingmessage (ScheduledTime);

CREATE OR REPLACE FUNCTION queue_somenamespace_pingmessage_trigger_function()
    RETURNS trigger AS
$BODY$
DECLARE
BEGIN
    PERFORM pg_notify('notify_somenamespace_pingmessage', NEW.Id::TEXT);
    RETURN NEW;
END;
$BODY$
    LANGUAGE plpgsql VOLATILE; --- VOLATILE indicates that the result of the function may change from one call to the next because of pg_notify

CREATE OR REPLACE TRIGGER queue_somenamespace_pingmessage_trigger
AFTER INSERT OR UPDATE ON queue_somenamespace_pingmessage
FOR EACH ROW
EXECUTE PROCEDURE queue_somenamespace_pingmessage_trigger_function();
```

</details>

# an example query:

<details>

Query: 
```sql
                UPDATE queue_somenamespace_pingmessage
                SET Attempts = Attempts + 1
                WHERE Id = (
                    SELECT Id 
                    FROM queue_somenamespace_pingmessage
                    WHERE ScheduledTime <= NOW()
                    ORDER BY ScheduledTime
                    FOR UPDATE SKIP LOCKED
                    LIMIT 1 
                )
                RETURNING Id, CorrelationId, MessageType, ContentType, ScheduledTime, Data, Headers, Attempts;
```

On Success:
```
                    DELETE FROM queue_somenamespace_pingmessage
                    WHERE Id = @Id;
```
On Failure: Just commit the update 

</details>

# an example of topics and subscriptions

```mermaid
graph LR
  A[topic] -- AFTER INSERT --> B[topic_erase]
  A -- BEFORE INSERT --> C[sub_1_trigger]
  A -- BEFORE INSERT --> D[sub_2_trigger]
  B -- EXECUTE --> E[topic_erase_function]
  C -- EXECUTE --> F[sub_1_trigger_function]
  D -- EXECUTE --> G[sub_2_trigger_function]
  F -- INSERT --> H[sub_1]
  G -- INSERT --> I[sub_2]
  F -- pg_notify --> J[sub_1_channel]
  G -- pg_notify --> K[sub_2_channel]
  L[drop_sub_1_on_topic_drop] -- EXECUTE --> M[object_drop_trigger]

```

<details>
```sql
CREATE TABLE topic (
  id UUID PRIMARY KEY,
  data JSONB
);

CREATE FUNCTION topic_erase_function() RETURNS trigger AS $$
BEGIN
  DELETE FROM topic WHERE id = NEW.id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER topic_erase
AFTER INSERT ON topic
FOR EACH ROW
EXECUTE FUNCTION topic_erase_function();
;

CREATE TABLE sub_1 (
  id UUID PRIMARY KEY,
  data JSONB
);

CREATE FUNCTION sub_1_trigger_function()
RETURNS trigger AS $$
BEGIN
  INSERT INTO sub_1 (id, data) VALUES (NEW.id, NEW.data);
  PERFORM pg_notify('sub_1_channel', NEW.data::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sub_1_trigger
BEFORE INSERT ON topic
FOR EACH ROW
EXECUTE FUNCTION sub_1_trigger_function();

-- Create sub_2 table
CREATE TABLE sub_2 (
  id UUID PRIMARY KEY,
  data JSONB
);

-- Create sub_2_trigger function
CREATE OR REPLACE FUNCTION sub_2_trigger_function() RETURNS trigger AS $$
BEGIN
  INSERT INTO sub_2 (id, data) VALUES (NEW.id, NEW.data);
  PERFORM pg_notify('sub_2_channel', NEW.data::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create sub_2_trigger on topic table
CREATE TRIGGER sub_2_trigger
AFTER INSERT ON topic
FOR EACH ROW
EXECUTE FUNCTION sub_2_trigger_function();

CREATE OR REPLACE FUNCTION drop_sub_1_on_topic_drop()
RETURNS event_trigger LANGUAGE plpgsql 
AS
$$
DECLARE
    objects_dropped record;
BEGIN
    FOR objects_dropped IN SELECT * FROM pg_event_trigger_dropped_objects()
    LOOP
        IF ( objects_dropped.object_name = 'topic'
             AND
             objects_dropped.original )
        THEN
            DROP TABLE IF EXISTS sub_1; 
            DROP FUNCTION IF EXISTS sub_1_trigger_function();
            DROP EVENT TRIGGER IF EXISTS object_drop_trigger;
            DROP FUNCTION IF EXISTS drop_sub_1_on_topic_drop();
        END IF;
    END LOOP;
END;
$$;

CREATE EVENT TRIGGER object_drop_trigger
ON sql_drop
EXECUTE FUNCTION drop_sub_1_on_topic_drop();
```
</details>

**Comment by jeremydmiller** [comment]
@PascalSenn Can I suggest a simpler approach? You could do this with much less code by using Wolverine's durability agent as it is. If you "publish" by essentially persisting the outgoing envelope to the durable envelope storage, but mark the envelope as owned by "AnyNode" (0), you could effectively get the load sharing. The durability agent would already be able to pull work into other nodes from those tables. That approach would probably limit you to only having queues rather than the full blown topic/subscription model though. 

Also, from my early investigations with Marten, pg_notify/listen in Postgresql isn't reliable. I wouldn't trust that.

Likewise, the Wolverine durability agent already directly supports scheduled messages as it is.

No matter what, could you try to utilize existing infrastructure in Wolverine instead of building something completely new? And remember to think through how this would be integrated with the existing inbox/outbox tables. You *could* make the new tables really just be buddy tables that link to the existing envelope storage tables where the full `Envelope` data is already stored today.

**Comment by jeremydmiller** [comment]
And likewise, we'd have to extend it, but the `DurabilityAgent` already has some functionality for detecting offline nodes.

**Comment by jeremydmiller** [comment]
This is going to get done, but with a simpler mechanism

**Comment by elmaxe** [comment]
Any plans for implementing topics/subscriptions?
