### ISSUE TITLE
AWS SQS - RunOaktonCommands() combined with ListenToSqsQueue(...) stops the applicaiton

### ISSUE THREAD

**Issue by ddivita** [JasperFx/wolverine#241]
When using `app.RunOaktonCommands` and `WolverineOoptions.ListenToSqsQueue` makes the app stop. 

Replication:
```
  using Oakton;
  using Wolverine;
  using Wolverine.AmazonSqs;
  
  var builder = WebApplication.CreateBuilder(args);
  
  builder.Host.UseWolverine(o =>
  {
      
      o.UseAmazonSqsTransport().AutoProvision();
      
      o.ListenToSqsQueue("hpque");
  
  });
  
  var app = builder.Build();
  
  app.RunOaktonCommands(args);
```
![image](https://user-images.githubusercontent.com/3431250/225340422-083c8ab2-f9a1-4110-8e8a-dc596e33b4ac.png)

Workaround:
Use `app.Run()` and watch the spice flow.

![image](https://user-images.githubusercontent.com/3431250/225346378-cdfc669f-c8ac-422f-a3df-0faf3c2d19cc.png)

Discord:
https://discord.com/channels/1074998995086225460/1074999099855753317/1084108516861694043

**Comment by jeremydmiller** [comment]
I don't have a clue offhand yet, but I'd love to dig into this by early next week

**Comment by jeremydmiller** [comment]
@ddivita Easy money. Use:

```csharp
return await app.RunOaktonCommands(args);
```

RunOaktonCommands() returns `Task<int>`. If you just return, you don't actually execute the task. The magic Program.Main() doesn't respect it as async unless you slap an `await` in there. That's why all the sample code in the docs says `await app.******`
