### ISSUE TITLE
Combination of updating Marten inline projection and returning a cascaded event from `InvokeAsync` leads to `ConcurrencyException`

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#254]
The application [breaks](https://github.com/JasperFx/wolverine/issues/225#issuecomment-1459052921) as follows:

1. Bootstrap web API with Wolverine auto transactions and durable local queues enabled, and Marten inline projection that has `UseOptimisticConcurrency` enabled
2. Receive web request
3. `InvokeAsync<TResult>` a handler, where `TResult` contains some data for the web response
4. Inside the handler
   1. `FetchForWriting` loads a stream
   2. Append event to the  stream
   3. Return `TResult` as a cascading event
8. The inline projection listens for the appended event and updates itself
9. `ConcurrencyException` for the inline projection is raised

Is this to be expected? My impression is that this should work.

I've attempted to write a test for this. Unfortunately, it hangs as soon as `UseDurableLocalQueues` is enabled.

I've also created a [Web API example](https://github.com/agross/WolverineConcurrency) that will expose the `ConcurrencyException` (you may need to change the connection string in Program.cs first).

```csharp
using IntegrationTests;

using Marten;
using Marten.Events.Aggregation;
using Marten.Events.Projections;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

using Shouldly;

using Wolverine;
using Wolverine.Marten;
using Wolverine.Tracking;

using Xunit;

namespace PersistenceTests.Marten.Bugs;

public class concurrency_problem : PostgresqlContext
{
  [Fact]
  public async Task should_work_but_doesnt()
  {
    using var host = await Host.CreateDefaultBuilder()
                               .ConfigureServices(services =>
                               {
                                 services.AddMarten(m =>
                                         {
                                           m.Connection(connectionString: Servers.PostgresConnectionString);

                                           m.Schema
                                            .For<SomeView>()
                                            .UseOptimisticConcurrency(enabled: true);

                                           m.Projections
                                            .Add<SomeProjection>(lifecycle: ProjectionLifecycle.Inline);
                                         })
                                         .IntegrateWithWolverine();
                               })
                               .UseWolverine(w =>
                               {
                                 w.AutoApplyTransactions();
                                 // Uncomment this to make the test block (and probably turn red).
                                 // w.Policies.UseDurableLocalQueues();
                               })
                               .StartAsync();

    var id = Guid.NewGuid();

    var (_, cascadingEvent) = await host.InvokeMessageAndWaitAsync<CascadingEvent>(new SomeCommand(Id: id));
    cascadingEvent.Id.ShouldBe(id);

    using var session = host.Services.GetRequiredService<IDocumentStore>().LightweightSession();

    var stream = await session.Events.FetchStreamAsync(streamId: id);
    stream.ShouldNotBeEmpty();

    var view = session.Load<SomeView>(id: id);
    view.Id.ShouldBe(expected: id);
  }
}

public record SomeCommand(Guid Id);

public record CreatedEvent(Guid Id);

public record CascadingEvent(Guid Id);

public record SomeStream(Guid Id);

public record SomeView(Guid Id);

public class SomeProjection : SingleStreamAggregation<SomeView>
{
  public static SomeView Create(CreatedEvent ev)
    => new(Id: ev.Id);
}

public class Handler
{
  public static async Task<CascadingEvent> Handle(SomeCommand command,
                                                  IDocumentSession session)
  {
    var stream = await session.Events.FetchForWriting<SomeStream>(id: command.Id);
    stream.AppendOne(new CreatedEvent(Id: command.Id));

    return new CascadingEvent(Id: command.Id);
  }
}

```

**Comment by jeremydmiller** [comment]
Just barely starting to look at this. I'd highly recommend against using the optimistic concurrency option against a projected document though, for exactly the kind of effect you're seeing here. The `FetchForWriting()` command -- or the Wolverine aggregate handler workflow -- already deal with concurrency for you, and in a way that's probably easier to use than the optimistic concurrency on a the document type.

**Comment by jeremydmiller** [comment]
Yeah, don't use optimistic concurrency on the projected views. Only real answer here.

**Comment by agross** [comment]
> The FetchForWriting() command -- or the Wolverine aggregate handler workflow -- already deal with concurrency for you,

I understand that FetchForWriting ensures that no concurrent updates can be made against the aggregate being fetched.

The guarantee on the "write side" makes optimistic concurrency for updating the read model unnecessary now that I think about it. But it's hard to understand why being explicit makes the whole operation fail.
