### ISSUE TITLE
Handler wont compile if Touple return type contains type string

### ISSUE THREAD

**Issue by ksusac** [JasperFx/wolverine#263]
If you declare public `static async Task<(HandlerContinuation, Order, string)> LoadAsync()` in generated code you get `(var handlerContinuation, var order, var string) = await Sample.Sample.SampleHandler.LoadAsync();` and it does not compile as variable can't be named string. 

I haven't tryed with primitive types but, it might be the same.

**Comment by jeremydmiller** [comment]
@agross Returning multiple instances of the same type won't work in the codegen. The codegen uses the type to "know" how to pipe data between methods. I think all we can do is throw an explanatory exception in that case.
