### ISSUE TITLE
Ability to spawn multiple sagas from a single command

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#265]
Not sure this is a good fit for the issues I encountered today, but you wanted to me add feedback :-)

* When event Marten event forwarding is enabled, why is it prohibited to start >1 sagas from one forwarded event type?
* It seems like a cascaded message from 1 saga cannot start another saga

To give more context:

* The system I'm working on handles reservations
* When a reservation comes up (15 min in advance) it becomes "bookable"
* If the user doesn't turn the reservation into a booking, the reservation is dropped
* Booked reservations are automatically canceled at the time the original reservation ends (the user may cancel in advance)

The time-based operations appear like a good fit for a saga and scheduled messages. When a reservation is received by the system it can i.e. make it "bookable" 15 min in advance of the reservation's start. Once a user performs the booking I can send a timeout message for the cancellation.

My idea is to have 2 sagas, one for the reserveration (timed: becoming bookable, dropping it; command: turn into booking), and another one for the actual booking. The booking saga should start at the same time as the reservation saga (to collect some data from the "starting event"), but request a timeout only after the real booking has been made.

The reservation I'm talking about here is not an aggregate root. It's embedded in a stream that represents multiple reservations made for a calendar day. I designed it this way to guarantee that reservations do not overlap.

_Originally posted by @agross in https://github.com/JasperFx/wolverine/issues/253#issuecomment-1479809606_

**Comment by jeremydmiller** [comment]
@agross Just not something I'd considered before. Makes sense.

**Comment by jeremydmiller** [comment]
@agross Little more complicated than maybe it sounded initially. I'd assume that you don't just start a Saga by saving it. You'd also want to spawn additional messages. And those messages may need to be associated with one of the Saga objects returned.

I'm thinking of adding a virtual `StartupMessages() : IEnumerable<object>`  method to `Saga` that Wolverine would know to call when a new `Saga` is returned that way. Or instead, you call the `Saga.Start()` for the original message type, and that potentially spawns cascaded messages. Hmm.

Need an explicit EnqueueCascadingAsync() that takes in the SagaId.

**Comment by agross** [comment]
I think I don't understand. Today I spawn the saga from the Marten event (via forwarding) like so:

```csharp
public class ReservationSaga : Saga
{
  public string Id { get; set; } = null!;
  public string CalendarDayId { get; set; } = null!;

  public async Task Start(ReservationPlaced placed,
                          IMessageContext context)
  {
    Id = placed.ReservationId;
    CalendarDayId = CalendarDayId.For(placed.WorkplaceId, placed.Date);

    var start = placed.Date.ToDateTime(placed.From, DateTimeKind.Utc);
    var end = placed.Date.ToDateTime(placed.To, DateTimeKind.Utc);
    var bookableOn = start.AddMinutes(-15);
    var autoCancelOn = start.AddMinutes(15);
    
    await context.SendAsync(new CanBeBooked(Id),
                            new DeliveryOptions { ScheduledTime = bookableOn });

    await context.SendAsync(new AutoCheckout(Id),
                            new DeliveryOptions { ScheduledTime = end });

    await context.SendAsync(new AutoCancel(Id),
                            new DeliveryOptions { ScheduledTime = autoCancelOn });
  }
  
  // ...
}
```

I tried to capture `ReservationPlaced` in another "booking" saga that would only handle the booking-related timeouts like auto checkout. It would also need to handle `AutoCancel` to complete it if the user never turned the reservation into a booking.

**Comment by jeremydmiller** [comment]
Meh, I'm going to wimp out and make a documentation note that you'll have to explicitly pass the Saga Id around in any messages sent from the action that also returns a Saga object. And make the implementation relatively simple just to get things going here.

**Comment by jeremydmiller** [comment]
> > Wolverine's behind the scenes SagaId tracking through envelope headers
> 
> I wasn't aware this existed. I never bothered to have a look at the binary `body` column of the `incoming_envelopes` table. But I wondered why that column wasn't JSON (if Wolverine uses Marten to store scheduled messages).

Couple reasons:

1. There's a pretty lightweight, custom binary serialization of all of the Envelope that's a leftover from FubuTransportation/LightningQueues which was itself originally an evolution of RhinoQueues. There's some trivia for you
2. Wolverine also supports EF Core & Sql Server, and will eventually support CosmosDb or DyanamoDb maybe for this too, so no Postgresql JSONB support

**Comment by agross** [comment]
> Fubu

Here's some trivia for you: About 13 years ago I build a system for a crematorium using the original FubuMVC 😄 

> Wolverine also supports EF Core & Sql Server

That's what I figured would be the most obvious reason to use binary serialization!

**Comment by jeremydmiller** [comment]
And I'm glad you'll still talk to me after the FubuMVC thing! Lot of lessons learned both positive and (more) negative from FubuMVC that went into Wolverine & Marten. The Wolverine codegen strategy was my theory about how to have fubu-style flexibility in a highly configurable Russian Doll pipeline w/o having crappy perf like fubu did.

**Comment by agross** [comment]
Likewise, I'm glad you still talk to me after the recent FP "incident". Perf was never an issue for us with Fubu as the system was pretty lightly used (<= 10 users or so). And it was so much better than the ASP.NET MVC version that was available back then. 👍
