### ISSUE TITLE
Optimized usage for AOT and Serverless

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#34]
Not exactly sure what this entails yet. Thinking that it means some codegen ahead of time.

**Comment by jeremydmiller** [comment]
Going to require some significant changes to eliminate reflection usage, not to mention the dynamic codegen.

**Comment by dpetrovych** [comment]
I was trying to find a good example of Wolverine integrated for Azure Functions with Service Bus trigger. Do you have one, or perhaps can point me in the right integration stragegy. Should I directly call some abstractions, like `IReceiver` from a triggered function code to suply message and a listener to confirm successful handling? If so, how to get a right entry point in a function code?

**Comment by jeremydmiller** [comment]
@dpetrovych Man, I'm sorry this snuck by me. I just now saw this. For serviceless integration, you'd need to just call IMessageBus directly. There's no native support yet in Wolverine. Honestly, it comes up so infrequently that this just isn't likely going to change anytime soon
