### ISSUE TITLE
Saga not found after invoking a saga handler

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#347]
Continued from https://github.com/JasperFx/wolverine/issues/310#issuecomment-1534364127

The sequence of events:

1. Invoke domain model, it emits an `First` event that is forwarded to Wolverine
2. `First` event is captured by `Saga1.Start` which cascades a `Saga2` instance. `Saga2` has a handler for the `Second` event.
3. Let a minute pass. Perhaps check the database to see that `Saga2` is persisted.
4. Invoke domain model again, which emits an instance of the `Second` event that is forwarded to Wolverine
5. Wolverine captures `Second` and invokes the `Saga2` handler (where I set a breakpoint)
6. The handler cascades a scheduled a message an returns
7. Marten fails with a "document not found exception" trying to persist the `Saga2`.

**Comment by agross** [comment]
Wow, I've got a repro. Quite a journey. There are lots of scenarios that work. But it breaks if `Saga2`'s handler cascades a message (scheduled or not) in step 6.

For your enjoyment: https://github.com/agross/wolverine-issue-347

Please adjust `appsettings.json` to fit your database.

**Comment by jeremydmiller** [comment]
Call `/first` then `/second` to make it happen?

**Comment by agross** [comment]
Exactly. I used Swagger UI.

**Comment by jeremydmiller** [comment]
And drum roll please....

"works on my box". Using Wolverine 0.9.18

Sorry, no love here. But thanks for going through this much effort!

**Comment by agross** [comment]
That's interesting that you do not see the exception in the logs. The exception won't show up on Swagger UI, did you also check debug output?

I just tried the repro again on a secondary machine and it still happens. Also using 0.9.18 according to `PackageReferences`:

```
fail: Wolverine.Runtime.WolverineRuntime[105]
      Failed to process message Second#01889f2c-48df-4ee6-84bd-1a1c2b283707 from local://repro.handlers.second/
      Marten.Exceptions.NonExistentDocumentException: Nonexistent document Repro.Sagas.SecondSaga: 42
         at Marten.Internal.UpdateBatch.throwExceptionsIfAny()
         at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
         at Internal.Generated.WolverineHandlers.SecondHandler1502839579.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Internal.Generated.WolverineHandlers.SecondHandler1502839579.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation)
```

<img width="762" alt="2023-06-09_10-06-38" src="https://github.com/JasperFx/wolverine/assets/16245/021444cf-9301-4af6-9a7c-fa0d2b594e6c">

**Comment by agross** [comment]
I think I have a hunch why this doesn't work. It's probably related to `Policies.UseDurableLocalQueues()`.

When `/second` is invoked, this causes two operations in the database:

1. Store an incoming envelope in `wolverine_messages.wolverine_incoming_envelopes` for `Third`, to be processed later or immediately
2. Update the `Second` saga document using `mt_update_secondsaga`

```
Marten executed in 5 ms, SQL:
insert into wolverine_messages.wolverine_incoming_envelopes (body, id, status, owner_id, execution_time, attempts, message_type, received_at) values (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7);;
select saga_events.mt_update_secondsaga(:p8, :p9, :p10, :p11);
  p0: System.Byte[]
  p1: 0188cdb7-a1ae-45e8-9666-973a3ea7aac0
  p2: Scheduled
  p3: 0
  p4: 6/18/2023 8:55:53 AM +00:00
  p5: 0
  p6: Repro.Sagas.Third
  p7: local://repro.sagas.third/
  p8: {"Id":"44444"}
  p9: Repro.Sagas.SecondSaga
  p10: 42
  p11: 0188cdb7-a1af-47fe-b637-7d34b57cbd11
```

These two operations are represented by a Marten `UpdateBatch`. They are only combined into one batch if `UseDurableLocalQueues()` is enabled. Without `UseDurableLocalQueues()` only the `mt_update_secondsaga` operation would be executed (and succeed).

It looks like that on my machine the first operation in the `UpdateBatch` "eats" the `final_version` returned by the `mt_update_secondsaga` function.

The screenshot below was taken after the all operations were executed and their results are being verified:

<img width="708" alt="2023-06-18_11-05-45" src="https://github.com/JasperFx/wolverine/assets/16245/6025a051-34ad-4dcf-aaca-1d0fb8c42f4d">

At that point in time the `reader` already contains the ID of the new saga version that was returned by `mt_update_secondsaga`. Postgres logged the execution of that function with the new version to set as `$4`:

```
2023-06-18 10:55:43.819 CEST [175] LOG:  execute <unnamed>: select saga_events.mt_update_secondsaga($1, $2, $3, $4)
2023-06-18 10:55:43.819 CEST [175] DETAIL:  parameters: $1 = '{"Id": "42"}', $2 = 'Repro.Sagas.SecondSaga', $3 = '44444', $4 = '0188cdb7-a1af-47fe-b637-7d34b57cbd11'
```

This is the `reader` while still on the same breakpoint as above:

<img width="455" alt="2023-06-18_11-07-56" src="https://github.com/JasperFx/wolverine/assets/16245/c7bc2c39-6afa-42c8-824d-6860c4824135">

After the `INSERT INTO wolverine_incoming_envelopes ...` is post-processed ([which is a no-op](https://github.com/JasperFx/wolverine/blob/d4a48488a45d7a39dda3a3faa3783df68417deb7/src/Persistence/Wolverine.Marten/Persistence/Operations/StoreIncomingEnvelope.cs#L48-L50)) the [reader is moved to the next result](https://github.com/JasperFx/marten/blob/ae9ff018769b908280688c95e13c684fe6d835c0/src/Marten/Internal/UpdateBatch.cs#L184), which does not exist.

Only then the second operation `mt_update_secondsaga` is post-processed. It expects a result in the reader to be available, but the first operation already read past it.

I _think_ `StoreIncomingEnvelope` should be implementing `NoDataReturnedCall`.

**Comment by jeremydmiller** [comment]
@agross Yeah, any operation that doesn't return a result. Easy change later today.
