### ISSUE TITLE
Cascaded message handing when using `InvokeAsync` vs. `InvokeAsync<T>` and Marten Event Forwarding unclear

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#348]
```cs
public static SomethingHandler
{
  public static ResponseMessage Handle(Something message)
  {
    return new ResponseMessage();
  }
}
```

There are 2 options to actively call the handler from e.g. a Web API:

- `InvokeAsync(new Something())`
- `InvokeAsync<ResponseMessage>(new Something())`

Optionally, the user may configure to forward Marten event forwarding which is a third way to invoke a handler: `services.AddMarten().EventForwardingToWolverine()`.

Depending on the `InvokeAsync` call I found that `ResponseMessage` is

* cascaded (passed to handlers handling `ResponseMessage`) when using `InvokeAsync(new Something())`
* not cascaded, but returned to the `InvokeAsync<ResponseMessage>(new Something())` call site

If Marten event forwarding is enabled and `ResponseMessage` is generated by appending to a Marten event stream like this:

```cs
public static SomethingHandler
{
  public static ResponseMessage Handle(Something message)
  {
    return CallMartenToAppendResponseMessageToAStreamAndReturnTheMessage();
  }
}
```

...then using the `InvokeAsync(new Something())` will cascade the message twice to `ResponseMessage` handlers (once forwarded from Marten, once as the cascaded message).

You can use the [repro](https://github.com/agross/wolverine-issue-347/blob/master/Repro/Program.cs#L29) to test this. Replace the linked `InvokeAsync` call with the non-generic variant as see how `FirstSaga.Start` is called twice:

```
FirstSaga Start
FirstSaga Start
```

**Comment by jeremydmiller** [comment]
Honestly, it's going to be a lot cleaner in the end using Wolverine.Http instead of treating Wolverine like it's MediatR. I'll take a look at this early next week though

**Comment by jeremydmiller** [comment]
@agross Everything here is working exactly as designed. I think this might be more a matter of documentation.

And I want to make it as loud and clear as possible in the documentation that I'm strongly recommending against this exact kind of usage (MediatR style) because it's too easy to get confused here.
