### ISSUE TITLE
Start new event stream via `AggregateHandler`

### ISSUE THREAD

**Issue by schnerring** [JasperFx/wolverine#356]
I've been toying around with Marten and Wolverine to wrap my head around DDD, CQRS, and event sourcing. I really love the projects so far, thanks for the great work! Also, thanks @oskardudycz your EventSourcing.NetCore repo. The event sourcing workshop samples are amazing, especially the part where you [demonstrate the immutable/mixed/mutable business logic with Marten](https://github.com/oskardudycz/EventSourcing.NetCore/tree/e3cc05bb51eaa24f931d4c0c47fccf3f10d9bccc/Workshops/IntroductionToEventSourcing/Solved/08-BusinessLogic.Marten).

[I also really like Wolverine's convention-based approach for `AggregateHandler`s you describe in the docs](https://wolverine.netlify.app/guide/durability/marten/#event-store-cqrs-support).

[Looking at the code-gen logic inside `LoadAggregateFrame`](https://github.com/JasperFx/wolverine/blob/70a6c847286e43a615a4b2f0f9e9f317fdd2f300/src/Persistence/Wolverine.Marten/Codegen/LoadAggregateFrame.cs), `AggregateHandler`s only really work for existing aggregate streams containing events. 

I initially searched the code base for `StartStream` because I was wondering if aggregate handlers could also be used to start new streams. This way I came across this `TODO` item in your code and was wondering if this is a feature you're planning (I couldn't find an issue)?

https://github.com/JasperFx/wolverine/blob/70a6c847286e43a615a4b2f0f9e9f317fdd2f300/src/Http/WolverineWebApi/Marten/Orders.cs#L82-L91

As an aside, I'm trying to combine the [imperative approach from the _Aggregates, Events, Repositories_ Marten docs](https://wolverine.netlify.app/guide/durability/marten/#event-store-cqrs-support) with the [mixed business logic approach from Oskars sample repo](https://github.com/oskardudycz/EventSourcing.NetCore/blob/e3cc05bb51eaa24f931d4c0c47fccf3f10d9bccc/Workshops/IntroductionToEventSourcing/Solved/08-BusinessLogic.Marten/Mixed/BusinessLogic.cs) and apply that to the [`Order` sample from the _Event Store & CQRS Support_ Wolverine docs](https://wolverine.netlify.app/guide/durability/marten/#event-store-cqrs-support).

Here's what the result could look like:

```csharp
public class Order
{
    public static OrderCreated CreateWithItems(Item[] items)
    {
        // Inject more domain logic here to make the factory method actually useful
        // ...

        var @event = new OrderCreated(items);

        // This "Apply()" is superfluous and just to demonstrate the pattern
        var order = new Order(@event);

        return @event;
    }

    // This basically acts as an "Apply()" method Marten also understands
    // It works better with nullable reference types
    private Order(OrderCreated created)
    {
        foreach (var item in created.Items) Items[item.Name] = item;
    }

    // [...]
    
    // Push the domain logic from the handler into the aggregate
    public void MarkItemAsReady(string itemName)
    {
	if (!Items.TryGetValue(itemName, out var item))
            // Some crude validation
            throw new InvalidOperationException($"Item {itemName} does not exist in this order");
       
        // Mark this item as ready
        var @event = new ItemReady(item.Name);

        // Not doing this in a purist way here, but just
        // trying to illustrate the Wolverine mechanics
        Apply(@event)
	    
        return @event;
    }

    private void Apply(ItemReady ready)
    {
        Items[ready.Name].Ready = true;
    }

    public bool IsReadyToShip()
    {
        return Shipped == null && Items.Values.All(x => x.Ready);
    }
}
```

I like this design because it internalizes all the `Apply()` methods. It also pushes the domain logic into the aggregate to ensure consistency. Instead of adding the applied events imperatively on a collection of `AggregateBase`, they're returned from the aggregate methods instead. This makes the code less stateful, because I can simply `yield return` the returned events in the aggregate handler instead of having to dequeue the events from the collection of `AggregateBase` first. The refactored command handler looks like this:

```csharp
[AggregateHandler]
public static IEnumerable<object> Handle(MarkItemReady command, Order order)
{
    yield return order.MarkItemAsReady(command.ItemName);

    // If the order is ready to ship, also emit an OrderReady event
    if (order.IsReadyToShip())
    {
        yield return new OrderReady();
    }
}
```

From the docs on the aggregate handler method signature:

> The 2nd argument should be the aggregate -- either the aggregate itself (Order) or wrapped in the Marten IEventStream<T> type (IEventStream<Order>).

I guess the above constraint would need to change, here are some ideas:

```csharp
// Allow aggregate handlers without aggregate argument
[AggregateHandler]
public static IEnumerable<object> Handle(CreateOrder command)
{
    yield return Order.Create(command.Items);
}

// make Order nullable
public static IEnumerable<object> Handle(CreateOrder command, Order? order) {}

// an empty IEventStream<T> would work without changing conventions
public static IEnumerable<object> Handle(CreateOrder command, IEventStream<Order> order) {}
```

What do you think?

Maybe this could also be a good sample for the [empty _Aggregate Handlers and Event Sourcing_ Wolverine docs](https://wolverine.netlify.app/guide/durability/marten/aggregates.html)?

**Comment by jeremydmiller** [comment]
@schnerring Sorry for the very slow response, this is *very close* to being there, the only issue now is to make the AggregateHandler convention ignore these methods. To create a new stream, you can do this:

```csharp
public static class StartStreamMessageHandler
{
    public static StartStream Handle(StartStreamMessage message)
    {
        return MartenOps.StartStream<NamedDocument>(message.Id, new AEvent(), new BEvent());
    }
    
    public static StartStream Handle(StartStreamMessage2 message)
    {
        return MartenOps.StartStream<NamedDocument>(message.Id, new CEvent(), new BEvent());
    }
}
```
