### ISSUE TITLE
Double .cs file extension in codegen

### ISSUE THREAD

**Issue by ejsmith** [JasperFx/wolverine#386]
When I do `dotnet run -- codegen write` as part of my build for non-dev builds, it generated files with double .cs extensions like this:

![image](https://github.com/JasperFx/wolverine/assets/282584/2dc95065-cd4d-4d57-b657-0db5827d45d9)

**Comment by jeremydmiller** [comment]
I hear you, and you and a couple other folks have reported the same thing before, but **I cannot reproduce this locally**

**Comment by ejsmith** [comment]
Awesome. Thanks! Guess it didn't make the latest release, but glad to know you found it and fixed it.
