### ISSUE TITLE
Interoperability with Azure Service Bus

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#399]
Need to expose an API to replace the envelope mapping.

Honestly, wait for someone to ask for it and see what they need specifically.

**Comment by dpetrovych** [comment]
Can there be an interoperability for NServiceBus message format with Azure SB?

**Comment by jeremydmiller** [comment]
@dpetrovych Sorry for the very, very slow response, but yes. Really just waiting for someone to ask for it. NSB to Wolverine was quite a bit easier than MassTransit to Wolverine

**Comment by jeremydmiller** [comment]
And this was done quite awhile ago
