### ISSUE TITLE
Missing tables in patch command line tooling

### ISSUE THREAD

**Issue by devployment** [JasperFx/wolverine#418]
Wolverine (0.9.19) creates the following tables running locally.

- `wolverine_nodes`
- `wolverine_node_assignments`
- `wolverine_control_queue`

Trying to create the migrations scripts, from local code branch running a Wolverine 0.9.19, but pointed at a remote Azure database does not detect the changes and always returns

`No differences were detected between the configuration and the actual database`

Tried the following commands

- `dotnet run -- db-patch`
- `dotnet run -- marten-patch`

If I run `dotnet run -- db-dump export.sql` on a newly created local database, the three tables mentioned above are missing as well in the full dump.

Somehow these new tables are excluded from the tooling.

**Comment by jeremydmiller** [comment]
I got this one fixed before pushing 1.0 yesterday. The file pathing issue is still outstanding as I'll have to dip into Weasel for that one.
