### ISSUE TITLE
Frame chain is being re-arranged

### ISSUE THREAD

**Issue by gztamas** [JasperFx/wolverine#42]
Using .NET 6 and Wolverine 0.8.2 I get an exception when invoking commands of different types in parallel.
A gist reproducing the issue can be found here:
https://gist.github.com/gztamas/50997c72c61b9ed7809156bdb76c7be1

According to the gitter discussion with @jeremydmiller it might be an issue of insufficient/bad locking.

**Comment by jeremydmiller** [comment]
Gonna try to beat it two ways:

1. Write a test that throws a lot of parallel requests right off the bat to try to reproduce it, improve locking
2. A "warmup" option like Marten's that would eliminate the issue altogether by building everything upfront
