### ISSUE TITLE
Avoid using IHostEnvironment.IsDevelopment in OptimizeArtifactWorkflow

### ISSUE THREAD

**Issue by devployment** [JasperFx/wolverine#423]
What was done for Marten in https://github.com/JasperFx/marten/issues/2367 would make sense for Wolverine as well. 

From the ticket
> our local machine uses the environment Local and Development is used in one of the deployed environments.

We face the exact same issue.

**Comment by jeremydmiller** [comment]
Funny, I thought about that a bit the other day. That's a quick "I take pull requests" for the inevitable 1.0.1 early next week
