### ISSUE TITLE
What is "A-Frame" Architecture, as mentioned on the Best Practices page?

### ISSUE THREAD

**Issue by SilasReinagel** [JasperFx/wolverine#424]
https://wolverine.netlify.app/tutorials/best-practices.html

This is unclear and seems non-standard. Could we add a definition, or brief explanation? The idea is intriguing...

**Comment by jeremydmiller** [comment]
@SilasReinagel See this fantastic paper from Jim Shore: https://www.jamesshore.com/v2/projects/nullables/testing-without-mocks

**Comment by SilasReinagel** [comment]
Thank you! This is a fantastic reference article!
