### ISSUE TITLE
DbContext singleton lifetime causes issues

### ISSUE THREAD

**Issue by ejsmith** [JasperFx/wolverine#425]
I have service classes and other background jobs that need to access the DbContext. All of those things sharing the same context instance causes all kinds of problems.

- All instances are sharing the same entity ChangeTracker which means it's easy for me to get dirty / stale entities.
- All changes are being included in the same unit of work.
- If the DbContext is disposed anywhere (which it is supposed to be disposed ASAP), then other code will run into issues with accessing a disposed instance.
- Try to replace `AddDbContextWithWolverineIntegration` and can't access `DbContextOutbox` to register it myself manually.

I tried to dig through the code to figure out what the benefit of the lifetime being set to singleton vs the default of scoped was, but I couldn't find anything.

Is the singleton lifetime really needed?

**Comment by jeremydmiller** [comment]
I agree that it would be absolutely harmful to register the `DbContext` as a singleton, but that helper registers `DbContext` as `Scoped`, but the `DbContextOptions` as a singleton. Is *that* getting you?

Here's the relevant code where you can clearly see what I'm talking about:

https://github.com/JasperFx/wolverine/blob/main/src/Persistence/Wolverine.EntityFrameworkCore/WolverineEntityCoreExtensions.cs#L24-L28

**Comment by ejsmith** [comment]
Hmm... now I'm confused because I changed it to my own implementation and things worked better. Let me dig further and let you know.
