### ISSUE TITLE
Improved Interoperability in Messaging

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#429]
All the envelope mapping needs to be exposed and easier to alter. 

Ideas:

* Conventional application of MassTransit or NSB interop
* Support for CloudEvents? Would happily span most transports
* What else?

**Comment by solvingproblemswithtechnology** [comment]
Any system that just sends a Json into a Queue/Topic/Exchange. I see it as follow:

Wolverine knows the type and the queue where they are receiving the message. So if there's no header added, it should be (theoretically) able to infer the type to deserialize it to from the context. That should work in almost all of the cases unless you want to cover expecifically another framework. And it would follow [Postel's Law (Robustness Principle)](https://en.wikipedia.org/wiki/Robustness_principle). 

If you are working with a system that wraps the message with extra info, you can just add it to your Type and Wolverine will deserialize it correctly. If it's adding extra Headers, exponsing in some way them should do the trick.

In case there's a need for more complex features, such retries an intereop would be needed, but for most cases I can think of, the basic approach just works.

**Comment by jeremydmiller** [comment]
"If you are working with a system that wraps the message with extra info, you can just add it to your Type and Wolverine will deserialize it correctly. If it's adding extra Headers, exponsing in some way them should do the trick."

-- that's not a "just", that's actually complicated and quite potentially expensive at runtime. Already hit that with the MassTransit interop :-)

**Comment by solvingproblemswithtechnology** [comment]
@jeremydmiller Yes! It's not a just! I forgot to add quotes as you are using code generation and all of that. I didn't meant at runtime but compilation time through convetions or something. 

Testing this version today, kudos!
