### ISSUE TITLE
Handler discovery after publish as single file

### ISSUE THREAD

**Issue by sharpzilla** [JasperFx/wolverine#432]
Hi, there. I have a problem when publishing my web application with option [PublishSingleFile](https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run). When my app is starting in IIS I get an error when try discover handler for command. My handlers and commands located in project Application. Message bus invoked in my API project.
Also I have .props file in which I set project properties: build output name -combination solution name + project name and also the same for namespaces.

**Comment by jeremydmiller** [comment]
Okay, so what's the exception? Or what is not happening correctly?

**Comment by sharpzilla** [comment]
In logs I see that message:
```

> [ERR] Failed to create a message handler for TaskScheduler.Application.Commands.ActiveJobsCommand
> 
> Wolverine.Runtime.Routing.IndeterminateRoutesException: Could not determine any valid subscribers or local handlers for message type TaskScheduler.Application.Commands.ActiveJobsCommand
> 
>    at Wolverine.Runtime.Routing.EmptyMessageRouter`1.FindSingleRouteForSending()
> 
>    at Wolverine.Runtime.WolverineRuntime.findInvoker(Type messageType)

```

**Comment by sharpzilla** [comment]
Also my publish setting: 
Net 7.0, framework-dependent, win-x64,  produce single file, enable ready to run compilation. When I turn off produce single file and publish my project, there are alot of files but app run normally.

**Comment by jeremydmiller** [comment]
Just for fun, in whatever project you have your `Program.Main` method, try sticking this in the UseWolverine() setup:

```csharp
opts.Discovery.IncludeAssembly(typeof(ONE OF YOUR MESSAGE HANDLERS).Assembly);
```

and try that?

You can know quickly w/o running the actual app by using `dotnet run -- describe` and checking out the section on handlers. That will tell you where and how it's looking for handlers too that might be helpful.

**Comment by sharpzilla** [comment]
My project stucture 

> src\Application
> src\BackgroundJobs => Program.cs
> src\Domain
> src\Domain.Shared
> src\Infrastructure

No result when trying with that line:
`opts.Discovery.IncludeAssembly(typeof(ONE OF YOUR MESSAGE HANDLERS).Assembly);`


There is an error message in log file:
> 2023-06-28 08:51:04.038 +03:00 [ERR] Failed to create a message handler for MyCompany.TaskScheduler.Application.Commands.ActiveJobsCommand
> System.InvalidOperationException: Compilation failures!
> 
> CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Wolverine' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Wolverine' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'MyCompany' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'MyCompany' could not be found (are you missing a using directive or an assembly reference?)
> CS0103: The name 'MyCompany' does not exist in the current context
> 
> Code:
> 
> // <auto-generated/>
> #pragma warning disable
> using Lamar;
> 
> namespace Internal.Generated.WolverineHandlers
> {
>     // START: ActiveJobsCommandHandler1997934307
>     public class ActiveJobsCommandHandler1997934307 : Wolverine.Runtime.Handlers.MessageHandler
>     {
>         private readonly Lamar.IContainer _rootContainer;
> 
>         public ActiveJobsCommandHandler1997934307(Lamar.IContainer rootContainer)
>         {
>             _rootContainer = rootContainer;
>         }
> 
> 
> 
>         public override async System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
>         {
>             await using var nestedContainer = (Lamar.IContainer)_rootContainer.GetNestedContainer();
>             
>             /*
>             * Dependency: new TaskSchedulerContext(options)
>             * 
>             * Dependency: Lambda Factory of DbContextOptions<MyCompany.TaskScheduler.Infrastructure.Persistence.TaskScheduler.TaskSchedulerContext>
>             * The scoping is Scoped, so a Lambda registration requires
>             * the usage of a nested container for resolution for correct scoping.
>             * A formal factory provider may be an alternative
>             * 
>             * 
>             * Dependency: Lambda Factory of DbContextOptions<MyCompany.TaskScheduler.Infrastructure.Persistence.TaskScheduler.TaskSchedulerContext>
>             * The scoping is Scoped, so a Lambda registration requires
>             * the usage of a nested container for resolution for correct scoping.
>             * A formal factory provider may be an alternative
>             */
>             var taskSchedulerRepository = nestedContainer.GetInstance<MyCompany.TaskScheduler.Domain.TaskScheduler.Interfaces.ITaskSchedulerRepository>();
>             var activeJobsCommand = (MyCompany.TaskScheduler.Application.Commands.ActiveJobsCommand)context.Envelope.Message;
>             var outgoing1 = await MyCompany.TaskScheduler.Application.Commands.ActiveJobsHandler.Handle(activeJobsCommand, taskSchedulerRepository, cancellation).ConfigureAwait(false);
>             
>             // Outgoing, cascaded message
>             await context.EnqueueCascadingAsync(outgoing1).ConfigureAwait(false);
> 
>         }
> 
>     }
> 
>     // END: ActiveJobsCommandHandler1997934307
>     
>     
> }
> 
> 
>    at JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(String code)
>    at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
>    at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
>    at Wolverine.Runtime.Handlers.HandlerGraph.HandlerFor(Type messageType)
>    at Wolverine.Runtime.WolverineRuntime.Wolverine.Runtime.IExecutorFactory.BuildFor(Type messageType)
>    at Wolverine.Runtime.WolverineRuntime.findInvoker(Type messageType)
> 2023-06-28 08:51:04.043 +03:00 [ERR] Error has occured
> System.InvalidOperationException: Compilation failures!
> 
> CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Wolverine' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Wolverine' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'MyCompany' could not be found (are you missing a using directive or an assembly reference?)
> CS0246: The type or namespace name 'MyCompany' could not be found (are you missing a using directive or an assembly reference?)
> CS0103: The name 'MyCompany' does not exist in the current context
> 
> Code:
> 
> // <auto-generated/>
> #pragma warning disable
> using Lamar;
> 
> namespace Internal.Generated.WolverineHandlers
> {
>     // START: ActiveJobsCommandHandler1997934307
>     public class ActiveJobsCommandHandler1997934307 : Wolverine.Runtime.Handlers.MessageHandler
>     {
>         private readonly Lamar.IContainer _rootContainer;
> 
>         public ActiveJobsCommandHandler1997934307(Lamar.IContainer rootContainer)
>         {
>             _rootContainer = rootContainer;
>         }
> 
> 
> 
>         public override async System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
>         {
>             await using var nestedContainer = (Lamar.IContainer)_rootContainer.GetNestedContainer();
>             
>             /*
>             * Dependency: new TaskSchedulerContext(options)
>             * 
>             * Dependency: Lambda Factory of DbContextOptions<MyCompany.TaskScheduler.Infrastructure.Persistence.TaskScheduler.TaskSchedulerContext>
>             * The scoping is Scoped, so a Lambda registration requires
>             * the usage of a nested container for resolution for correct scoping.
>             * A formal factory provider may be an alternative
>             * 
>             * 
>             * Dependency: Lambda Factory of DbContextOptions<MyCompany.TaskScheduler.Infrastructure.Persistence.TaskScheduler.TaskSchedulerContext>
>             * The scoping is Scoped, so a Lambda registration requires
>             * the usage of a nested container for resolution for correct scoping.
>             * A formal factory provider may be an alternative
>             */
>             var taskSchedulerRepository = nestedContainer.GetInstance<MyCompany.TaskScheduler.Domain.TaskScheduler.Interfaces.ITaskSchedulerRepository>();
>             var activeJobsCommand = (MyCompany.TaskScheduler.Application.Commands.ActiveJobsCommand)context.Envelope.Message;
>             var outgoing1 = await MyCompany.TaskScheduler.Application.Commands.ActiveJobsHandler.Handle(activeJobsCommand, taskSchedulerRepository, cancellation).ConfigureAwait(false);
>             
>             // Outgoing, cascaded message
>             await context.EnqueueCascadingAsync(outgoing1).ConfigureAwait(false);
> 
>         }
> 
>     }
> 
>     // END: ActiveJobsCommandHandler1997934307
>     
>     
> }
>

**Comment by jeremydmiller** [comment]
I'm sure it's a real issue, but there's nothing actionable to do to fix whatever it is without a lot more information. I think my advice at this point would be to pre-generate all types before doing the publishing here.
