### ISSUE TITLE
Transactional error handler fails to intercept desired exception

### ISSUE THREAD

**Issue by lofbacke** [JasperFx/wolverine#433]
I am using Marten and Wolverine. I want to intercept exceptions of type `ExistingStreamIdCollisionException` so that I can return a user-friendly error message in my HTTP endpoint response as a 400. Here is the code for the endpoint and handler:
```cs
public record StartThing(Guid ThingId, string Stuff);

public static class StartThingEndpoint
{
    [WolverinePost($"{Routes.Things}/start")]
    public static Task StartThing(StartThing command, IMessageBus bus) =>
        bus.InvokeAsync(command);
}

public static class StartThingHandler
{
    public static void Handle(StartThing command, IDocumentSession session)
    {
        var @event = new ThingStarted(command.ThingId, command.Stuff);
        session.Events.StartStream<Thing>(command.ThingId, @event);
    }
}
```

Since the exception is not thrown until the transaction is automatically committed when the `IMessageBus.InvokeAsync()` call completes, I am attempting to intercept the `ExistingStreamIdCollisionException` as follows:
```cs
builder.Host.UseWolverine(options =>
{
    options.Policies.AutoApplyTransactions();

    options.Policies.OnException<ExistingStreamIdCollisionException>().Discard().And(async (_, lifecycle, _) => {
        if (lifecycle.Envelope?.Failure is not ExistingStreamIdCollisionException ex)
            return;

        await lifecycle.RespondToSenderAsync($"{ex.AggregateType.Name} with provided ID already exists");
    });
});
```

I've omitted some additional code that actually translates the error handler string response into a proper `IResult`, but it's irrelevant to the issue at hand. I've confirmed that the exception policy is not being executed at all. However, I am still new to the critter stack and I'm sure I could be doing something wrong. Is this a real bug? Or is there a better way to handle this?

Thanks in advance!

**Comment by jeremydmiller** [comment]
@lofbacke Sorry man, I read it much more closely this morning. When you're calling `InvokeAsync()` or `InvokeAsync<T>()` to execute a message inline,  only the "Retry" actions are used. So your call to `Discard()` does nothing, and the same with the custom `RespondToSenderAsync()` in this case.

I think for what you want to do here, I'd recommend using HTTP middleware that does a catch, then writes the HTTP status code. I'm happy to help with that one, and it'd be a good example usage of middleware.

And as soon as I get 1.0.1 up, you could write:

```csharp
public record StartThing(Guid ThingId, string Stuff);

public static class StartThingEndpoint
{
    [WolverinePost($"{Routes.Things}/start")]
    [EmptyResponse]
    public static IStartStream StartThing(StartThing command) 
    {
         var @event = new ThingStarted(command.ThingId, command.Stuff);
         return MartenOps.StartStream(command.ThingId, @event);
    }
}
```

**Comment by lofbacke** [comment]
Ah, understood. Thanks so much for the response, @jeremydmiller.

A few follow-up questions based on your comments above:

1. If `Discard()` calls can’t be used with inline message executions, what is an example use case for combining that policy with `RespondToSenderAsync()`?
2. I looked at HTTP middleware as an option before settling on the policy approach, but decided against it. Unfortunately, I’ve slept several times since I made that decision, so I can’t remember why. 😅 I’d love to see an example using the middleware.
3. I like how clean the code snippet you posted looks. Out of curiosity, what advantage does the `MartenOps` class give you over the current implementation with `IDocumentStore`?

Thanks in advance!

**Comment by jeremydmiller** [comment]
1. `Discard()` means throw this away and don't move this to any kind of error queue. It's intended for when you recognize that a message is invalid for some reason and could never be processed. `RespondToSenderAsync()` is useful for telling the original caller about what failed. That's only usable inside of asynchronous messaging.
2. I think this would be a great example, so I might try to blog it and add the example to the docs 
3. It's no different in terms of actual functionality, but it leads to a pure function that's synchronous for easy unit testing

**Comment by lofbacke** [comment]
Great, that all makes sense. Looking forward to the blog post and Wolverine 1.0.1! I’ll go ahead and close this issue. Thanks again and keep up the great work!
