### ISSUE TITLE
High memory impact and starting time on First request

### ISSUE THREAD

**Issue by smartcodinghub** [JasperFx/wolverine#435]
Hi!

First of all, thanks for all the work, the project looks awesome. I would like some things to changem but mostly very smalls stuff.

I have issues with the memory consumption on startup. Previously, I was always between 27 and 48 Mb of RAM. Since I added Wolverine, the first request takes 3 times as long to run and spikes up to 183 Mb. For a microservice this small and using kubernetes, it introduces a lot of overhead and I had a problem as it caused spin ups of new containers. It's 4x the usual comsuption within startup, so... it always spin up new containers on startup.

Also, let me know how can I contribute. I would like to send a PR to improve EF DbContext registration, since I'm using a custom one and I can't use your provided extensions. I'm using AddDbContextPool + some custom replaced services.

Keep up the good work! 

![image](https://github.com/JasperFx/wolverine/assets/12385152/be9ea889-b142-4263-a924-f7523aa17a66)

**Comment by jeremydmiller** [comment]
@smartcodinghub Try this first to improve that cold start resource usage: https://wolverine.netlify.app/guide/codegen.html#optimized-workflow. But to make that work, you'll need to check in the pre-generated code so that it's built into your assemblies when you deploy.

**Comment by smartcodinghub** [comment]
It seems to be working! Any chance to have a dotnet tool to take care of compilation + this? or custom targets?

Anyway, is there a way to truly verify its working?

**Comment by jeremydmiller** [comment]
@smartcodinghub Why yes:)

`dotnet run -- codegen write` from your Wolverine app.
