### ISSUE TITLE
Wrong order message in DurableOutbox

### ISSUE THREAD

**Issue by aliseyedali** [JasperFx/wolverine#436]
Wolverine Version 1.
First and foremost, thank you for all the effort you've put into this project. It's truly impressive.

I'm currently experiencing some issues with the UseDurableOutbox functionality. Here's a brief explanation of the problem:

Whenever I receive a chronological event from my event handler, I immediately publish a corresponding message. However, when I incorporate the DurableOutbox feature, I notice that Wolverine is enqueueing my messages in the incorrect order. For instance, if I publish four or five messages, the third one gets placed at the front of the queue instead of its original order.
`
private async Task OnMessageReceivedAsync(OrderedEvent e)
    {
        await _bus.PublishAsync(e);
    }
`
Could you please assist me in resolving this matter? I greatly appreciate your help. 
@jeremydmiller

**Comment by jeremydmiller** [comment]
Hey all, I think I'm going to have to push this off until a 1.2 release as it'll likely have additional database fields. But I'll commit to this finally being addressed by the end of this week.

**Comment by jeremydmiller** [comment]
@aliseyedali I'm going to need more information from you about how to reproduce this. From a simple test today, it worked and all the messages were received in order.

**Comment by aliseyedali** [comment]
> @aliseyedali I'm going to need more information from you about how to reproduce this. From a simple test today, it worked and all the messages were received in order.

@jeremydmiller 
this is my configuration:

`
hostBuilder.UseWolverine((context, opts) =>
            {
                opts.UseSystemTextJsonForSerialization();

                opts.Services.AddMarten(opts =>
                {
                    opts.UseDefaultSerialization(serializerType: SerializerType.SystemTextJson);
                    opts.Connection(connectionString);
                    opts.DatabaseSchemaName = "machine";

                }).UseLightweightSessions()
                .IntegrateWithWolverine()
                .ApplyAllDatabaseChangesOnStartup();

                var options = machineOptions.MachineClinetOptions.Single();

                opts.ListenAtPort(options.ListenAtPort).Sequential();

                opts.PublishAllMessages()
                .ToServerAndPort(options.HostName, options.ToPort)
                .UseDurableOutbox();

            }).UseResourceSetupOnStartup()
            .ConfigureExtensionService(configurationSection: "Extensions")
            .ConfigureServices((context, services) =>
                {
                    services.Configure<MachineOptions>(context.Configuration.GetSection("MachineOptions"));
                    services.AddHostedService<WorkerService>();
                });
`
and in WorkerService:

`private async Task OnMessageReceived(OrderedEvent e)
    {
        _logger.LogDebug("Received event: " + e.GetType().Name + $" ({e.OrderId}) - {e.Id}");
        try
        {
            await _bus.PublishAsync(@event);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "unhandle exception in OnMessageReceived");
        }
    }
`
I also got a similar result using Rabbitmq

**Comment by jeremydmiller** [comment]
Moving under #722
