### ISSUE TITLE
multiple services for event type

### ISSUE THREAD

**Issue by denis-troller** [JasperFx/wolverine#443]
Maybe I am a little slow, but it seems that I cannot get two services to listen to the same event simply.

If I declare a handler for the same type of mesage in two different apps and use conventional routing on both, the both pull messages from the queue for that type, competing for the messages (only one service will get each message).

How do you configure wolverine so that each service gets its own queue for that message type ?
This is automatic in MassTransit and I am surprised I cannot find the way to do it in Wolverine apart from manually creating a queue and binding it to the exchange for that message type, which seems like a lot of work if I have multiple message types.

What am I missing ?

**Comment by jeremydmiller** [comment]
That's not something I'd ever thought of, or used in MassTransit quite like that. Try something like this:

```csharp
    opts.UseRabbitMq().AutoProvision()
        .UseConventionalRouting(c =>
        {
            // Just stick a prefix on front of the queue names
            c.QueueNameForListener(t => "service1." + t.FullName);
        });
```

You'll have to do something about the binding from exchange to queue name though.

Hey, in the future, can you ask questions on Discord instead of GitHub? --> https://discord.gg/xqym37VMZM
