### ISSUE TITLE
Flesh out the best practices documentation

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#445]
Absolutely most include a decision tree about how to deal with HTTP handlers too

**Comment by pekkah** [comment]
As there are so many options for customization, it would be nice to have production ready examples for each transport and storage and notes on how you would change things for development time. Even after browsing the documentation, it's still a bit unclear to me what options to set and why and when to lean on the defaults. Have used NServiceBus before on large systems.
