### ISSUE TITLE
Wolverine writes FailureAcknowledgement to System.Byte[] queue when handing message with NServiceBus interop

### ISSUE THREAD

**Issue by mfuqua3** [JasperFx/wolverine#449]
I have not been able to fully nail down the root cause of this one, so these repro steps are somewhat speculative.

Environment: `WolverineFx.RabbitMQ v1.0.0`

Suspected Reproduction Steps:

Listen to a RabbitQueue using NServiceBusInterop:

```csharp
wolverineOptions.ListenToRabbitQueue(localQueue)
            .CustomizeDeadLetterQueueing(x =>
            {
                x.QueueName = localQueue + ".error";
                x.Mode = DeadLetterQueueMode.InteropFriendly;
            })
            .UseNServiceBusInterop();
```

Send a message to this queue from NServiceBus. Note first screenshot with expected NServiceBus fields. Note the reply-uri from the first screenshot (does not match NServiceBus.ReplyToAddress)

Throw an exception during message execution, observe that Wolverine failure gets sent to the reply-uri, in this case System.Byte[].

Third screenshot may be related (or maybe different bug), I suspect that Wolverine is attempting to read off this System.Byte[] queue with NServiceBus interop but is failing due to lack of expected headers.

![image](https://github.com/JasperFx/wolverine/assets/28541406/cd2ba521-7da1-41ab-bd75-e3ab208d3a3f)

![image](https://github.com/JasperFx/wolverine/assets/28541406/1228255e-cb18-476c-b942-1998691d561c)

![image](https://github.com/JasperFx/wolverine/assets/28541406/7243110d-834b-4a33-b212-766c46fc3296)

**Comment by mfuqua3** [comment]
Unrelated, this `CustomizeDeadLetterQueueing` overload is not part of the Wolverine SDK, but is an extension. So the code snippet won't work out of the box.

```csharp
public static class RabbitMqConfigurationExtensions
{
    public static RabbitMqTransportExpression CustomizeDeadLetterQueueing(this RabbitMqTransportExpression expression,
        Action<DeadLetterQueue> configureQueue)
    {
        var deadLetterQueue = new DefaultDeadLetterQueue();
        configureQueue(deadLetterQueue);
        expression.CustomizeDeadLetterQueueing(deadLetterQueue);
        return expression;
    }

    public static RabbitMqListenerConfiguration CustomizeDeadLetterQueueing(
        this RabbitMqListenerConfiguration expression,
        Action<DeadLetterQueue> configureQueue)
    {
        var deadLetterQueue = new DefaultDeadLetterQueue();
        configureQueue(deadLetterQueue);
        expression.DeadLetterQueueing(deadLetterQueue);
        return expression;
    }
    private sealed class DefaultDeadLetterQueue : DeadLetterQueue
    {
        private const string DefaultQueueName = "wolverine-dead-letter-queue";

        public DefaultDeadLetterQueue():base(DefaultQueueName)
        {
            
        }
    }
}
```

**Comment by ThickPropheT** [comment]
The `The given key 'NServiceBus.ReplyToAddress' was not present in the dictionary` part is actually a problem in and of itself.

[Wolverine makes the assumption](https://github.com/JasperFx/wolverine/blob/da796ad1a224b72a174db8702db0cf6940b8c85b/src/Transports/RabbitMQ/Wolverine.RabbitMQ/Internal/RabbitMqEndpoint.NServiceBus.cs#L30) that all NSB messages will include the 'NServiceBus.ReplyToAddress' header, but apparently they don't always.

**Comment by ThickPropheT** [comment]
Also note that the header values are byte arrays [here](https://github.com/JasperFx/wolverine/blob/da796ad1a224b72a174db8702db0cf6940b8c85b/src/Transports/RabbitMQ/Wolverine.RabbitMQ/Internal/RabbitMqEndpoint.NServiceBus.cs#L30) instead of strings:

![image](https://github.com/JasperFx/wolverine/assets/6137018/1777e821-e396-4b3f-a7c1-57eeb87ad7e1)

So when you do this:

`e.ReplyUri = new Uri($"rabbitmq://queue/{queueName}");`

your uri ends up being `rabbitmq://queue/System.Byte[]` rather than the value of the ReplyToAddress header.

**Comment by jeremydmiller** [comment]
Hey guys, what version of NServiceBus are y'all using there? 

And as I said on Discord, I'm on a short family vacation until after the 4th. I can pick this up Wednesday morning though.

The reply uri will be quick. Dealing w/ the byte[] instead of strings as well.

**Comment by jeremydmiller** [comment]
Meh, the "NServiceBus.ReplyToAddress" had special, hard coded handling, and that's why it bombed on that one.
