### ISSUE TITLE
TransactionalFrame is internal?

### ISSUE THREAD

**Issue by rosdi** [JasperFx/wolverine#453]
I am following this documentation: https://wolverine.netlify.app/guide/durability/marten/#snippet-sample_commandsaretransactional

Am I correct to assume this documentation is outdated since TransactionalFrame is internal?

https://github.com/JasperFx/wolverine/blob/da796ad1a224b72a174db8702db0cf6940b8c85b/src/Persistence/PersistenceTests/Marten/transactional_frame_end_to_end.cs#L94

**Comment by jeremydmiller** [comment]
That's just sample code to show you how to write middleware policies, and the test project has access to Wolverine's internals. Nothing in the docs of that page are outdated.

Would you mind asking questions in the Discord channels instead of GitHub issues?
