### ISSUE TITLE
Incorrect order of messages with durable outbox

### ISSUE THREAD

**Issue by arbellaio** [JasperFx/wolverine#457]
Hello All, 

I've encountered an issue with the DurableOutbox feature in my event handling system. Whenever I receive events in chronological order and publish corresponding messages, I've noticed that Wolverine, the message enqueueing component, places the messages incorrectly in the queue. For example, when I publish five messages, the third message is moved to the front of the queue instead of maintaining its original order.

Please guide how to modify the code to ensure the correct order of message publishing while using the DurableOutbox.

**Comment by jeremydmiller** [comment]
Try setting the execution of the listeners to `Sequential` like this:

https://github.com/JasperFx/wolverine/blob/ab3ac2457cb7cff1a20e239ec897ea45a9dcb278/src/Samples/DocumentationSamples/EnqueueSamples.cs#L30

**Comment by arbellaio** [comment]
Hi, Jeremy appreciate you getting back to me, but I am having this issue when I am publishing messages, and this sequential method is for listener as I understand.

**Comment by aliseyedali** [comment]
> Hi, Jeremy appreciate you getting back to me, but I am having this issue when I am publishing messages, and this sequential method is for listener as I understand.

#436 
I also have this issue.

**Comment by jeremydmiller** [comment]
Hey @arbellaio, same thing. I'm going to need more information about your setup & configuration to reproduce this. Publishing today through a rabbit mq queue with multiple messages, everything using durable inbox/outbox, and I received all messages in order as expected.

**Comment by jeremydmiller** [comment]
Moving under #722
