### ISSUE TITLE
ASP.Net Core Integration - Endpoints documentation - unfinished info section

### ISSUE THREAD

**Issue by nicholas-brooks** [JasperFx/wolverine#462]
Under "Legal Endpoint Signatures" section, the sentence doesn't finish.

https://github.com/JasperFx/wolverine/blob/9fbd5edd68fb98d4810ecee38e678fe73a7c19c7/docs/guide/http/endpoints.md?plain=1#L55

I'm unsure what it's trying to say.

**Comment by jeremydmiller** [comment]
Thanks for the heads up, I'll check it out.
