### ISSUE TITLE
Swashbuckle does not see route parameters in Wolverine HTTP method attributes

### ISSUE THREAD

**Issue by lofbacke** [JasperFx/wolverine#467]
When using route parameters in my Wolverine HTTP method attributes, Swashbuckle cannot see them.

Example:
```cs
public static class GetUserProfileEndpoint
{
    [Authorize]
    [WolverineGet($"{Routes.Users}/{{userId}}")]
    public static async Task<UserProfile?> GetUserProfile(Guid userId, IQuerySession session)
    {
        // query logic omitted for brevity
        return userProfile;
    }
}
```

Although Swashbuckle can see the endpoint itself, the `userId` parameter is not listed.
![image](https://github.com/JasperFx/wolverine/assets/52764594/2edac9cf-2581-4029-a876-ed193a7ba8ef)

If I hit the endpoint with a `userId` value, Wolverine does successfully pick it up. Additionally, the `[FromRoute]` attribute allows Swashbuckle to correctly identify the parameter, as does moving the endpoint into a minimal API.

**Comment by Xzelsius** [comment]
If you specify `[FromRoute]` on the `userId `it does work, although you don't need it for Wolverine to work.

**Comment by Xzelsius** [comment]
Related !446

**Comment by jeremydmiller** [comment]
Folks, this worked OOTB with the current Wolverine main folder today. Not really sure what's changed.

**Comment by jeremydmiller** [comment]
I'm still adding a second layer of `IFromRouteMetadata` though
