### ISSUE TITLE
Integration test not able to track all messages

### ISSUE THREAD

**Issue by mirinkinen** [JasperFx/wolverine#468]
There is a problem with tracking messages that are sent from ASP.NET Core middleware after controller logic. The issue is reproduced in [this simple app](https://github.com/mirinkinen/wolverine-tracking-problem).

The app has a `MessageMiddleware` that sends the `BeforeMessage` before the controller and `AfterMessage` after the controller. In between, the controller sends it own message of type `ControllerMesssage`.

The `all_messages_are_tracked` test tries to track these messages. The tracking works when controller returns plain `Ok()` but does not work when controller returns any kind of object, even a simple string.

**Comment by jeremydmiller** [comment]
@mirinkinen I stumbled into this myself today while working on something completely different. The tracking was always used before on a single triggering message. In your case -- and mine -- it's able to think it's complete and trigger the task completion **during** the actions in the ExecuteAndWaitAsync(). I'm fixing this today to latch that. Easy money once and only once I saw a reproduction.
