### ISSUE TITLE
Bug: FluentValidation is not picked up when running in a different assembly

### ISSUE THREAD

**Issue by Richard87** [JasperFx/wolverine#478]
I made a small test project here:
https://github.com/Richard87/WolverineTestFluentValidation

When using the HelloEndpoint in the main Program.cs file, validation works as expected, but when loading the class from the ClassLibrary, its not picked up...

**Comment by jeremydmiller** [comment]
@Richard87 Meh, it's an ordering issue. If you reorder things in `Program` to

```csharp
    opts.Discovery.IncludeAssembly(typeof(CreateCustomer2).Assembly);
    opts.UseFluentValidation();
```

it's all good. 

I'm not up for messing w/ this much more tonight, but tomorrow I'll make the registration lazy so that it's not evaluated until after the UseWolverine() call.

**Comment by Richard87** [comment]
Thanks for looking in to it! 🙏
