### ISSUE TITLE
Can't use nested types as middleware

### ISSUE THREAD

**Issue by BrianVallelunga** [JasperFx/wolverine#481]
I'm testing Wolverine with an F# application. In F#, classes get nested by default inside of modules (which are classes). Trying to create a middleware with the following code fails:

```f#
type public TenantMiddleware() =
    member self.Before (bus: IMessageBus) =
        bus.TenantId <- "Test"
        ()
```

The reason it fails is the check for `IsPublic` on this line:
https://github.com/JasperFx/wolverine/blob/83dc7bc109409d945a75a906f73ced7fa098407b/src/Wolverine/Middleware/MiddlewarePolicy.cs#L89-L92

`IsPublic`  only returns true for public, non-nested types. Changing this to `IsVisible` allows public, nested types. See: https://learn.microsoft.com/en-us/dotnet/api/system.type.isvisible and https://learn.microsoft.com/en-us/dotnet/api/system.type.ispublic

I tested this and can confirm that changing this solves the F# issue I'm experiencing. I'm happy to submit a 7-letter pull request!

**Comment by jeremydmiller** [comment]
@BrianVallelunga I'll push this through for 1.2.1 tomorrow. You already did most of the leg work, and I'll add a test to nail it down permanently. I know I've had to fix this exact same issue on some other OSS project. Thank you for your help!
