### ISSUE TITLE
MapWolverineEndpoints authorization?

### ISSUE THREAD

**Issue by BrianVallelunga** [JasperFx/wolverine#495]
I'm trying to figure out how to enable authorization for all Wolverine endpoints using the HTTP features. I have successfully applied the `[Authorize]` attribute to an endpoint, but I'd like to apply it globally. I can add an authorization policy, but I'm not sure how to get it applied to the Wolverine endpoints. Any thoughts?

I think I'm looking for the equivalent to MVC's:

```
app.UseEndpoints(endpoints =>
{
    // Require Authorization for all your Controllers
    endpoints.MapControllers().RequireAuthorization();
});
```

**Comment by jeremydmiller** [comment]
You could use an `IHttpPolicy` that news up and adds `AuthorizationAttribute` to each chain. It'd be a relatively quick PR, but I'm already working up a 1.3 release today anyway. Want me to add a pre-built, opt in policy for this?

It'll be something like `MapWolverineEndpoints(opts => opts.Policies.RequireAuthorization())`;

**Comment by BrianVallelunga** [comment]
I feel like it is a common enough feature that it should probably exist, especially since there's parity in the existing MVC and endpoint routing of ASP.NET.

**Comment by jeremydmiller** [comment]
Actually, temporarily, can you use:

```csharp
app.MapWolverineEndpoints(opts =>
{
    // This is strictly to test the endpoint policy
    
    opts.ConfigureEndpoints(chain =>
    {
        chain.Metadata.RequireAuthorization();
    });
```

I'm just out of time for the day and need to kick out Wolverine 1.3. But totally agree with you here.

**Comment by jeremydmiller** [comment]
Or actually, this would work:

```csharp
app.MapWolverineEndpoints(opts =>
{
    // This is strictly to test the endpoint policy
    
    opts.ConfigureEndpoints(chain =>
    {
        chain.RequireAuthorization();
    });
```

**Comment by BrianVallelunga** [comment]
That would also be fine. Sorry I don't have a strong opinion about this! Thanks for the help though.

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/wolverine/commit/c46285135c9d18c8d4d4fd2547417adda3904bca
