### ISSUE TITLE
AmazonSqs disabling DeadLetterQueue still makes it default to "AmazonSqsTransport.DeadLetterQueueName"

### ISSUE THREAD

**Issue by maxaki** [JasperFx/wolverine#521]
Not sure if it's an issue or not but here's more detail
Setup: <https://i.maxaki.com/GmpHD3whux2k9mpkbuen.png>
Debug: <https://i.maxaki.com/u2SsoMt5obgcOXDhZ5aT.png>
Output: <https://i.maxaki.com/woFCOoXOwkYBcHSs7POM.png>
The dead letter queue appears to never be empty even though it's been disabled

**Comment by jeremydmiller** [comment]
I'm shutting this down.
