### ISSUE TITLE
[NotBody] Not respected by Swashbuckle When using a Parameter for LoadAsync result

### ISSUE THREAD

**Issue by JoshuaNitschke** [JasperFx/wolverine#528]
I was going through the `LoadAsync` example and noticed that `[NotBody]` is not being respected by Swashbuckle creating an unusable entry on the swagger page.  The endpoint performs as expected (verified using postman) so this is more cosmetic but renders the swagger page a bit useless for communicating how to work with the API if you want to use this feature.

Steps to reproduce

1) Add an endpoint like so:
```
public class GetProfileEndpoint
{
    [WolverineGet("/profiles/{userId}")]
    public Profile GetProfile([FromRoute]Guid userId, [NotBody][Required] Profile profile, HttpContext context, IDocumentSession session)
    {
        return profile;
    }
}
```

**RESULT**
Swagger will not let you execute the endpoint because it wants a body, but there is also no input field to provide one either (see screenshot below)

<img width="1382" alt="image" src="https://github.com/JasperFx/wolverine/assets/33307206/b0327133-d06d-4f11-93d7-bb55ef2a2512">

**EXPECTED RESULT**
Swagger should render as it does with this code:
```
public class GetProfileEndpoint
{
    [WolverineGet("/profiles/{userId}")]
    public Task<Profile?> GetProfile([FromRoute]Guid userId, HttpContext context, IDocumentSession session)
    {
        return session.LoadAsync<Profile>(userId);;
    }
}
```
<img width="1105" alt="image" src="https://github.com/JasperFx/wolverine/assets/33307206/8b0b183a-9991-477b-af0c-9ad32f38b3d6">

**Comment by alistair** [comment]
@JoshuaNitschke Could you try adding [BindNever] to your Profile parameter?

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.bindneverattribute?view=aspnetcore-7.0

From the swagger code

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L308-L321

**Comment by alistair** [comment]
Mmmmm....  doesn't seem to work

**Comment by alistair** [comment]
Ok I think I got the output that you expect.

```
public class SwaggerRemoveNotBodyParameterFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        context.ApiDescription.ParameterDescriptions
            .Where(pd => ((Microsoft.AspNetCore.Mvc.Infrastructure.IParameterInfoParameterDescriptor)pd.ParameterDescriptor).ParameterInfo.CustomAttributes.Any(x => x.AttributeType == typeof(NotBodyAttribute)))
            .ToList()
            .ForEach(
                pd =>
                {
                    if (operation.Parameters != null)
                    {
                       // These first to lines don't do anything as the operation doesn't contain the Parameter
                       // But the ApiDescription does so removing it from there means nothing is displayed.
                        var notBodyParameter = operation.Parameters.SingleOrDefault(p => p.Name == pd.Name);
                        operation?.Parameters?.Remove(notBodyParameter);
                        context.ApiDescription.ParameterDescriptions.Remove(pd);
                    }
                });
    }
}
```

**Comment by alistair** [comment]
Sorry going to use this to dump some stuff in here so I can remember it.

https://github.com/dotnet/aspnetcore/blob/b0b9f45538383bdf036bd35a84c6552d37bd6010/src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs
