### ISSUE TITLE
Injected service and IMessageBus seem to differ in scope

### ISSUE THREAD

**Issue by BrianVallelunga** [JasperFx/wolverine#533]
I don't seem to be able to access the same IMessageBus as the handler when instantiating a service in my DI container. I'm trying to do this to create tenant-aware services that don't require passing around a tenant id manually on every method call.

Given this service:

```c#
public class Service : IService
{
    public string TenantId {get; set;}
}
```

Registered like this:

```c#
services.AddScoped<IService>(s => {
    var bus = s.GetRequiredService<IMessageBus>();
    return new Service { TenantId = bus.TenantId };
});
```

Being injected into this:

```c#
public Task Handle(Message message, IMessageBus bus, IService service)
{
      // bus.TenantId is populated properly
      // service.TenantId is null
}
```

This code being run in a background worker, not in an HTTP pipeline. The real code is obviously more complex with more than a string that gets set. Is this roughly the same issue as https://github.com/JasperFx/wolverine/issues/501 or https://github.com/JasperFx/wolverine/issues/360 ? If so, any ideas for a workaround?

Thanks! I'm really like Wolverine thus far.

**Comment by jeremydmiller** [comment]
@BrianVallelunga I'm going to add this to the docs to "don't do that"

I'll look at the exact resolution, but can you get rid of the Lambda usage here? Even if we can fix the code generation, I would very strongly recommend using `IMessageBus` within a lambda like this (and honestly recommend against doing things like that except in rare exception cases as a 20 year IoC author):

```csharp
services.AddScoped<IService>(s => {
    var bus = s.GetRequiredService<IMessageBus>();
    return new Service { TenantId = bus.TenantId };
});
```

Wolverine is trying very hard to **not** use the IoC container at runtime. Having a lambda registration that's scoped or transient defeats that and forces Wolverine back to using a nested container. Which is fine, except that Wolverine itself creates the actual object of the `IMessageContext / IMessageBus` that you see used in the handler.

We **can** beat this by having the current IMessageBus/IMessageContext injected into the nested container to make your scenario work, but I'd still recommend against that.
will never work with

**Comment by BrianVallelunga** [comment]
I can inject an `IServiceFactory` into my handler with a `Build(string tenantId)` method on it. Due to other architecture choices, I'd only need one of these per tenant-aware handler, so perhaps that is a better choice. The `IServiceFactory` wouldn't need the lambda registration itself.

**Comment by jeremydmiller** [comment]
I honestly don't even want to try to address this other than as a documentation issue.

**Comment by BrianVallelunga** [comment]
All good, thanks! Creating a factory seems to have solved the issue for me.
