### ISSUE TITLE
Handlers classname ending with a number cannot be discovered

### ISSUE THREAD

**Issue by timdeschryver** [JasperFx/wolverine#540]
It seems like handlers that are within classes that end with a number are not discovered.
Invoking the bus ends with an the following error message:

```
Wolverine.Runtime.Routing.IndeterminateRoutesException
Could not determine any valid subscribers or local handlers for message type CoreTests.Compilation.FixtureMessage
```

This only happens when the classname ends with a number, classes containing a number are working fine.

For a reproduction see 👇

https://github.com/JasperFx/wolverine/compare/main...timdeschryver:reproduction/handler-with-number-in-class-name?expand=1

**Comment by jeremydmiller** [comment]
@timdeschryver Yeah, that's just not supported. The docs do spell that out that the discovery works on the "Handler" or "Consumer" suffix. You *can* use the `IWolverineHandler` marker interface or `[WolverineHandler]` attribute if you want to vary from the naming convention.

I don't think I want to change this behavior to be honest, so I'm going to close this.

**Comment by timdeschryver** [comment]
🤦 My bad, thanks for pointing that out!
I only read through the tutorials and I was just trying some things out, hence this issue.
