### ISSUE TITLE
NodaTime.Instant fails to serialize to JSON properly despite configuring Nodatime Serializer

### ISSUE THREAD

**Issue by JoshuaNitschke** [JasperFx/wolverine#543]
I tried to configure the JSON serializer several different ways as you can see in the example repo, but I couldn't find a method / order that would serialize JSON responses as expected.

**STEPS TO REPRODUCE**
1) Pull this branch: https://github.com/JoshuaNitschke/wolverine-issue-reproduction/tree/nodatime-issue
2) Run the unit test

**RESULT**
<img width="885" alt="image" src="https://github.com/JasperFx/wolverine/assets/33307206/818f4bd5-27b6-4300-89cd-25ebbc9763ec">

**EXPECTED RESULT**
Instant to serialize in ISO-8601 pattern e.g. 2023-09-11T23:35:41.101553Z

**OTHER RESOURCES**
@alistair made this: https://github.com/alistair/wolverine/tree/configure_json_serializer
Discord report: https://discord.com/channels/1074998995086225460/1150925861458030655
Possibly related Marten issue: https://github.com/JasperFx/marten/issues/2613

**Comment by alistair** [comment]
Hey @JoshuaNitschke 

There are actually 2 JsonOptions which exist.  My belief is that you are configuring the Mvc version but not the Microsoft.AspNetCore.Http.Json.JsonOptions version which is what wolverine actually depends on.

See https://github.com/dotnet/aspnetcore/issues/35904 for more detail

**Comment by JoshuaNitschke** [comment]
@alistair I don't think so - did you pull the repo?
<img width="479" alt="image" src="https://github.com/JasperFx/wolverine/assets/33307206/5c9e15c1-b52a-4f04-8c2f-b2f620a43116">

**Comment by alistair** [comment]
Yeah I did but actually replicated it slightly differently.   Just finished cleaning up my branch and created this above PR so that wolverine captures the IOption<> over referencing the JsonOption directly.

**Comment by JoshuaNitschke** [comment]
@alistair  thank you sir!!!

**Comment by jeremydmiller** [comment]
This is resolved by @alistair 's fix here: https://github.com/JasperFx/wolverine/pull/544
