### ISSUE TITLE
Using the correct architecture

### ISSUE THREAD

**Issue by ploef** [JasperFx/wolverine#551]
Hi,
I'm unsure about the correct architecture when using a saga (state machine). If I have an entity whose state I want to capture, should the saga contain all the properties of that entity or just an id and the state? And then store the entity itself separately in its entirety.

Kind regards, 
Peter

**Comment by jeremydmiller** [comment]
@ploef If you can, please use Discord (https://discord.gg/xqym37VMZM) for questions and keep GitHub issues for bugs or the back log. Thank you.

A saga is just a temporary workflow. If the entity data is permanent, I think I'd just opt to reference the primary key of the entity in the saga and look up the entity later. Unless you have performance concerns about the extra data lookup that is.

**Comment by ploef** [comment]
Hi, that's the road I took now. Thanks for the backup. 😄 
And I will start using discord from now on.
