### ISSUE TITLE
Setting JsonSerializingOptions for endpoints

### ISSUE THREAD

**Issue by ploef** [JasperFx/wolverine#552]
Hi,

Using standard controllers I was able to configure the handling of enums like this:

``
builder.Services.AddControllers()
        .AddJsonOptions(x =>
        {
            x.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
        });

How can I do that with: MapWolverineEndpoints?

**Comment by jeremydmiller** [comment]
The exact same way you would for Minimal API. That's meant to be documented here: https://wolverine.netlify.app/guide/http/endpoints.html#json-handling

I'll add a code sample to the docs in a bit, but close this when that's done. 

```csharp
var builder = WebApplication.CreateBuilder(args);

// Set the JSON serializer options
builder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options =>
{
    options.SerializerOptions.PropertyNameCaseInsensitive = false;
    options.SerializerOptions.PropertyNamingPolicy = null;
    options.SerializerOptions.WriteIndented = true;
});

var app = builder.Build();
app.MapGet("/", () => new { FirstName = "Gérald", LastName = "Barré" });
app.Run();
```

See https://www.meziantou.net/configuring-json-options-in-asp-net-core.htm. Watch the namespace. Might also add a helper method for this to Wolverine.HTTP 'cause it's biting people.

**Comment by ploef** [comment]
Hi Jeremy, thanks for the quick response. It's already getting better except for parsing a enumeration value. This is working using the "old" controller setup but it seems that the minimal API has an issue with it.

Using this configuration:

```cs
builder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options =>
{
    options.SerializerOptions.PropertyNameCaseInsensitive = false;
    options.SerializerOptions.PropertyNamingPolicy = null;
    options.SerializerOptions.WriteIndented = true;
    options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
});
```

outputs this error:
```cs
System.Text.Json.JsonException: The JSON value could not be converted to Wur.Mip.Hub.Commands.ReportingLanguageType. Path: $.sample.reportingLanguage
```

The enum looks like this:

```cs
public enum ReportingLanguageType
{
    nl,
    en
}
```

and finally this is part of the json:

```json
{
  "sample" :
  {
    "id" : "333",
    "matrixType" : "Spuitvloeistof",
    "matrixDescription" : "Spuitvloeistof",
    "intakeDate" : "2020-07-20",
    "remark": "concateneringstest",
    "reportingLanguage" : "nl",
    "casing" : "Plastic",
    "sealType" : "Secubag",
```
