### ISSUE TITLE
Compilation Failures: context confusion

### ISSUE THREAD

**Issue by pettys** [JasperFx/wolverine#563]
Here are the details of the unexpected error. The error can be reproduced with the code at the end of this report. I believe the generated code should be using `context` where it uses `context1` and `context2`. @jeremydmiller suggested, "One way or another, Wolverine is getting confused by the usage of multiple arguments, parameters, or types named 'context'. Moreover, it's the very code that Wolverine uses to disambiguate that that's messing you up."

```
InvalidOperationException: Compilation failures!

CS0103: The name 'context1' does not exist in the current context
CS0103: The name 'context2' does not exist in the current context

Code:
[irrelevant bits snipped]

namespace Internal.Generated.WolverineHandlers
{
   public class MyMessageHandler1907647795 : Wolverine.Runtime.Handlers.MessageHandler
   {

      public override System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
      {
         var myMessageHandler = new MyMessageHandler();
         var myService1 = new MyService1(context1);
         var myService2 = new MyService2(myService1, context2);
         // The actual message body
         var myMessage = (MyMessage)context.Envelope.Message;

         // The actual message execution
         myMessageHandler.Handle(myMessage, myService2);

         return System.Threading.Tasks.Task.CompletedTask;
      }
   }
}
```

Here is what I was able to boil down as a minimal repro code. I believe you can repro:
1. Use .NET Core 7 (did not test on 6)
2. `dotnet new webapi`
3. `dotnet add package WolverineFx`
4. Replace `Program.cs` with the code below
5. Run the app with a web browser pointed at `/`
6. Expected Output: "ok" in web browser
7. Actual Result: a page with the error details as above.
8. **Workaround**: in the below code, change `MyService2(MyService1 svc1, IMessageBus bus)` to `MyService2(MyService1 svc1, IMessage**Context** bus)` and the problem goes away.

```
using Wolverine;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddScoped<MyService1>();
builder.Services.AddScoped<MyService2>();
builder.Host.UseWolverine();

var app = builder.Build();

app.MapGet("/", async (IMessageBus bus) => {
	await bus.PublishAsync(new MyMessage());
	return Results.Ok("ok!");
});

app.Run();

public class MyService1 {
	public MyService1(IMessageContext arg) { }
}

public class MyService2 {
	public MyService2(MyService1 svc1, IMessageBus bus) { }
}

public record MyMessage();

public class MyMessageHandler {
	public void Handle(MyMessage command, MyService2 service2) { }
}
```

**Comment by jeremydmiller** [comment]
Got it, easy money, thanks for the reproduction code. Fix in 1.7.1 in a bit.

Hey, if you use Wolverine.HTTP, see the bottom of this section:  https://wolverine.netlify.app/guide/http/mediator.html

And I'd actually recommend against trying to inject IMessageBus into your own services. I'd try hard to keep message publishing in the root handler method if you can. Maybe even using cascading messages.
