### ISSUE TITLE
Compiler: disposing too soon

### ISSUE THREAD

**Issue by pettys** [JasperFx/wolverine#564]
Without middleware, but with a dependency that implements IDisposable, the code generated does not await the handler which may (and most often will) dispose the dependency before the handler completes.

Example code generated:

```
public override System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
{
  var timesheetNotificationHandler = new X.TimesheetNotificationHandler();
  using var sqlSession = new X.SqlSession(_sqlConfig);
  var timesheetSubmittedEvent = (X.TimesheetSubmittedEvent)context.Envelope.Message;            
  return timesheetNotificationHandler.Handle(timesheetSubmittedEvent, sqlSession);
}
```

In this case `sqlSession` will be disposed before `Handle` completes, except in trivial cases.

**Workaround:**
Adding this middleware appears to get the compiler to await the Handle method:
```
public class WorkAroundCrazyWolverineIssueTillResolvedMiddleware {
	public Task After() => Task.CompletedTask;
}
```

**Side bug:**
I tried a FInally() in the middleware first and Wolverine generated code that didn't compile for that, too:
```
CS0157: Control cannot leave the body of a finally clause
...
try
{
   return Tmly.Notifications.Types.NotifyApproverOfSubmittedTimeHandler.Handle(notifyApproverOfSubmittedTime, userRepository, timesheetRepository, broadcaster);
}
finally
{
   return workAroundCrazyWolverineIssueTillResolvedMiddleware.Finally();
}
```

**Comment by jeremydmiller** [comment]
@pettys What version of Wolverine were you using? I just looked into the code, and it should already be forcing it into using the `await` syntax.

**Comment by pettys** [comment]
@jeremydmiller 1.7.0. I'll test with 1.7.1 & if still reproducible I'll try to create a failing unit test.
