### ISSUE TITLE
New HTTP multi-tenant support not setting TenantId on IMessageContext

### ISSUE THREAD

**Issue by BrianVallelunga** [JasperFx/wolverine#569]
I was removing my custom middleware that set the `TenantId` property to use the new built-in support and seem to have come across a bug (using 1.7.1).

My HTTP endpoints are configured with: `opts.TenantId.IsRequestHeaderValue("Tenant")`

✅ If my HTTP handler signature is `HandleGet(IMessageBus bus)` then `bus.TenantId` is set properly.

✅If the signature is `HandleGet(IMessageContext messageContext, IMessageBus bus)` then both `bus.TenantId` and `messageContext.TenantId` are set properly.

❌ If my HTTP handler signature is just `HandleGet(IMessageContext messageContext)` then `messageContext.TenantId` is `NULL`.

It seems that to be set properly, `IMessageBus` must be a parameter, not just `IMessageContext`. I'm assuming this isn't by design, but wanted to report it since there are several cases where I only need `IMessageContext`.

**Comment by jeremydmiller** [comment]
Ugh. Okay.

Why are you having to inject the IMessageBus as a parameter btw?

**Comment by BrianVallelunga** [comment]
After updating to 1.7.1 and trying the new code, I noticed some endpoints were working (IBus), and others were broken (IMessageContext).

I only injected them both in a single handler to see if the values were different between the two. That's when I discovered the odd behavior.
