### ISSUE TITLE
Custom System.Text.Json configuration not being picked up by Wolverine.Http

### ISSUE THREAD

**Issue by nkosi23** [JasperFx/wolverine#573]
Just to give this bug a dedicated issue since it got lost [at the end of the one](https://github.com/JasperFx/wolverine/issues/508) dedicated to UseNewtonsoftForSerialization. 

I have tried configuring an Fsharp friendly serializer for STJ (provided by the nuget package FSharp.SystemTextJson) but it doesn't seem to be picked up by Wolverine:

```csharp
builder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options =>
{
    var jsonFsharpOptions = new JsonFSharpOptions(includeRecordProperties: true);
    jsonFsharpOptions.AddToJsonSerializerOptions(options.SerializerOptions);
});

// Wolverine usage is required for WolverineFx.Http
builder.Host.UseWolverine(opts =>
{
    // This middleware will apply to the HTTP
    // endpoints as well
    opts.Policies.AutoApplyTransactions();

    // Setting up the outbox on all locally handled
    // background tasks
    opts.Policies.UseDurableLocalQueues();
    opts.UseSystemTextJsonForSerialization(stj =>
    {
        // JsonFSharpOptions.Default()
        // .AddToJsonSerializerOptions(stj);
        var jsonFsharpOptions = new JsonFSharpOptions(includeRecordProperties: true);
        jsonFsharpOptions.AddToJsonSerializerOptions(stj);
    });
});
```

From what I understand, the second block shouldn't even be necessary since Wolverine.Http is supposed to pick up whatever has been configured in ASP.NET Core minimal API. Either way, it doesn't work: the custom configuration is not used by Wolverine.Http to serialize the response of requests.

These serialization issues have been preventing me from using Wolverine and have slowed my project quite a bit :sweat_smile:  especially since there is no real workaround available to serialize F# properly until 1.7.2 is released since for now even Newtonsoft cannot be used

**Comment by jeremydmiller** [comment]
So this syntax:

```csharp
// Wolverine usage is required for WolverineFx.Http
builder.Host.UseWolverine(opts =>
{
    // This middleware will apply to the HTTP
    // endpoints as well
    opts.Policies.AutoApplyTransactions();

    // Setting up the outbox on all locally handled
    // background tasks
    opts.Policies.UseDurableLocalQueues();
    opts.UseSystemTextJsonForSerialization(stj =>
    {
        // JsonFSharpOptions.Default()
        // .AddToJsonSerializerOptions(stj);
        var jsonFsharpOptions = new JsonFSharpOptions(includeRecordProperties: true);
        jsonFsharpOptions.AddToJsonSerializerOptions(stj);
    });
});
```

Will have absolutely no impact on HTTP serialization. My thinking was that you could easily want separate serialization policies for outward facing HTTP endpoints versus inward facing messaging. The Wolverine.HTTP endpoints uses the `Microsoft.AspNetCore.Http.Json.JsonOptions` object that is configured for Minimal API & AspNetCore in general, so this *should* have worked OOTB:

```csharp
builder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options =>
{
    var jsonFsharpOptions = new JsonFSharpOptions(includeRecordProperties: true);
    jsonFsharpOptions.AddToJsonSerializerOptions(options.SerializerOptions);
});
``` 

I'll look at that now. There is a new helper in 1.7 that's:

```csharp
        builder.Services.ConfigureSystemTextJsonForWolverineOrMinimalApi(o =>
        {
            // Do whatever you want here to customize the JSON
            // serialization
            o.SerializerOptions.WriteIndented = true;
        });
```

to help you pick the right one. I'm going to look at that one right now as well.
