### ISSUE TITLE
Allow filters to be added to Azure Service Bus subscriptions

### ISSUE THREAD

**Issue by GaryFail** [JasperFx/wolverine#574]
It would be great if we could add filters to the subscriptions on Azure Service Bus to give a bit more control of the messaging topology.

**Comment by Xzelsius** [comment]
@GaryFail I got a working implementation ready for this.

But it would only support exactly one filter. Did you intend to have multiple filters with one subscription?
If so what is your use-case?

I am not entirely sure how multiple filters work (only ever used simple SqlFilters myself). If you check this page https://learn.microsoft.com/en-us/azure/service-bus-messaging/topic-filters it states this

> Each rule with an action produces a copy of the message. This message will have a property called RuleName where the value is the name of the matching rule. The action can add or update properties, or delete properties from the original message to produce a message on the subscription.

This confuses me TBH. Does this mean if I add two filters to one subscription the Lister would receive the message twice?

**Comment by GaryFail** [comment]
Our current topology is we have one subscription per service, each service can subscribe to multiple message types so therefore we have a filter per message type that the service will subscribe to.

**Comment by Xzelsius** [comment]
@GaryFail So one Subscription with potentially 100 different Filters?
Or one Filter with an expression like `subject IN ('MessageType1', 'MessageType2')`?

My solution would only support the second case.
