### ISSUE TITLE
Api versioning breaks wolverine http handlers from showing up in Swagger

### ISSUE THREAD

**Issue by erdtsieck** [JasperFx/wolverine#578]
Whenever you add api versioning in your startup, swagger docs do not appear for Wolverine HTTP handlers anymore

```
builder.Services.AddApiVersioning(options =>
{
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
});
builder.Services.AddVersionedApiExplorer();
builder.Services.AddSwaggerGen();
```

**Comment by jeremydmiller** [comment]
@erdtsieck I spent about 90 minutes on this today that I couldn't really afford to be wasting. This garbage is **very** tightly coupled to MVC Core. It's going to take some kind of Wolverine.Http.ApiExplorer package to create a custom discovery mechanism for versioning. Right now, this is **way** into "I take pull requests" territory.

**Comment by erdtsieck** [comment]
> @erdtsieck I spent about 90 minutes on this today that I couldn't really afford to be wasting. This garbage is **very** tightly coupled to MVC Core. It's going to take some kind of Wolverine.Http.ApiExplorer package to create a custom discovery mechanism for versioning. Right now, this is **way** into "I take pull requests" territory.
> 
> I think the way this couple be accomplished is building a custom `IApiDescriptionProvider` for Wolverine that *must* be registered in the container after the API generator stuff. That custom provider will need to be able to stick the `ApiVersionModel` default on the `ActionDescriptor` for Wolverine endpoints so the idiotic Microsoft code will accept it as having a default version. 
> 
> 

Sorry you had a hard time with this. It is okay to prostpone this a bit and maybe me or some other contributor will create a pr

**Comment by alistair** [comment]
Hi @erdtsieck Would it be possible to get a reproduction of your issue.   Ive attempted to reproduce it but have been struggling to achieve it.  At the moment Im actually getting the wolverine endpoints in swagger but not my 'simple' versioned  endpoints.

If you can provide I will attempt to have more of a look for you.  My understanding is that even tho swushbuckler uses the api explorer api to collect metadata it doesn't rely on it exclusively.  So its a bit of a 'there be dragons' type situations with unintended coupling between multiple different packages etc etc.

https://github.com/alistair/wolverine-api-versioning-example

**Comment by erdtsieck** [comment]
<img width="171" alt="image" src="https://github.com/JasperFx/wolverine/assets/1730868/71145d43-8845-446d-ae0f-adcc64c14524">

My csproj
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="6.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="WolverineFx" Version="1.9.0" />
    <PackageReference Include="WolverineFx.Http" Version="1.9.0" />
    <PackageReference Include="WolverineFx.Marten" Version="1.9.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
  </ItemGroup>

</Project>
```

My application code
```cs
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

builder.Services.AddMarten(opts =>
    {
        opts.Connection("Host=localhost;Database=postgres;User ID=;Password=;Port=5432;Pooling=true;Include Error Detail=true;");
    })
    .IntegrateWithWolverine();

builder.Services.AddResourceSetupOnStartup();

builder.Host.UseWolverine(opts =>
{
    opts.Policies.AutoApplyTransactions();
    opts.Policies.UseDurableLocalQueues();
});

builder.Services.AddApiVersioning(options =>
{
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
});
builder.Services.AddVersionedApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.MapWolverineEndpoints();

return await app.RunOaktonCommands(args);

public record Message1(string Text);
public class Test1Endpoint
{

    [WolverinePost("api/Test1")]
    public static string Post(Message1 message)
    {
        return "everything is okay " + message.Text;
    }
}
````

**Comment by erdtsieck** [comment]
It seems `"Microsoft.AspNetCore.Mvc.Versioning` is deprecated. Moving to:

```xml
<PackageReference Include="Asp.Versioning.Mvc" Version="7.1.0" />
<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="7.1.0" />
```

And changing

```cs
builder.Services.AddApiVersioning(options =>
{
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
});
builder.Services.AddVersionedApiExplorer();
builder.Services.AddSwaggerGen();
```

TO:

```cs
builder.Services
    .AddEndpointsApiExplorer()
    .AddSwaggerGen()
    .AddApiVersioning(options =>
    {
        options.AssumeDefaultVersionWhenUnspecified = true;
        options.DefaultApiVersion = new ApiVersion(1, 0);
    })
    .AddApiExplorer()
    .EnableApiVersionBinding();
```

did the trick
