### ISSUE TITLE
Marten transactional middleware isn't correctly applied if Marten is only used by other middleware

### ISSUE THREAD

**Issue by JoshuaNitschke** [JasperFx/wolverine#581]
I'm not sure if this should be in Wolverine or Martin - if you want me to move it to Martin, let me know.
It's enough to inject IDocumentSession to induce this behavior.

**STEPS TO REPRODUCE**
1) Clone https://github.com/JoshuaNitschke/wolverine-issue-reproduction at 459dbed061fabb54a0420953c288d4238acd2f55
2) Run Unit Tests

**RESULT**
1. The endpoints utilizing Marten will fail (even if its just an unused dependency injection)
2. It seems to me that not all events from Marten are getting forwarded to Wolverine (see `fail1` where the second event doesn't get tracked - unless I comment out the first StartStream line)

<img width="786" alt="image" src="https://github.com/JasperFx/wolverine/assets/33307206/f8ec17a0-c234-4962-ad0d-8cee2fa83585">

**EXPECTED RESULT**
All tests should pass!

**Comment by jeremydmiller** [comment]
See the docs: https://wolverine.netlify.app/guide/durability/marten/event-sourcing.html#publishing-events

This line:

"Do note that only event types that have a matching subscription in the Wolverine configuration will actually be published."

There are no local subscribers or messaging rules in your application, so therefore no subscriptions to any of the event types. The code is working as expected. 

I'm closing this for now, but if you want, start a conversation in Discord instead.

**Comment by jeremydmiller** [comment]
Meh, I didn't see the handlers at first.

**Comment by JoshuaNitschke** [comment]
Per our conversation on Discord I upgraded to 1.8 and the test results are the same.

**Comment by jeremydmiller** [comment]
It's because the application of the auto-transactions isn't smart enough to consider only middleware methods. There's no usage of `IDocumentSession` or any kind of Marten side effect in the main endpoint method, so the transactional middleware doesn't think it should be applied. W/o that, there's no message flushing.

It's an non-idiomatic usage, but we can make the codegen smart enough to understand that `IDocumentSession` (or an EF Core DbContext) is being used in the call stack some where.

**Comment by JoshuaNitschke** [comment]
@jeremydmiller I did some refactoring after our conversation on Discord and I have come across another instance of events being lost when Wolverine and Marten are playing together that doesn't sound to me fits your diagnosis above.

Basically if I write to a stream that has a projection, it seems that any messages I send on the bus get lost.  I'm not sure if this is the same thing as what I already have demonstrated, but it sounds different because I _am_ using `IDocumentSession`

```
    public async Task Handle(EventFooBar e)
    {
        var @event = new NewStreamEvent(CombGuidIdGeneration.NewGuid()); 
        _session.Events.StartStream<ExampleStream>(@event.Id, @event);   // if you comment out this line or the one below, test events_from_handlers_when_when_work_causes_projection_events_should_not_be_lost will pass
        await _session.SaveChangesAsync();
        await _bus.SendAsync(new EventFoo(e.number));
        await _bus.SendAsync(new EventBar(e.number));
    }
```

I've updated the example repo with this new test case

**Comment by jeremydmiller** [comment]
@JoshuaNitschke I think the last thing is something completely different, but the fix for the main issue is going in now

**Comment by JoshuaNitschke** [comment]
@jeremydmiller do you want me to make a new bug issue for the last thing if its something completely different?

**Comment by JoshuaNitschke** [comment]
Confirmed that after updating to 1.8.1 only one of the failing tests were resolved

<img width="873" alt="image" src="https://github.com/JasperFx/wolverine/assets/33307206/4f4c122e-f5ec-494d-bd48-a8d8c2c636f7">
