### ISSUE TITLE
Duplicate processing of messages after DurabilityAgent recovery

### ISSUE THREAD

**Issue by afmuller** [JasperFx/wolverine#585]
There is a scenario I am trying to troubleshoot. I have a Handler which emits a “SendEmailCommand” outgoing/cascading message. The corresponding Handler processes the message and in turn sends an email. I noted that, on a certain occasion, the email was sent twice (I’ve noted that sometimes it appears messages are being processed twice, so I started investigating further) - appears to be random. I inspected the logs. I noted that the Durability Agent issued a command to recover the “SendEmailCommand“ message. The message was thereafter processed twice (and the email in turn processed twice).
This was a message send on a local queue. 
I am using durability for all local queues, and persisting to Posgresql:

opts.PersistMessagesWithPostgresql(connectionString);
opts.Policies.UseDurableLocalQueues();

See attachment/screenshot.

I am running version 1.8.0 of Wolverine. 

![image](https://github.com/JasperFx/wolverine/assets/15875383/81659dd7-e0b5-4dae-9166-4943d1085fa0)

Also noted that the below message repeatedly shows up in the logs - see below.

**Releasing node ownership in the inbox/outbox from dormant node 0**

![image](https://github.com/JasperFx/wolverine/assets/15875383/65f0a3bd-d549-4fa9-9c61-d9ee19903f23)
 
Nodes do reflect in the database though:

![image](https://github.com/JasperFx/wolverine/assets/15875383/5baf2f91-797c-4983-9a93-7884faf35de1)

**Comment by jeremydmiller** [comment]
@afmuller Ended up being something completely different than what I thought it would be. Of course.
