### ISSUE TITLE
Middleware is not resolving dependencies from `Finally` function.

### ISSUE THREAD

**Issue by trbngr** [JasperFx/wolverine#595]
I'm just using the static middleware example and the generated code is not resolving the `ILogger` dependency from [`Finally`](https://github.com/trbngr/Wolverine.Middelware.Problems/blob/main/CreatePerson.cs#L46).

[Repro](https://github.com/trbngr/Wolverine.Middelware.Problems/tree/main)

## Deps

* WolverineFx 1.8.3
* WolverineFx.Http 1.8.3

**Comment by jeremydmiller** [comment]
Duplicate with https://github.com/JasperFx/wolverine/issues/614, and fixed. 

Thanks for the repro steps! That helps tremendously.
