### ISSUE TITLE
Allow AggregateHandler to get ID from route params

### ISSUE THREAD

**Issue by murbanowicz** [JasperFx/wolverine#609]
Hi,

We’ve touched this on Discord and @jeremydmiller asked me to create a ticket for this.

I am one of the people who like the REST API design like /orders/:orderId/confirm . It would be amazing if Wolverine would allow us to get the aggregate id from the route param instead of the request body.

**Comment by jeremydmiller** [comment]
This is going to be a little more annoying than I'd hoped. This is going to take a separate Wolverine.Http.Marten project. No clean way of doing this without knowledge of the HttpChain

`
