### ISSUE TITLE
QUESTION: Scalability - Multiple instances

### ISSUE THREAD

**Issue by LSTANCZYK** [JasperFx/wolverine#622]
Is it possible to run multiple instances of the same application on multiple servers to provide redundancy and scalability?
I am assuming I would be using _Azure Service Bus_

**Comment by jeremydmiller** [comment]
Yes. Wouldn't be much of a tool if it didn't. You'd get competing consumers from Azure Service Bus as is. 

Hey, in the future, could you please use Discord for questions? GitHub issues are meant for bugs or feature requests.

See https://discord.gg/yddkxe3fEc
