### ISSUE TITLE
Trying to Understand - Can't Invoke messages that are subscribed from other sources

### ISSUE THREAD

**Issue by JohnGalt1717** [JasperFx/wolverine#627]
I'm coming from MassTransit so bear with me:

I would have expected that every message type would automatically generate a queue. I.e. if I have a record called AnalyseTopicUrls there would be a new queue created in rabbitmq for AnalyseTopicUrls .

I would further expect that any handler would take its definition and automatically create said queue if it doesn't exist and then listen to it.

But I can't ge this to work, and it appears to be all a bunch of shared queue name strings that you have to manually map every message you want to Invoke/Send/Publish and what queue they're being published to unless you're doing it all in memory al-la Mediator.  As soon as they're different instances (i.e. jobs that run listening for these messages) then it's all manual.

Is this true?

Is there a way to make it work the way I'd expect?

I.e. I would have assumed that the following:

`await bus.InvokeAsync<TopicUrlAnalysisResponse>(new AnalyseTopicUrls());`

Would have published to a AnalyseTopicUrls queue that if it didn't exist it would have created automatically (or errored because the handler for it didn't create the queue)

I do get this:

`Could not determine any valid subscribers or local handlers for message type Messages.Articles.AnalyseTopicUrls`

But since I already have the following in a job that appears to be running wolverine correctly (with just UseWolverine()): 
```
[WolverineHandler]
public sealed class AnalyseTopicUrlsHandler() {
   public async Task<TopicUrlAnalysisResponse> Handler(AnalyseTopicUrls message) {

   }
}

```
It would have, during setup of the Host with UseWoverine, found this, and then created the queue if it didn't exist called "AnalyseTopicUrls" automatically and then started listening and routing any messages to this handler.

The documentation unfortunately, unless I've missed something is really not clear as to what it's doing and what you have to do to get say a WebApi app to publish a request to a IHost job that is handling a specific message type and none of the samples I could find make it clear what it's doing to setup these messages.

Also, I would have thought that the WolverineMessageAttribute would have had an optional parameter that would allow it to override the queue name so that Wolverine knew what queue to publish to automatically based on the message being sent.

So my question is 2 fold:

1. How do you get it to just do automatic registration of messages to both publish and listen? (or how do I setup a queue per message or even get it to know to publish it to RabbitMQ which I've registered in UseWolverine with opts => opts.UseRabbitMq(...)?)
2. If I'm not missing documentation, could someone build up document (or I would be happy to do so once I have understanding) to explains how to setup this scenario to work properly?  

Thanks!

**Comment by JohnGalt1717** [comment]
I've sort of got it partially working with this:

```
				options.UseRabbitMq(new Uri(connectionStrings.RabbitMq))
									.UseConventionalRouting()
									.ConfigureListeners(x => x.UseDurableInbox())
									.ConfigureSenders(x => x.UseDurableOutbox())
									.AutoProvision();

```
Which isn't at all documented here: https://wolverine.netlify.app/guide/messaging/transports/rabbitmq/ 

However, this doesn't appear to support 2 levels of InvokeAsync (i.e. invoked into a handler, and then the handler invokes.)  The second invoke doesn't get the response that is definitely sent (It's in the RabbitMQ logs). It just ultimately times out.

So I'm sure I'm still doing something wrong.  I would have thought that the above on the job that runs the first level would have also setup the second message properly.  It definately sends it, and the handler for that message responds immediately, but then the first job just sits waiting for the response despite it being available??

**Comment by jeremydmiller** [comment]
@JohnGalt1717 Can you please use Discord for questions rather than GitHub issues in the future?

And the conventional routing for Rabbit MQ is opt in, and **fully documented** right here and you should have been able to see that in the navigation pane from the main rabbit mq documention without any trouble: https://wolverine.netlify.app/guide/messaging/transports/rabbitmq/conventional-routing.html

Sorry, but I don't know what this is supposed to mean:

"However, this doesn't appear to support 2 levels of InvokeAsync (i.e. invoked into a handler, and then the handler invokes.) The second invoke doesn't get the response that is definitely sent (It's in the RabbitMQ logs). It just ultimately times out."

At the end of the day, are you just wanting to do request/reply between two nodes with Rabbit MQ as the transport? If so, do you have a valid message handler in the original requestor for `TopicUrlAnalysisResponse`?

**Comment by jeremydmiller** [comment]
Nothing actionable here, I'm closing this.
