### ISSUE TITLE
Strange 'RabbitMqResponses' queue

### ISSUE THREAD

**Issue by vglinca** [JasperFx/wolverine#633]
Hi,

I'm new to the Wolverine. Want to use it to connect to RabbitMq. The setup is very smooth and transparent. But I did notice one strange thing: Wolverine always creates strange queue 'wolverine.response.-some-number'. I can't even disable this (because I don't want to give configure permissions for a RMQ user). 
What is this queue for? I published a message to some exchange and no changes were detected in that queue. I might be wrong but it seems complete useless. Could anyone explain, please?

**Comment by jeremydmiller** [comment]
That is an in memory queue created by wolverine for request/response invocations between wolverine nodes. So when you call InvokeAsync<T>(message) on something that's routed to a Rabbit MQ queue, that's what the response would come back on. 

If you're the same person who was asking about that on Discord, I'd happily accept a PR to opt out of that automatic queue. If this was just a "what is this?" question, could you close this issue?

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/wolverine/commit/d26520ca84ff017d2f42d62af0d2e09b9cbb17f5
