### ISSUE TITLE
Dependency version conflicts net8

### ISSUE THREAD

**Issue by dandcg** [JasperFx/wolverine#636]
**Describe the bug**
.NET dependencies for WolverineFx are currently set to <8.0.0 as a version constraint.

**To Reproduce**
Add JasperFx to .net 8 asp.net core project.

**Expected behavior**
Dependencies to include 8.0.0 within version constraints.

**Additional context**

Added direct reference to to 8.0.0 libs in project to working around implicit mapping issue:

```
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
```

**Comment by jeremydmiller** [comment]
We know. Waiting on the dependencies underneath Wolverine to be updated first, then Wolverine itself. This happens every single time there's a new .NET version.
