### ISSUE TITLE
Await forwarded event actions from integration tests

### ISSUE THREAD

**Issue by erdtsieck** [JasperFx/wolverine#647]
**Is your feature request related to a problem? Please describe.**
I have handlers that append that event and integration tests for that work just fine, including forwarding and everything.

Now I have another test where I just want some initial state for my aggregate by inserting the initial event. But also needing what always happens when that event is in place.
I could of course, always do what I did in these other tests, but that requires quite a lot of setup. So I'm trying to just set a base with this event +forwarded actions and state

**Describe the solution you'd like**
`await Host.TrackActivity().ForwardEventAndWaitAsync(event);` 

or maybe just somthing that looks at the outboxed events.
An extension method off of IHost that takes in an Action<IDocumentSession> or Func<IDocumentSession, Task>. Use the OutboxedSessionFactory singleton to build the Marten session w/ a new Wolverine context.

**Describe alternatives you've considered**
Adding an explicit handler works as well instead of tranforming events from EventForwardingToWolverine, but that can not take IEvent, so that is limited. A fake handler in your tests that returns the event and awaiting that would work too. 

**Additional context**
having in place:
```cs
services.AddMarten(sp => 
   // ...
)
.EventForwardingToWolverine(x =>
{
    x.SubscribeToEvent<ConsultatieGestart>().TransformedTo(e =>
        new ConsultatieAutoriseerDeelnemersVoorPatient(e.StreamKey!, e.Data.Deelnemers.Select(d => d.Id).ToList()));
});
```
And in my test:
```cs
private readonly ConsultatieGestart _consultatieGestart;

// init event from ctor

[Fact]
public async Task HetVerwijderenVanDeelnemersInEenConsultatie()
{
    // Arrange
    await using var session = OpenSession();
    session.Events.Append(_consultatieId, _consultatieGestart);
    await session.SaveChangesAsync();
    await Host.TrackActivity().SendMessageAndWaitAsync(_consultatieGestart);
    // .. code that needs forwared stuff to be completed to be able to run
```

Gives me:  `Could not determine any valid subscribers or local handlers for message type Consulteren.ConsultatieGestart`

**Comment by jeremydmiller** [comment]
Here's *a* potential starting point:

```csharp
public static class MartenTestingExtensions
{
    public static async Task<ITrackedSession> ExecuteAgainstMartenAndWait(this IHost host, Action<IDocumentSession> action)
    {
        var factory = host.Services.GetRequiredService<OutboxedSessionFactory>();

        return await host.ExecuteAndWaitAsync(async context =>
        {
            var session = factory.OpenSession(context);
            action(session);
            await session.SaveChangesAsync();
            
            // Shouldn't be necessary, but real life says do it anyway
            await context.As<MessageContext>().FlushOutgoingMessagesAsync();
        });
        
        
    }
}
```

That'd go into Wolverine.Marten

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/wolverine/pull/653

Thanks @erdtsieck!
