### ISSUE TITLE
Setting `x.CodeGeneration.TypeLoadMode` ignores `Configure()` methods on handler classes

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#650]
**Describe the bug**

I have a Wolverine-based app in a docker image with precompiled handlers. Setting `TypeLoadMode` to either `Static` or `Auto` seems to make things set up in `Configure()` ignored.

**To Reproduce**

```csharp
using JasperFx.Core;

using Wolverine;
using Wolverine.ErrorHandling;
using Wolverine.Marten;
using Wolverine.Runtime.Handlers;

namespace Api.Jobs;

public record Tick();

public static class TickHandler
{
  public static void Configure(HandlerChain chain)
  {
    chain.OnException<Exception>()
         .Discard()
         .And((runtime, context, exception)
                =>
              {
                runtime.Logger.LogWarning("This failed");

                return Task.CompletedTask;
              });
  }

  public static void Handle(Tick tick)
  {
    throw new Exception("Some error");
  }
}
```

The log message `This failed` is never logged.

**Expected behavior**

`Configure()` should be considered although handler types are loaded statically. 

**Desktop (please complete the following information):**
 - OS: macOS, Linux
 - WolverineFx 1.12.4, .NET 8.0

**Comment by jeremydmiller** [comment]
@agross I see the cause in the code, but let's see how many regression bugs I can create here

**Comment by jeremydmiller** [comment]
@agross as always, thank you for writing up the issue and your patience.

**Comment by agross** [comment]
Thank you, @jeremydmiller!
