### ISSUE TITLE
HTTP Endpoint: clarify docs regarding attribute to use when not following naming convention with Endpoint suffix

### ISSUE THREAD

**Issue by nkosi23** [JasperFx/wolverine#663]
**Is your feature request related to a problem? Please describe.**
The documentation is not clear regarding the attribute to use when not following the naming convention of using the "Endpoint" suffix for HTTP endpoints. Namely [the code sample on this page reads](https://wolverine.netlify.app/guide/http/endpoints.html):

```csharp
// The "Endpoint" suffix is meaningful, but you could use
// any name if you don't mind adding extra attributes or a marker interface
// for discovery
public static class TodoCreationEndpoint
{
```

But these remarks are never expanded in the rest of the page. At the minute, I'm going through the source code trying to find out which attribute to use but I am having a hard time to find this information.

In my case, i do not follow the convention because I am using F# and F# modules are turned into CLR static classes (with this regard Wolverine turns out to be shockingly F# friendly and the experience is quite magic - just some glitches to return tuples to trigger cascading messages: F# tuples are not recognized as C# tuple so I need to inject the message bus in the method instead. Maybe I should open a ticket for this, I was in a rush so didn't think about it). As a result the modules contain more than the HTTP endpoints so adding the Endpoint suffix wouldn't be appropriate.

For context: in F#, we tend to put much more stuff in a single file than in C# where one file = one class. since the syntax is concise and lightweight, it is quite convenient to group all types, functions and more items related to a bounded context in a module - single file.

I am therefore trying to find out which attribute I should use to decorate my modules for discovery purposes.

**Describe the solution you'd like**
More precise information regarding alternatives to the naming convention of endpoints.

**Describe alternatives you've considered**
Tried to browse the source code but not trivial to find the information.

**Comment by jeremydmiller** [comment]
@nkosi23 This behavior is spelled out pretty clearly in the documentation: https://wolverine.netlify.app/guide/http/integration.html#discovery, and the exact behavior you were looking for was *bolded*.

If you have specific suggestions for how to make this easier to find or how to express this better, I'd be happy to take a pull request for that. Until then, I believe this is actually well covered by the documentation.
