### ISSUE TITLE
FluentValidations not getting triggered

### ISSUE THREAD

**Issue by iammukeshm** [JasperFx/wolverine#664]
Questions about FluentValidation in Wolverine. The Http Validator doesnt seem to work for me. Am I missing something?

Here is my Feature class, with an Validator, validating Name property. I have also included the Endpoint Mapping here. This is on a seperate assembly.

```
public static class CreateProduct
{
    public sealed record Command(string Name, Guid CategoryId, decimal Price, string? Description = null);
    public static class Handler
    {
        public static void Handle(Command command, ILogger logger)
        {
            logger.LogInformation("product created");
        }
    }
    public class Validator : AbstractValidator<Command>
    {
        public Validator()
        {
            RuleFor(p => p.Name)
                .NotEmpty()
                .MinimumLength(10)
                .MaximumLength(75);
        }
    }
    public static RouteHandlerBuilder MapCreateProductEndpoint(this IEndpointRouteBuilder endpoints)
    {
        return endpoints.MapPost(
            "/",
            (Command command, IMessageBus bus) => bus.InvokeAsync(command)
        )
        .WithName(nameof(CreateProduct))
        .WithDisplayName(nameof(CreateProduct))
        .WithTags("products")
        .MapToApiVersion(1.0);
    }
}
```
Here is my wolverine registration, which is on the WebApi project.

```
builder.Host.UseWolverine(options =>
{
    options.CodeGeneration.TypeLoadMode = TypeLoadMode.Auto;
    options.Discovery.IncludeAssembly(typeof(CatalogModule).Assembly);
    options.UseFluentValidation();
});
```

The validators are loaded from the CatalogModule Assembly this way.
```
builder.Services.AddValidatorsFromAssembly(assembly);
```
I tried posting to the v1/catalog/products/ [POST] endpoint with an empty name in the request body. There is no validation triggered whatsoever. It just returns a 200 status code, and logs `product created` message on the console. I expect the api to return a ProblemDetails error response, or any validation error. TIA

**Comment by jeremydmiller** [comment]
@iammukeshm

Please use Discord for questions: https://discord.com/channels/1074998995086225460/1074999099855753317, and I answered you there as well. Wolverine's Fluent Validation middleware does the automatic ProblemDetails behavior when used with Wolverine.HTTP, but there's no magic way to make that work when using "Wolverine as MediatR" the way you are up above. See the documentation please.
