### ISSUE TITLE
Swagger not working nicely with Marten Document integration

### ISSUE THREAD

**Issue by jessestr** [JasperFx/wolverine#669]
![Screenshot 2023-12-20 at 15 03 24](https://github.com/JasperFx/wolverine/assets/55050897/b81fe2b2-7e3e-4592-8c08-550673e276ef)
[https://wolverine.netlify.app/guide/http/marten.html#passing-marten-documents-to-endpoint-parameters](url)

The documentation says to use this, though the {id} param set in the route does not show up in Swagger to be filled in.
Executing the endpoint is no issue. Just a matter of making sure the Id is available in swagger as well

![Screenshot 2023-12-20 at 15 05 10](https://github.com/JasperFx/wolverine/assets/55050897/90db1f98-912e-4060-8f45-89935394e41d)

**Comment by jeremydmiller** [comment]
This was fixed in 1.13. See https://jeremydmiller.com/2023/12/19/wolverines-http-gets-a-lot-better-at-openapi-swagger/
