### ISSUE TITLE
[DocumentFromMessage("MyId")] / [AggregateFromMessage("MyId")]

### ISSUE THREAD

**Issue by jessestr** [JasperFx/wolverine#670]
As discussed in Discord, would like to extend the current functionality of the [Document] and [Aggregate] attributes so it can work without any identifiers specified in the endpoint URL.

My approach is to have (example)
`DELETE /todo`

Where the command received by the Todo endpoint would be DeleteTodoRequest(string TodoId);
Hence we would need an another to specify to take the identifier from the message instead of the endpoint url.

`[DocumentFromMessage("TodoId")]`

Would solve this

**Comment by jeremydmiller** [comment]
Might very well try to fit this into 3.0 now

**Comment by jeremydmiller** [comment]
I'm folding this into #1073
