### ISSUE TITLE
Wolverine doesn't always tear down nodes

### ISSUE THREAD

**Issue by JoshuaNitschke** [JasperFx/wolverine#672]
**Describe the bug**
My application is in early stages, so it isn't hosted anywhere yet.  I am currently doing test driven development with plenty of integration tests which is how I noticed this issued.  I have not been clearing the database on startup , and I noticed my tests that used to take 2 mins to complete started to take 20 mins to complete.  After doing some digging, I noticed that my wolverine_nodes table had over 300 entries in it, from when I last dropped all tables until present day.  I dropped the wolverine tables and my tests were back snappy again.

I posted in Discord about this and was told to make an issue. https://discord.com/channels/1074998995086225460/1074999099855753317/1187471545329795184

**To Reproduce**
1. Create a Wolverine application  with these options
```
builder.Host.UseWolverine(
    (context, opts) =>
    {
        opts.Policies.OnException<ConcurrencyException>().RetryTimes(3);
        opts.Policies.OnException<NpgsqlException>()
            .RetryWithCooldown(50.Milliseconds(), 100.Milliseconds(), 250.Milliseconds());

        opts.Policies.AutoApplyTransactions();
        opts.Policies.UseDurableLocalQueues();

        if (context.HostingEnvironment.IsDevelopment())
        {
            opts.Durability.Mode = DurabilityMode.Solo;
        }

        opts.ApplicationAssembly = typeof(IApplicationRoot).Assembly;
    }
);
```
1. Create some kind of simple API end point
2. Write multiple tests that use alba to create an app fixture and test against the input
3. run dotnet test and verify that a node is created for the test run, the ID updates in place as multiple fixtures are created, but the final fixture is never disposed of and the node is left in the table

**Expected behavior**
I would expect no nodes entry to be in the wolverine_nodes table after the tests finish executing.

**Screenshots**
<img width="797" alt="image" src="https://github.com/JasperFx/wolverine/assets/33307206/18144ec3-41c7-4a3b-8bea-6057a32f3d48">

My AppFixture does dispose

```
public class AppFixture : IAsyncLifetime
{
    public IAlbaHost Host { get; set; } = null!;
    public readonly FakeClock FakeClock = new(new Instant());
    public AppFixture()
    {
    }

    
    public async Task InitializeAsync()
    {
        OaktonEnvironment.AutoStartHost = true;
        var jwtSecurityStub = new JwtSecurityStub();

        Host = await AlbaHost.For<Program>(x =>
        {
            x.ConfigureServices(services =>
            {
                services.AddSingleton<IClock>(FakeClock);
            });
        }, jwtSecurityStub);
    }

    public async Task DisposeAsync()
    {
        await Host.StopAsync();
        await Host.DisposeAsync();
    }
}
```

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Don't do any real node persistence on app startup or teardown
- [ ] NulloNodePersistence
- [ ] Use the nullo when the mode isn't `Balanced`
