### ISSUE TITLE
1.13 OpenApi generation ignores ExcludeFromDescriptionAttribute

### ISSUE THREAD

**Issue by BrianVallelunga** [JasperFx/wolverine#674]
After upgrading to 1.13.1 my endpoints with the ExcludeFromDescription attribute (from Microsoft.AspNetCore.Routing) are no longer ignored and are added to the swagger.json file. The generation itself seems fine otherwise.

**Comment by jeremydmiller** [comment]
Not terribly surprising since I'd never even heard of that attribute. What is that supposed to do?

**Comment by BrianVallelunga** [comment]
It just completely removes the endpoint from the generated specification. I was using it for a couple of endpoints that return binary data such as images.

**Comment by BrianVallelunga** [comment]
Thanks
