### ISSUE TITLE
GeneratedCodeOutputPath seems to be ignored by wolverine

### ISSUE THREAD

**Issue by nkosi23** [JasperFx/wolverine#676]
**Describe the bug**

Hello!

I am having a hard-time changing the GeneratedCodeOutputPath for Wolverine, 

```csharp
  builder.Host.UseWolverine(opts =>

        opts.CodeGeneration.GeneratedCodeOutputPath = "../MyProject.CodeGeneration.JasperFx/"
```

I have the exact same line for Marten (`opt.GeneratedCodeOutputPath = "../MyProject.CodeGeneration.JasperFx/"`) and when running `dotnet run -- codegen write`, the files coming from the `ICodeFileCollections` defined by Marten are written to the correct output directory while all the collections defined by Wolverine are put in the default directory in my main project (Internal/Generated).
 

I have just spent the last 2 hours studying the source code of JasperFx.CodeGeneration and Wolverine but fail to see an obvious suspect. The action is taking place here, first of all the output path is read by the `DynamicCodeBuilder` on every `ICodeFileCollection`:

https://github.com/JasperFx/JasperFx.CodeGeneration/blob/b6868586a838c8c9e1739aa4ffb007fdda0e6a1e/src/JasperFx.CodeGeneration/DynamicCodeBuilder.cs#L67

For HttpEndpoints, ICodeFileCollection is implemented by the  HttpGraph class, which seems to correctly receive the `CodeGeneration` option as a dependency resolved from the IoC container:

https://github.com/JasperFx/wolverine/blob/08eb736e515002649b7cf835b8930b95a6babc64/src/Http/Wolverine.Http/HttpGraph.cs#L41

https://github.com/JasperFx/wolverine/blob/08eb736e515002649b7cf835b8930b95a6babc64/src/Http/Wolverine.Http/WolverineHttpEndpointRouteBuilderExtensions.cs#L171

The endpoints are then added to the collection of `WolverineSupplementalCodeFile` by `MapWolverineEndpoints`:

https://github.com/JasperFx/wolverine/blob/08eb736e515002649b7cf835b8930b95a6babc64/src/Http/Wolverine.Http/WolverineHttpEndpointRouteBuilderExtensions.cs#L182

While `WolverineSupplementalCodeFile` is itself registered as a singleton in the IoC container, and used to resolve ICodeFileCollection for Wolverine as per:

https://github.com/JasperFx/wolverine/blob/08eb736e515002649b7cf835b8930b95a6babc64/src/Wolverine/HostBuilderExtensions.cs#L71-L72

Everything seems fine to me in the source code, I also checked if the CodeGeneration option could have been overriden somewhere else but haven't stumbled on anything obvious. Does anyone have any idea? 

**To Reproduce**

Try to configure the output path of source generation with:
 

```csharp
  builder.Host.UseWolverine(opts =>

        opts.CodeGeneration.GeneratedCodeOutputPath = "../MyProject.CodeGeneration.JasperFx/"
```

**Expected behavior**

The output files are written in the correct output directory.

**Additional context**
For context, my solution is written in F# so I need to output the generated classes in a dedicated C# project.

**Comment by jeremydmiller** [comment]
@nkosi23 I found the underlying issue, but I've got to shave a bunch of Nuget yaks before I can test the fix.
