### ISSUE TITLE
LoadAsync for the same entity in separate handlers targeting the same eventtype results in an error

### ISSUE THREAD

**Issue by FrankIversen** [JasperFx/wolverine#690]
**Describe the bug**
I cannot use Loadasync in two seperate classses who each are handling the same event to load the same entity. 

Franki — i går kl. 22:08
Question:  I have two separate handlers for the same event type. Both using LoadAsync to get the updated model from the database. This results in a error in the dynamic handler. Because two variables are named the same. The fix is easy. Just remove one the LoadAsync methods from one of the classes. Is this behaviour intended or a bug?
Jeremy Miller — i går kl. 22:11
No, it's not purposeful, but also, nobody has tried doing that yet apparently. Bug. Edge case bug, but bug.

**To Reproduce**
see above

**Expected behavior**
Being able to use LoadAsync in two seperate classes with two seperate handlers targeting the same event and loading the updated model from the database using LoadAsync

Error:
CS0128: A local variable or function named 'supplier' is already defined in this scope

**Comment by jeremydmiller** [comment]
I think the answer might be an exception telling you to "don't do that" though
