### ISSUE TITLE
Durable Local Queues not persisting cascading messages 

### ISSUE THREAD

**Issue by rbenitti** [JasperFx/wolverine#697]
**Describe the bug**
When using durable local queues (with Sql Server as backing storage), the messages publish from the handlers don't seem to be persisted.

**To Reproduce**
1. Run the code. 
2. Each handler has a delay of 5 seconds. 
3. While the MiddleEvent handler is running, kill the process before it can complete
4. Rerun the program

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disabled</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
	  <PackageReference Include="WolverineFx" Version="1.14.0" />
    <PackageReference Include="WolverineFx.SqlServer" Version="1.14.0" />
  </ItemGroup>
</Project>
```

```
using JasperFx.Core;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Oakton;
using System;
using System.Threading;
using System.Threading.Tasks;
using Wolverine;
using Wolverine.SqlServer;

var connectionString = "Server=localhost;Database=InProcess;Trusted_Connection=True;TrustServerCertificate=True;";

Console.WriteLine("Hello, from InProcess demo");
Console.WriteLine(connectionString);

// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");

return await Host.CreateDefaultBuilder(args)
    .UseWolverine((context, opts) =>
    {
        opts.Policies.MessageSuccessLogLevel(LogLevel.Information);
        opts.Policies.MessageExecutionLogLevel(LogLevel.Debug);

        opts.Durability.Mode = DurabilityMode.Solo;
        opts.PersistMessagesWithSqlServer(connectionString, "wv");
        opts.Policies.UseDurableLocalQueues();
        opts.Policies.AllLocalQueues(x => x.Sequential());
        opts.Services.AddHostedService<Worker>();
    })
    .RunOaktonCommands(args);

public class Worker(IMessageBus bus) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var id = 1;
        while (!stoppingToken.IsCancellationRequested)
        {
            Console.ReadLine();
            var e = new StartEvent(id++);
            Console.WriteLine($"Publishing {e}");
            await bus.PublishAsync(e);
        }
    }
}
public record StartEvent(int Id);
public record MiddleEvent(int Id);
public record FinalEvent(int Id);
public record DelayedEvent(int Id, DateTime Timestamp) : TimeoutMessage(5.Seconds());

public static class MyEventHandler
{
    public static async Task Handle(StartEvent e, IMessageBus context)
    {
        Console.WriteLine($"Handling {e}");
        await Task.Delay(5000);
        await context.PublishAsync(new MiddleEvent(e.Id));
    }
    public static async Task<(FinalEvent, DelayedEvent)> Handle(MiddleEvent e)
    {
        Console.WriteLine($"Handling {e}");
        await Task.Delay(5000);
        return (new FinalEvent(e.Id), new DelayedEvent(e.Id, DateTime.Now));
    }
    public static async Task Handle(FinalEvent e)
    {
        Console.WriteLine($"Handling {e}");
        await Task.Delay(5000);
    }
    public static async Task Handle(DelayedEvent e)
    {
        Console.WriteLine($"Handling {e}");
        await Task.Delay(5000);
    }
}
```

**Expected behavior**
As the local queues are set to durable, on startup it should grab the pending MiddleEvent and restart processing it.

**Screenshots**
![image](https://github.com/JasperFx/wolverine/assets/5204934/efb60a48-c38a-4d1a-ab21-3e79ca3723da)

**Desktop:**
 - OS: Windows 10
 - Version 22H2

**Additional context**
The documentation says:
[Durable Local Messages](https://wolverine.netlify.app/guide/messaging/transports/local.html#durable-local-messages)
>The local worker queues can optionally be designated as "durable," meaning that local messages would be persisted until they can be successfully processed to provide a guarantee that the message will be successfully processed in the case of the running application faulting or having been shut down prematurely (assuming that other nodes are running or it's restarted later of course).

Also,
[https://wolverine.netlify.app/guide/handlers/cascading.html](https://wolverine.netlify.app/guide/handlers/cascading.html)
>Cascading messages returned from handler methods will not be sent out until after the original message succeeds and is part of the underlying transport transaction

Could it be related?

**Comment by rbenitti** [comment]
I've been trying to debug by referencing the projects directly (no nuget package)

When sending a message to the bus from inside a handler, there is a Transaction set (from the first message that kicked the handler). 

Then, going through `MessageBus.PersistOrSendAsync `it ends up calling `IEnvelopeTransaction.PersistIncomingAsync`
Now, I can see that the `IEnvelopeTransaction `is **Wolverine.Runtime.MessageContext**, and it does not seem to do any writing to the db as `DatabaseEnvelopeTransaction `does.

Could there be some issue here? I couldnt figure out from the documentation when is the initial message considered done (so that the cascading messages have to be written to the storage), or if my configuration is making the things work inline (like MediatR) and that could cause the situation?

**Comment by jeremydmiller** [comment]
@rbenitti It's kind of a fake setup here, and not idiomatic Wolverine usage. You're not getting any inbox here because you're not doing anything that's using any kind of persistence mechanism, so Wolverine isn't smart enough to *think* it should be using any kind of envelope persistence here. 

Admittedly a hole in Wolverine's logic, but also a non-idiomatic usage. If your endpoints used an EF Core DbContext or injected a SqlTransaction, then it would have been smart enough to do things durable.

What are you actually trying to accomplish? I get that Wolverine didn't behave the way you expected, but this is all fake. How are you actually planning to use it in real application development?

**Comment by jeremydmiller** [comment]
Here's a working version of the code:

```csharp
[Transactional]
public static class MyEventHandler
{
    public static async Task Handle(StartEvent e, IMessageBus context, SqlTransaction tx)
    {
        Console.WriteLine($"Handling {e}");
        await Task.Delay(5000);
        await context.PublishAsync(new MiddleEvent(e.Id));
    }
    public static async Task<(FinalEvent, DelayedEvent)> Handle(MiddleEvent e, SqlTransaction tx)
    {
        Console.WriteLine($"Handling {e}");
        await Task.Delay(5000);
        return (new FinalEvent(e.Id), new DelayedEvent(e.Id, DateTime.Now));
    }
    public static async Task Handle(FinalEvent e)
    {
        Console.WriteLine($"Handling {e}");
        await Task.Delay(5000);
    }
    public static async Task Handle(DelayedEvent e, SqlTransaction tx)
    {
        Console.WriteLine($"Handling {e}");
        await Task.Delay(5000);
    }
}
```

So it's something that *could* be fixed I suppose, but I'd drop this to a very low priority because it's just not very realistic IMO. If you want things to be database backed, but you're not really using any kind of persistence within the handlers, you could get more approapriate behavior by using the Sql Server messaging transport
