### ISSUE TITLE
First class "query message" support

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#71]
Alright, I've frequently mocked MediatR (and probably will again), but after working in a massive system with an explosion of repository methods, I'm coming around to the idea of query handlers / specifications.

**Goal**: allow for expressing complex queries -- including any necessary transformations -- in one small, dedicated type or function. Use Wolverine's codegen'd dependency model around that with also the potential for middleware.

I'm proposing two patterns (maybe) **nah, this sounds like it would really mess people up**:

```csharp
// use method injection at will
public static QueryResponseModel Query(QueryRequestModel model, IService1 service1, IService2 service2)
{

}
```

And you'd still use `ICommandBus.InvokeAsync<QueryResponseModel>(QueryRequestModel)` 

Or maybe:

```csharp
// This is just a marker interface
public interface IQuerySpecification<T>
{
    
}

public class QueryRequestModel : IQuerySpecification<QueryResponseModel>
{
   // props & other members

   // The name Query would be meaningful here
   public Task<QueryResponseModel> Query(IDocumentSession, DbContext, CancellationToken)
   {
       // do whatever, use method injection
   }
}
```

**Comment by aritchie** [comment]
My two cents worth - I would vote for the second model above.  It emulates mediatr & InvokeAsync would become explicitly strongly typed instead of "guessing" on the generic return value. 

PS - I love this project.

**Comment by jeremydmiller** [comment]
There hasn't been any demand for this, and I'm kind of horrified at how this kind of thing has played out in real codebases where I've seen folks use this with MediatR.
