### ISSUE TITLE
Durable inbox won't handle the incoming queue

### ISSUE THREAD

**Issue by dgrozenok** [JasperFx/wolverine#711]
**Describe the bug**
With the durable inbox configured Woverine takes all the messages from the RabbitMQ and places them into the table in PostgreSQL. However, while the messages are being handled, the table is only growing in size. In the logs we see the following exceptions which tells us there could be a message or a record in the queue that causes the Woverine to fail on reading the durable inbox. With hundreds of thousands messages unfortunately it's hard to identify the one failing to be able to reproduce.

Woverine version is 1.10

Here is the exception:
{   "Depth": 0,   "ClassName": "System.NullReferenceException",   "Message": "Object reference not set to an instance of an object.",   "Source": "Wolverine.RDBMS",   "StackTraceString": "   at Wolverine.RDBMS.Durability.CheckRecoverableIncomingMessagesOperation.PostProcessingCommands()+MoveNext()\n   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()\n   at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()\n   at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()\n   at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()\n   at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()\n   at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation)\n   at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation)\n   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)",   "RemoteStackTraceString": null,   "RemoteStackIndex": 0,   "HResult": -2147467261,   "HelpURL": null }

**Comment by jeremydmiller** [comment]
@dgrozenok Just shot you a couple messages about this on LinkedIn. Hit me up via phone if you need this addressed before Monday?

**Comment by jeremydmiller** [comment]
@dgrozenok This is from a background job, and not the code that would be marking the incoming envelopes as "Handled" after a message is processed. This is a symptom, and not the cause of whatever is happening for you. Can you look for errors from a `MarkIncomingEnvelopeAsHandledAsync` method?

It might be that the failure you see is a result or cause of table locks.

You aren't using this from any kind of serverless function are you by chance?

**Comment by dgrozenok** [comment]
Will look for other exceptions. The services are running in kubernetes pods.

**Comment by misha-p** [comment]
@jeremydmiller Checked other exceptions except those from background job post processing - nothing from MarkIncomingEnvelopeAsHandledAsync, no locks or anything of that nature.

**Comment by misha-p** [comment]
also fyi - we turned off durable outbox, cleaned up state in postgres - no errors since.

**Comment by jeremydmiller** [comment]
I've got nothing here, sorry folks
