### ISSUE TITLE
Move to PeriodicTimer everywhere

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#716]
Just replace the current Timer usage with PeriodicTimer as time permits

**Comment by woksin** [comment]
Is it worth switching to PeriodicTimer? As it does not offer an API that will support what Timer is used for, at least not out of the box

**Comment by jeremydmiller** [comment]
@woksin Which is why I haven't done anything yet:) Probably should be "investigate" using periodic timer

**Comment by jeremydmiller** [comment]
Nobody cares, I don't think this is necessary.
