### ISSUE TITLE
WolverineFx.Http MapPostToWolverine<TRequest, TResponse> is not setting tenant id

### ISSUE THREAD

**Issue by ticky74** [JasperFx/wolverine#744]
Given the following configuration:

```
app.MapWolverineEndpoints(o =>
{
    o.TenantId.AssertExists();
    o.TenantId.IsRequestHeaderValue("tid");
    o.TenantId.IsClaimTypeNamed("tid");
    o.UseFluentValidationProblemDetailMiddleware();
}); 
```

and the following http endpoint

```
app.MapPostToWolverine<MyCommand, MyResponse>("/api/my-command")
    .WithTags("tags")
    .Produces<MyResponse>(StatusCodes.Status200OK);
```

The handler gets executed as expected, however neither the TenantId on IMessageBus or IMessageContext is set

```
public static async Task<HandlerContinuation> BeforeAsync(MyCommand input, IMessageBus bus, IMessageContext context, 
               MachOneDbContext db)
    {
        return HandlerContinuation.Continue;
    }

public static MyResponse  Handle(MyCommand input, IMessageBus bus, IMessageContext context, 
               DbContext db)
    {
        ....
        return new MyResponse()
    }
```

If I use a straight MyCommandEndpoint http handler class everything works as expected;

**Comment by jeremydmiller** [comment]
@ticky74 The Map****ToWolverine wasn't really designed for anything more than doing a straight shot to Wolverine. Any reason why you can't just use Wolverine.HTTP endpoints?

**Comment by ticky74** [comment]
No technical reason at all. Since I have started using Wolverine I find myself in amazement when I have to write more than 4 or 5 lines of code when using Wolverine***Anything! What you've done here is really a step function in progress for software developers. Definitely owe you a lunch or beer if we ever meet!

Thanks again so much for the explanation.
