### ISSUE TITLE
Wolverine with Marten integration crashes

### ISSUE THREAD

**Issue by AdvantBeiten** [JasperFx/wolverine#749]
Version tested: V1.20.1

I use wolverine with marten:

services.AddMarten(storeOptions =>
{
    -- Do some config
})
.IntegrateWithWolverine("messageStore")
.EventForwardingToWolverine();

This works the first time. the schema and all tables are created.
After that, it crashed with:

 Npgsql.PostgresException (0x80004005): 42P06: schema "messagestore" already exists

Expected Behavior: Wolverine should check if the schema already exists and should not try to created it if already present.

**Comment by jeremydmiller** [comment]
@AdvantBeiten Meh, I'll call this a "bug", but look carefully. You're getting hit with a case sensitivity issue. Change your code to `.IntegrateWithWolverine("messagestore")` and you'll be good to go. PostgreSQL will force object names to be lower case.

**Comment by AdvantBeiten** [comment]
Thanks for the fast help. I just didn't see that. Sometimes the solution is so easy. Thanks again.
