### ISSUE TITLE
Wolverine needs a password in marten with wolverine senarion in V 7.1/2.0

### ISSUE THREAD

**Issue by AdvantBeiten** [JasperFx/wolverine#767]
I use this:

services.AddMarten(storeOptions =>
            {
                storeOptions.Connection(connectionString);
           // more options
            })
           .IntegrateWithWolverine("messagestore");

This worked in v6, but not in v7 any more. It only works when I remove the IntegrateWithWolverine command

The connections string contains a password, but at application start I get:

"Failed to setup resource Envelope Storage of type Wolverine
      Npgsql.NpgsqlException (0x80004005): No password has been provided but the backend requires one (in SASL/SCRAM-SHA-256)"

I alrady tried .IntegrateWithWolverine("messagestore", connectionString);

but still no luck.

Marten is version 7.1.1, wolverine 2.0.0, wolverinefx.marten is 2.0.0 as well

Any help would be appreciated.

Thanks!

**Comment by jeremydmiller** [comment]
More or less a duplicate with https://github.com/JasperFx/wolverine/issues/691.

Here's the temporary, easy workaround for the Npgsql behavior change that got you: https://github.com/npgsql/npgsql/issues/1123
