### ISSUE TITLE
When returning multiple ISideEffects from a handler, only the first is executed

### ISSUE THREAD

**Issue by robertdusek** [JasperFx/wolverine#778]
Marten 7.3.1
Wolverine 2.1.1

Given the following handler:
```c#
public record ExampleDocument(Guid Id, string Text);
public record StoreTwoDocuments();

public static class DoubleDocumentHandler
{
    public static (IMartenOp, IMartenOp) Handle(StoreTwoDocuments message)
    {
        return (
            MartenOps.Store(new ExampleDocument(Guid.NewGuid(), "some text")),
            MartenOps.Store(new ExampleDocument(Guid.NewGuid(), "some other text"))
            );
    }
}
```

the following code is generated:
```c#
    // START: StoreTwoDocumentsHandler2045588605
    public class StoreTwoDocumentsHandler2045588605 : Wolverine.Runtime.Handlers.MessageHandler
    {
        private readonly Wolverine.Marten.Publishing.OutboxedSessionFactory _outboxedSessionFactory;

        public StoreTwoDocumentsHandler2045588605(Wolverine.Marten.Publishing.OutboxedSessionFactory outboxedSessionFactory)
        {
            _outboxedSessionFactory = outboxedSessionFactory;
        }



        public override async System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
        {
            // Building the Marten session
            await using var documentSession = _outboxedSessionFactory.OpenSession(context);
            // The actual message body
            var storeTwoDocuments = (Repro.StoreTwoDocuments)context.Envelope.Message;

            
            // The actual message execution
            (var outgoing1, var martenOp) = Repro.DoubleDocumentHandler.Handle(storeTwoDocuments);

            if (outgoing1 != null)
            {
                
                // Placed by Wolverine's ISideEffect policy
                outgoing1.Execute(documentSession);

            }

            
            // Commit any outstanding Marten changes
            await documentSession.SaveChangesAsync(cancellation).ConfigureAwait(false);

            
            // Have to flush outgoing messages just in case Marten did nothing because of https://github.com/JasperFx/wolverine/issues/536
            await context.FlushOutgoingMessagesAsync().ConfigureAwait(false);

        }

    }

    // END: StoreTwoDocumentsHandler2045588605
```

The first item in the returned tuple is named `outgoing1` and is executed, but the second item named `martenOp` is not executed.

**Comment by jeremydmiller** [comment]
Picking this up now

**Comment by robertdusek** [comment]
It's probably a larger consideration but would it make sense to have a collection type for side effects similar to OutgoingMessages and Events?

**Comment by jeremydmiller** [comment]
It absolutely would, and I'd even planned on that, but that doesn't work today because the `Execute` / `ExecuteAsync()` signature doesn't have to be consistent, and Wolverine is planning that out on the concrete type of the side effect. It could work w/ `IMartenOp` because the signature is all the same. So there could be a `MartenOps`, but not a generic `SideEffects` unless we introduce a different form something liek:

**Comment by robertdusek** [comment]
One advantage I can see to a `MartenOps` collection is that it clearly communicates the transaction boundary of those specific side effects compared to the wider `ISideEffect` concept that may require some compensating action if the Wolverine transaction fails after the side effect is executed.

I think the advantage of an `IWolverineAction` interface is maybe a bit less clear cut. Conceptually the current implementation of side effects is really clean and unless returning multiple or a variable qty of side effects became a common request I think it's probably better to avoid subdividing the side effect concept into different categories with a new interface. I realize that this kind of goes against my argument in favor of the `MartenOps` collection though and I really can't reconcile that.

This sparked another thought though; some form of `OnError` method for side effects might be a useful addition.
