### ISSUE TITLE
First class event subscriptions from Marten 

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#783]
The existing event forwarding happens at the time that events are captured. Other folks are going to want to do ordered and/or batched operations on the incoming events. 

Some thoughts:

* Try to utilize as much as possible of the Marten "async daemon" infrastructure
* Utilize Marten's `ProjectionBase` to allow for limiting events and setting up event filters?
* Handler recipe that can take a batch of events, and just return an `IEnumerable<object>` of cascading messages. Should be able to use other services, but point is to return messages
* Handler recipe similar to Marten's SingleStreamAggregation that uses a `Handle(EventType) : OutgoingMessages` or `Handle(IEvent<EventType>)`. 
* Definitely a recipe that can work with a batch of events at a time
* If using a Marten IDocumentSession, try to use the same session that's being used by the surrounding agent so that the progression write can go in on the same transaction
* Wolverine's agent assignment will be used to verify the subscriptions only run on one box at a time
* Subscriptions should define their lifetime. If added later, do they catch up from zero? Do they use archived events? Start from a certain time?
* **Anything** more advanced like replaying or pausing subscriptions goes into Critter Stack Pro
* Add Otel tracking and statistics as well

**Comment by erdtsieck** [comment]
It would be great if handing an event could be an aggregatehandler that aggregates the aggregate that is linked to that event. The IEvent handle should make that possible I would think

**Comment by jeremydmiller** [comment]
@erdtsieck Ah, effectively allowing you to take extra actions off the event? Can you describe your use case for that?

**Comment by elexisvenator** [comment]
There is mention here about being based on marten's projections, but it feels to me that if implemented properly then projections would become based on this instead.

Re lifetimes: Being able to start from 0 and start from "current" are probably both desirable. As is more pro features like "start from X" and "reset to X".

Re handling archived: Definitely feel that archived events should not be handled by default. I can see a use case for this if there are users that are in the habit of archiving streams based on time, so maybe make it explicit that you want to do this.

Re Batching: I feel this is critical for some use cases, especially when communicating to apis that support batching (eg aws sqs is cheaper when using batched apis). Some sort of advanced batching with behaviors like "wait for X messages or Y seconds before processing" would be useful here.  Another thing to consider here is how to deal with poison pill events hiding within a batch.

A few shiny (aka pro) features that come to mind:
- Pausing without config change/redeployment.
- Worker nodes - being able to offload the async daemon to background-only application nodes

**Comment by jeremydmiller** [comment]
@elexisvenator Thanks for the feedback!

> There is mention here about being based on marten's projections, but it feels to me that if implemented properly then projections would become based on this instead.

There were some changes in the 7.0 daemon that got us partially there to begin with in preparation for this. This was a last minute scratch in the initial 7.0 release

I *think* that there will be an API right off the bat for restarting from 0 or a certain point, but just an API. I think anything more advanced will be in "Critter Stack Pro"

> Definitely feel that archived events should not be handled by default.

They're not, but that's adjustable. In a follow up release soon, I'd love to make the event archiving be full blown hot/cold storage through opt in sharding and add better archiving support to the projections

> Re Batching: I feel this is critical for some use cases

Going in day one because a JasperFx client has a use case for that :-)

> A few shiny (aka pro) features that come to mind:

100% "Critter Stack Pro". Pausing sounds like low hanging fruit, the other might be a little more

**Comment by jeremydmiller** [comment]
There's also a world of possibilities for confusion between this and the event forwarding. Make sure the event forwarding can be filtered too!

**Comment by elexisvenator** [comment]
Where do you see the line being for using event subscriptions and event forwarding? Is event forwarding going to be a simpler but narrower scoped version of the same functionality. (I am currently using event forwarding to send a message based on an event to sqs, not sure whether it would be worth switching over)

**Comment by jeremydmiller** [comment]
Funny, I got up this morning thinking about how to describe the decision to use one or the other. 

And yeah, I think event forwarding is always going to be a simpler mechanism that also gets the events out much faster, just without any ordering guarantees.
