### ISSUE TITLE
Using WolverineDelete throws Wolverine.Middleware.InvalidWolverineMiddlewareException: It's not currently legal in Wolverine to return the message type from middleware

### ISSUE THREAD

**Issue by StellaAlexis** [JasperFx/wolverine#809]
**Describe the bug**
Wolverine is trying to apply a WolverineDelete endpoint as middleware which results in an InvalidWolverineMiddlewareException and app crash at startup. The code works as expected when changing the endpoint type to GET, POST or PUT instead of DELETE or when adding additional parameters to the Delete method.

As there are workarounds it's not a high priority issue. Also happy to provide more details. 

**Additional context**
The following class is throwing the error:
```
public class TrainerDelete
{
    private readonly UserManager<User> UserManager;
    
    public TrainerDelete(UserManager<User> userManager)
    {
        UserManager = userManager;
    }
    
    [Tags("Trainer")]
    [WolverineDelete("/api/trainer")]
    public async Task<IResult> Delete(UserId userId, IDocumentSession session, CancellationToken ct)
    {
        if (await session.LoadAsync<Trainer>(userId.Id, ct) != null)
        {
            session.HardDelete<Trainer>(userId.Id);
            await session.SaveChangesAsync(ct);
        }

        User? user = await UserManager.FindByIdAsync(userId.Id.ToString());
        IdentityResult userDelete = await UserManager.DeleteAsync(user);

        if (userDelete.Errors.Any())
        {
            return Results.Problem(userDelete.Errors.ToString());
        }
        
        return userDelete.Succeeded ? Results.NoContent() : Results.Problem("Unable to delete trainer");
    }
}
```

Working class using Get as the only difference
```
public class TrainerDelete
{
    private readonly UserManager<User> UserManager;
    
    public TrainerDelete(UserManager<User> userManager)
    {
        UserManager = userManager;
    }
    
    [Tags("Trainer")]
    [WolverineGet("/api/trainer")]
    public async Task<IResult> Delete(UserId userId, IDocumentSession session, CancellationToken ct)
    {
         // method implementation
        
        return userDelete.Succeeded ? Results.NoContent() : Results.Problem("Unable to delete trainer");
    }
}
```

Working class using an additional empty parameter
```
public record DeleteTrainer;

public class TrainerDelete
{
    private readonly UserManager<User> UserManager;
    
    public TrainerDelete(UserManager<User> userManager)
    {
        UserManager = userManager;
    }
    
    [Tags("Trainer")]
    [WolverineDelete("/api/trainer")]
    public async Task<IResult> Delete(DeleteTrainer command, UserId userId, IDocumentSession session, CancellationToken ct)
    {
        // method implementation
        
        return userDelete.Succeeded ? Results.NoContent() : Results.Problem("Unable to delete trainer");
    }
}
```

**Stacktrace**
```
Wolverine.Middleware.InvalidWolverineMiddlewareException: It's not currently legal in Wolverine to return the message type from middleware
   at Wolverine.Middleware.MiddlewarePolicy.ApplyToChain(List`1 applications, GenerationRules rules, IChain chain)
   at Wolverine.Middleware.MiddlewarePolicy.Apply(IReadOnlyList`1 chains, GenerationRules rules, IContainer container)
   at Wolverine.Http.HttpGraph.DiscoverEndpoints(WolverineHttpOptions wolverineHttpOptions)
   at Wolverine.Http.WolverineHttpEndpointRouteBuilderExtensions.MapWolverineEndpoints(IEndpointRouteBuilder endpoints, Action`1 configure)
   at Program.<Main>$(String[] args) in **/Program.cs:line 117
   at Program.<Main>(String[] args)
```

**Comment by jeremydmiller** [comment]
@StellaAlexis There's nothing in Wolverine.HTTP that would automatically apply anything as middleware. Are you sure this is really everything for the repro steps? I can't imagine why anything you're showing here would be a problem. There's nothing special about the `DELETE` verb behavior in Wolverine. It should behave exactly like POST/PUT. GET/HEAD is a little different of course.

**Comment by StellaAlexis** [comment]
Thanks for getting back to me so quickly! And apologies I didn't test well enough I assumed as the GET worked and I have endpoints similar enough with POST and PUT working those would work too. But after more testing POST and PUT have the same issue. 

To provide better reproduction steps I created a minimal repo that reproduces the issue:
https://github.com/StellaAlexis/MinimalExamples/tree/production/WolverineMiddlewareApply

**Comment by jeremydmiller** [comment]
@StellaAlexis Blessed be those who provide executable reproduction steps, for they shall have their bugs fixed first!

Not sure I'll get this into 2.2 that will hit tomorrow or Monday, but definitely in 2.3 that will come out next week. Wolverine looks to be busy for a bit.

Thanks for taking the time to do that!

**Comment by jeremydmiller** [comment]
@StellaAlexis Finally looking at it today, and I see exactly what's happening. This'll get fixed w/ a combo of:

* Longer, maybe more descriptive error message
* New `[EmptyRequest]` attribute for HTTP to let Wolverine know to ignore that first `UserId` argument as the HTTP request body

**Comment by jeremydmiller** [comment]
Ton of work on your part and mine just for me to end up tweaking an exception message and telling you to add one attribute:

`public async Task<IResult> Delete([NotBody] UserId userId, IDocumentSession session, CancellationToken ct)`

**Comment by StellaAlexis** [comment]
Awesome, thanks so much Jeremy!
