### ISSUE TITLE
Container disposed on using cascading messages two levels deep

### ISSUE THREAD

**Issue by NeussConsulting** [JasperFx/wolverine#833]
I have strange disposing issue with Wolverine.

I'm in a Blazor Component and inject me a IMessageBus instance into it.

Then I have 4 messages with handlers (a, b, c, sharedA, sharedB)

```
public async Task<Response> Handle(a message)
{
Just local code
return new Resonse
}

public async Task<Response> Handle(b message, IMessageContext context)
{
Local code
var test = await context.InvokeAsync<Reponse>(new sharedA);
More local code
return Response;
}

public async Task<Response> Handle(c message)
{
Local code
return Response;
}

public async Task<Response> Handle(sharedA message, IMessageContext context)
{
Local code
var test = await context.InvokeAsync<Reponse>(new sharedB);
More local code
return Response;
}

public async Task<Response> Handle(sharedB message)
{
Local code
return Response;
}
```

I call them like that inside the Blazor Component:

```
await messageBus.InvokeAsync<Response>(new a); --> Works fine

await messageBus.InvokeAsync<Response>(new b); --> Works fine

await messageBus.InvokeAsync<Response>(new c); --> Exception inside WolverineRuntime because Container is disposed
```

if I change message handler sharedA like the below everything works
`
public async Task<Response> Handle(sharedA message)
{
return Response;
}
`

**Comment by jeremydmiller** [comment]
@NeussConsulting Oh, and look for anything in your codebase where you're injecting `IContainer` or `IServiceProvider`

It's a Lamar-specific thing, but there's a feature called "DisposalLock" you can set on the container to ignore requests to dispose the container. It's a hack, but it's there to stop problems like this when you can't easily find the root cause

**Comment by NeussConsulting** [comment]
> @NeussConsulting I really don't think this is because of Wolverine. There's nothing in the Wolverine codebase that would dispose the underlying container. What else is going on in your app? Something happening maybe that's killing the app? Is this possibly from a test where you're not waiting correctly for the cascading behavior which is asynchronous?

As I found out, it's lifetime issue with a Blazor Component, the forums are full of it, but with EF and so on, but same symptom.
Unfortunately I don't know how to fix it with Wolverine, it's to Niche. ;(

BUT, it's NOT a Wolverine Bug.

**Comment by jeremydmiller** [comment]
@NeussConsulting As a workaround, look for ContainerLock on the Lamar `Container`
