### ISSUE TITLE
Agent leader election timeouts when running in HotCold mode locally

### ISSUE THREAD

**Issue by Richard87** [JasperFx/wolverine#834]
**Describe the bug**
When running in HotCold mode locally I start getting `TimeoutExceptions`  in my log every 30ish seconds.

It probably started after a debugging session, and I currently have about 25 nodes in `wolverine_nodes` on my laptop (only one process is currently running.

| id | node\_number | description | uri | started | health\_check | capabilities |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| e44beb57-5834-48a6-8d2a-d8e9394bc1aa | 22 | Richards-MacBook-Pro | dbcontrol://e44beb57-5834-48a6-8d2a-d8e9394bc1aa/ | 2024-04-23 19:04:30.823890 +00:00 | 2024-04-23 19:04:30.823890 +00:00 |  |
| 3d341c78-a321-42e3-b60f-91d32a268ffe | 23 | Richards-MacBook-Pro | dbcontrol://3d341c78-a321-42e3-b60f-91d32a268ffe/ | 2024-04-23 19:10:59.918864 +00:00 | 2024-04-23 19:10:59.918864 +00:00 |  |
| 88326fd3-aac7-439b-9346-97b0cb923c44 | 24 | Richards-MacBook-Pro | dbcontrol://88326fd3-aac7-439b-9346-97b0cb923c44/ | 2024-04-23 19:11:18.236782 +00:00 | 2024-04-23 19:11:18.236782 +00:00 |  |
| f9aeb68b-0aaa-4f95-b400-3851827b60e0 | 26 | Richards-MacBook-Pro | dbcontrol://f9aeb68b-0aaa-4f95-b400-3851827b60e0/ | 2024-04-23 19:22:55.905173 +00:00 | 2024-04-23 19:23:18.953634 +00:00 |  |
| 5f84f8d4-94c9-4193-99d5-1a7cd27e55c9 | 27 | Richards-MacBook-Pro | dbcontrol://5f84f8d4-94c9-4193-99d5-1a7cd27e55c9/ | 2024-04-23 19:24:51.397411 +00:00 | 2024-04-23 19:24:51.397411 +00:00 |  |
| 37d54ed4-2578-4a4e-be25-40e206a96622 | 28 | Richards-MacBook-Pro | dbcontrol://37d54ed4-2578-4a4e-be25-40e206a96622/ | 2024-04-23 19:25:18.744822 +00:00 | 2024-04-23 19:25:18.744822 +00:00 |  |
| 1fae5838-0612-4b83-a7d1-059cf10dc4ec | 29 | Richards-MacBook-Pro | dbcontrol://1fae5838-0612-4b83-a7d1-059cf10dc4ec/ | 2024-04-23 19:25:47.804795 +00:00 | 2024-04-23 19:25:47.804795 +00:00 |  |
| c08e7104-d882-4d91-861d-705398fa94f9 | 30 | Richards-MacBook-Pro | dbcontrol://c08e7104-d882-4d91-861d-705398fa94f9/ | 2024-04-23 19:26:35.503936 +00:00 | 2024-04-23 19:26:35.503936 +00:00 |  |
| b2f1a2be-63bc-4390-827d-916b6aea13dc | 33 | Richards-MacBook-Pro | dbcontrol://b2f1a2be-63bc-4390-827d-916b6aea13dc/ | 2024-04-23 19:35:24.795122 +00:00 | 2024-04-23 19:35:38.286930 +00:00 |  |
| 2600ae44-241b-4a5c-b06f-4969ba067e49 | 34 | Richards-MacBook-Pro | dbcontrol://2600ae44-241b-4a5c-b06f-4969ba067e49/ | 2024-04-23 19:37:53.219540 +00:00 | 2024-04-23 19:37:53.219540 +00:00 |  |
| 2e64bb5a-fc93-4d95-b347-e621579aa54a | 36 | Richards-MacBook-Pro | dbcontrol://2e64bb5a-fc93-4d95-b347-e621579aa54a/ | 2024-04-23 19:38:39.284212 +00:00 | 2024-04-23 19:38:39.284212 +00:00 |  |
| d5a117ab-f537-45b8-bdc1-c00803d39187 | 37 | Richards-MacBook-Pro | dbcontrol://d5a117ab-f537-45b8-bdc1-c00803d39187/ | 2024-04-23 19:40:30.886600 +00:00 | 2024-04-23 19:40:30.886600 +00:00 |  |
| 084eae10-36ac-4ec5-a558-b7a28fadfa7c | 38 | Richards-MacBook-Pro | dbcontrol://084eae10-36ac-4ec5-a558-b7a28fadfa7c/ | 2024-04-23 19:40:56.640718 +00:00 | 2024-04-23 19:40:56.640718 +00:00 |  |
| 2a9b620c-36af-4f8d-8014-1822445af5c8 | 39 | Richards-MacBook-Pro | dbcontrol://2a9b620c-36af-4f8d-8014-1822445af5c8/ | 2024-04-23 19:41:17.773211 +00:00 | 2024-04-23 19:41:17.773211 +00:00 |  |
| 61831773-89ec-4b64-a033-177c00390566 | 40 | Richards-MacBook-Pro | dbcontrol://61831773-89ec-4b64-a033-177c00390566/ | 2024-04-23 19:43:04.354858 +00:00 | 2024-04-23 19:43:04.354858 +00:00 |  |
| 05a3858d-d570-4ac2-9262-af935741cc49 | 41 | Richards-MacBook-Pro | dbcontrol://05a3858d-d570-4ac2-9262-af935741cc49/ | 2024-04-23 19:45:22.901876 +00:00 | 2024-04-23 19:45:22.901876 +00:00 |  |
| 878e459e-61ae-4492-bacf-22e9fac48e10 | 42 | Richards-MacBook-Pro | dbcontrol://878e459e-61ae-4492-bacf-22e9fac48e10/ | 2024-04-23 19:49:32.077179 +00:00 | 2024-04-23 19:49:32.077179 +00:00 |  |
| e6426cb1-1812-4a87-9b2c-bad3054697bb | 43 | Richards-MacBook-Pro | dbcontrol://e6426cb1-1812-4a87-9b2c-bad3054697bb/ | 2024-04-23 19:49:59.244468 +00:00 | 2024-04-23 19:49:59.244468 +00:00 |  |
| 51da62ac-f29a-4297-a8c1-2bf82ac76946 | 44 | Richards-MacBook-Pro | dbcontrol://51da62ac-f29a-4297-a8c1-2bf82ac76946/ | 2024-04-23 19:50:23.735715 +00:00 | 2024-04-23 19:50:23.735715 +00:00 |  |
| 7fe20dae-b965-41a6-b75e-0fcbdb78faa7 | 45 | Richards-MacBook-Pro | dbcontrol://7fe20dae-b965-41a6-b75e-0fcbdb78faa7/ | 2024-04-23 19:50:46.144445 +00:00 | 2024-04-23 19:50:46.144445 +00:00 |  |
| a94e2a2b-8488-49f2-9d57-595ceb75e819 | 46 | Richards-MacBook-Pro | dbcontrol://a94e2a2b-8488-49f2-9d57-595ceb75e819/ | 2024-04-23 19:51:08.461305 +00:00 | 2024-04-23 19:51:08.461305 +00:00 |  |
| 539297f4-0fc2-46c2-b2f7-8cb07a85c40e | 47 | Richards-MacBook-Pro | dbcontrol://539297f4-0fc2-46c2-b2f7-8cb07a85c40e/ | 2024-04-23 19:51:33.084439 +00:00 | 2024-04-23 19:51:33.084439 +00:00 |  |
| 29289d20-bf8b-422e-aaf6-0e42d0c25986 | 49 | Richards-MacBook-Pro | dbcontrol://29289d20-bf8b-422e-aaf6-0e42d0c25986/ | 2024-04-23 19:52:45.856408 +00:00 | 2024-04-23 19:53:00.353818 +00:00 |  |
| d87f6611-adbc-4094-a688-b890a7355af7 | 50 | Richards-MacBook-Pro | dbcontrol://d87f6611-adbc-4094-a688-b890a7355af7/ | 2024-04-23 19:59:34.474813 +00:00 | 2024-04-23 19:59:34.474813 +00:00 |  |
| e002455e-5833-4d33-94d8-80ce47120057 | 54 | Richards-MacBook-Pro | dbcontrol://e002455e-5833-4d33-94d8-80ce47120057/ | 2024-04-23 20:30:06.375203 +00:00 | 2024-04-23 20:41:59.778607 +00:00 |  |

```
fail: Wolverine.Runtime.WolverineRuntime[0]
      Error trying to perform agent health checks
      System.TimeoutException: Timed out waiting for expected acknowledgement for original message 018f0cae-705e-4f19-b6e6-134442522ea5 of type Wolverine.Runtime.Agents.TryAssumeLeadership
         at Wolverine.Runtime.Routing.MessageRoute.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRoute.cs:line 146
         at Wolverine.Runtime.WolverineRuntime.InvokeAsync(Guid nodeId, IAgentCommand command) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 60
         at Wolverine.Runtime.Agents.TryAssumeLeadership.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/TryAssumeLeadership.cs:line 24
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AgentCommandHandler.cs:line 36
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 202
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 212
         at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 93
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 129
         at Wolverine.Runtime.WolverineRuntime.executeHealthChecks() in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 207

```

Running Wolverine 2.5.1 / Marten 7.8.0

**Comment by jeremydmiller** [comment]
@Richard87 Are you maybe constantly running your app with a debugger and manually shutting things down without letting the app close gracefully? If you are, my advice would be to run "Solo" locally. Or clear out the nodes table occasionally.

Might also try using Rabbit MQ as the control queues, but the single biggest issue is bypassing a clean shutdown over and over again. The "Solo" mode is specifically meant to address the exact issue you're hitting.

**Comment by Richard87** [comment]
Yup, thats basically excactly whats happening (clicking restart debugging button), but shoudnt Wolverine cleanup orphaned nodes at one point, or is it the operators responsibilty?

Also, maybe it should be a Warning instead of a Warning or Information instead of an Error  if its not a problem @jeremydmiller ?
