### ISSUE TITLE
Add warning "Wolverine is only able to use Lamar as its IoC container"  on the landing page

### ISSUE THREAD

**Issue by epitka** [JasperFx/wolverine#835]
I really like Wolverine's approach, and was investigating it as an alternative to MediatR to dispatch commands. Since this is brownfield project, this is a deal breaker. I think this warning should be prominently displayed either in tutorials or on landing page.

**Comment by jeremydmiller** [comment]
That's documented in several places, but sure. Sounds like a great pull request.
