### ISSUE TITLE
Request/Reply and system queue semantics for Azure Service Bus

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#85]
Read this much closer: https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messages-payloads#message-routing-and-correlation

Can you make a queue/topic for ASB that routes replies back to a single node?

**Comment by gfoidl** [comment]
For this to use [sessions](https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions) are helpful.
