### ISSUE TITLE
Alba Integration Test Fails with Wolverine Middleware host

### ISSUE THREAD

**Issue by franks1** [JasperFx/wolverine#851]
**Describe the bug**
Hi Team,
I want to use Wolverine endpoints in my application.
When I add Wolverine middleware in the program file: builder.Host.UseWolverine();
the app works fine, but my integration test with Alba host fails with the error: 
**System.AggregateException : An error occurred while writing to logger(s). (Cannot access a disposed object.
Object name: 'EventLogInternal'.)**
Seems to be coming from Microsoft.Extensions.Logging.

However, when I exclude Wolverine middleware and use Minimal API the Test project passes my test.

**To Reproduce**
1. Run dotnet test for the test project in this sample project: [https://github.com/franks1/NurseRegistry]

**Expected behavior**
I expect that the test project should not fail.

**Screenshots**
![test_error](https://github.com/JasperFx/wolverine/assets/3717094/90e4207c-1459-41a7-9bf3-844445e0dd54)

**Comment by jeremydmiller** [comment]
@franks1 I cloned your repro and the one test in there passes on my box. There's no middleware in the project, or at least no Wolverine middleware. I added some fake middleware that used an `ILogger` and still didn't see what you saw. Hit me up on Discord if you want, but for right now I'm closing this just for the sake of bookkeeping.

**Comment by franks1** [comment]
> @franks1 I cloned your repro and the one test in there passes on my box. There's no middleware in the project, or at least no Wolverine middleware. I added some fake middleware that used an `ILogger` and still didn't see what you saw. Hit me up on Discord if you want, but for right now I'm closing this just for the sake of bookkeeping. 

Thank you . I will surely get in touch on discord. Thank you

**Comment by esond** [comment]
@franks1 Did you solve this for yourself? Running into the exact same issue.

**Comment by esond** [comment]
Well, I think I solved it for myself. I was calling `DisposeAsync()` on the Alba host, but calling `StopAsync()` instead seems to have solved the problem.

**Comment by esond** [comment]
I seem to have solved this for myself. I was calling `DisposeAsync()` on the Alba host, but should have been calling `StopAsync()` instead.
