### ISSUE TITLE
About 500ms roundtrip latency in Ping-Pong demo with TCP transport

### ISSUE THREAD

**Issue by K1vs** [JasperFx/wolverine#883]
**Describe the bug**
In demo Ping-Pong app with TCP transport i got about 500ms latency from senting ping to receiving pond on localhost.
If I change transport to RabbitMQ, the round trip latency decrease to 15 ms, which is good enough result.
Such a latency (500ms localhost) certainly cannot be considered normal and expected for TCP transport.

**To Reproduce**
1. Setup demo app from https://wolverinefx.net/tutorials/ping-pong.html
2. Add OpenTelemetry tracing or any other latency monitoring tools.
3. Run applications and check roundtrip latency in monitoring tool. 

**Expected behavior**
The roundtrip latency should not exceed 35 milliseconds.

**Screenshots**
With RabbitMQ 
![image](https://github.com/JasperFx/wolverine/assets/11088116/b91d6ec2-d58e-4240-9b21-a9b12f4c3dcc)
With TCP transport
![image](https://github.com/JasperFx/wolverine/assets/11088116/915eaba4-5480-46d3-bdda-e17f7e6eed08)

**Desktop (please complete the following information):**
 - Windows 11
 - .NET 8
 - WolverineFx 2.7.0
 
**Additional context**
As I understand the documentation, TСP transport is not educational. It is quite suitable for real tasks where authorization is not needed and lightness is important. But such delays do not allow it to be used in real tasks, about which there should be a warning.

**Comment by jeremydmiller** [comment]
@K1vs "I take pull requests"

**Comment by K1vs** [comment]
Thanks! It would be nice to add information about the waiting time for sending a package to the documentation. This may come as a surprise to some developers. Being able to customize this time would be interesting for many scenarios.
