### ISSUE TITLE
Durable In/Outbox behavior seems to keep messages in SQL forever.

### ISSUE THREAD

**Issue by Djoums** [JasperFx/wolverine#895]
Follow-up of the existing issue https://github.com/JasperFx/wolverine/issues/689 that has been fixed on the main branch already.

The provided fix is only for the latest version however (.Net 8) and is not available to those who still have to use .Net 6.

Is it possible to port the fix in the 1.20.x version ? The committed code fix seems fairly lightweight.

**Comment by jeremydmiller** [comment]
I've pushed that fix to 1.20.2. Sorry for the delay.
