### ISSUE TITLE
Any plans for MySQL support?

### ISSUE THREAD

**Issue by Ekkeir** [JasperFx/wolverine#949]
We're now considering our options for saga-capability library and WolverineFx seems interesting.

The downside is - MySQL is used in our environment. So the question is - are there any plans for MySQL-based persistence in the near future?

Thank you!

**Comment by jeremydmiller** [comment]
It comes up occasionally. It's certainly possible, but a touch of work mostly because of wanting to have the built in database change detection in Weasel.

**Comment by Ekkeir** [comment]
Got it, thank you for the response!
