### ISSUE TITLE
Wolverine & Marten integration: Deadletter replay not working correctly

### ISSUE THREAD

**Issue by jorik** [JasperFx/wolverine#971]
**Describe the bug**

Replaying deadletter'd events of type `IEvent<T>` does not work.

**To Reproduce**
Setup Marten and Wolverine, with `marten.IntegrateWithWolverine`, `marten.PublishEventsToWolverine`, `wolverine.UseDurableLocalQueues` and `wolverine.AutoApplyTransactionsalso` enabled.

Then, write a handler for a Marten event:
```
public sealed class MyEventHandler()
{
    public MyCascadingEvent Handle(IEvent<MyEvent> @event)
    {
        throw new Exception("asd");
    }
}
```

This will send the message to the error queue: `with message 'Moved message 0190cac1-9ceb-4bad-a3eb-afe8c9a81cee to the Error Queue`

No replay the event, by setting `replayable` to `true` in the `wolverine_dead_letters` table to re-run the message. When re-running, wolverine is not able to correctly route the message.

```
2024-07-19T13:31:11.2280960 info: Wolverine.RDBMS.DurabilityAgent[0]
      Issuing a command to recover 1 incoming messages from the inbox to destination local://ieventmyevent/
2024-07-19T13:31:11.2490510 info: Wolverine.RDBMS.DurabilityAgent[206]
      Recovered 1 incoming envelopes from storage
2024-07-19T13:31:11.2507170 info: Wolverine.RDBMS.DurabilityAgent[0]
      Successfully recovered 1 messages from the inbox for listener local://ieventmyevent/
2024-07-19T13:31:11.2515180 info: Wolverine.Runtime.WolverineRuntime[106]
      e6c8713c-ee8d-4d91-89e5-9990a5700e82: No known handler for EventMyEvent#0190cac1-9ceb-4bad-a3eb-afe8c9a81cee from local://replies/
```

**Expected behavior**
Message should be replayed, but it's lost

**Desktop (please complete the following information):**
 - OS: Mac OSX

**Comment by jorik** [comment]
Found another place where `IEvent<T>` is causing issues:

```
    opts.OnException<SendEmailException>()
        .RetryWithCooldown(100.Milliseconds(), 500.Milliseconds(), 2.Seconds(), 5.Seconds())
        .Then
        .ScheduleRetry(1.Minutes(), 2.Minutes());
```

The cooldowns work, but the retry ends up with:

```
2024-07-20T11:48:01.6811800 info: Wolverine.Runtime.WolverineRuntime[0]
      Locally enqueuing scheduled message 0190cf89-4f6b-4a7c-8ae4-f89d49044d31 of type EventCreated
2024-07-20T11:48:01.6894440 info: Wolverine.Runtime.WolverineRuntime[106]
      19cbeb11-d601-4ee6-a11d-efb7dd8cb89b: No known handler for EventCreated#0190cf89-4f6b-4a7c-8ae4-f89d49044d31 from local://replies/
```

**Comment by jeremydmiller** [comment]
This was *nasty* to fix and took longer than every other bug in this release combined. The IEvent<T> publishing is both strategically important and extremely unpleasant to support.
