### ISSUE TITLE
Configuring SQS with a Queue name in PascalCase appears to try and use the lowercase version

### ISSUE THREAD

**Issue by zanehanasoft** [JasperFx/wolverine#973]
**Describe the bug**
When I setup an SQS queue in Wolverine, if I have a queue like EmailManagerLog2 it will try to look for emailmanagerlog2 instead. Because SQS queue names are case sensitive we have having issues linking our code to our SQS queue

**To Reproduce**
1. Have an existing queue in SQS called EmailManagerLog2
2. Use .NET Core 8 ASP.NET Core
3. WolverineFx nuget package 2.6 (I've also tested on the latest version 2.15.2)
4. Setup Wolverine as follows. 
![Configuration](https://github.com/user-attachments/assets/a362912b-afde-4b2d-9d43-9cbae330d2f0)
5. After debugging the options after the configuration is complete is appears to create 2 queue configurations.
![AmazonSQSObjectInfo](https://github.com/user-attachments/assets/6d715e8c-eac1-446c-bbe4-2559fd046788)
![SQSQueueInfo](https://github.com/user-attachments/assets/ad49a715-906f-490c-98cb-9eca396cb96c)
![SQSQueueInfo2](https://github.com/user-attachments/assets/5b08e08e-73f6-4c89-91c1-d8dd77dca908)
And after the app tries to run I see this Exception.
![Exception](https://github.com/user-attachments/assets/639cd457-eb8d-4d15-bb03-fd16c4d083c2)

If I create the queue as a lowercase version it works but the actual queue I want is PascalCase and I wont be changing it because it is consumed by another service.

**Expected behavior**
Should not lower the case of the Queue.

UPDATE: I've pulled the source code directly and have found where the issue is. I don't have permission to create a PR though so I've attached this patch.

[0001-add-a-fix-to-support-finding-an-AmazonSQSQueue-objec.patch](https://github.com/user-attachments/files/16344828/0001-add-a-fix-to-support-finding-an-AmazonSQSQueue-objec.patch)

**Comment by jeremydmiller** [comment]
@zanehanasoft Got it, and applying it now. Why didn't you have permission to do a PR though?

**Comment by zanehanasoft** [comment]
oh sorry I meant I didn't have the ability to push my branch, when I tried I get an error saying I don't have write access
