### ISSUE TITLE
Improved Saga Support for 3.0

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#988]
While the 3.0 work is happening, now is a good time to talk about possible improvements to the Saga support. I've got a couple things in mind:

## Concurrency Protection

You could fake the concurrency a little bit with Marten, but it would be nice to have first class concurrency protection with sagas so that parallel work doesn't necessarily overwrite Saga state. My only ideas so far are based on Marten's `FetchForWriting()` implementation:

1. An optimistic approach whereas we add versioning to the stateful `Saga`, which is easy enough. In this case we will "know" the current revision of the saga because we're loading it to begin with. On committing the saga state we'll have the database reject the changes if the saga has been changed since the transaction started
2. Little bit harder, and probably only useful for Marten for now and even then with Marten development, use an exclusive lock on the saga in the database. That'll force the single file through that saga

In all cases, throw a distinct exception so that it's easy to apply retry rules on any operations against the saga

## Lightweight database storage

Especially when using SQL Server or Postgresql w/o Marten, use a crude table storage and JSON serialization. Quicker and easier the messing around with EF Core mapping IMO

**Comment by elexisvenator** [comment]
I have only just started experimenting with sagas myself, does `[SagaIdentity]` work with the aspnetcore endpoint integration?  I haven't tested nor really thought through how rational of an idea that is yet though.

Is saga state documents (in marten integration)? Asking because that would lead to some useful functionality around being able to query saga state for inspection/monitoring purposes.

Other than that, optimistic concurrency sounds like a great idea 👍

**Comment by jeremydmiller** [comment]
@elexisvenator So:

> does [SagaIdentity] work with the aspnetcore endpoint integration?

Yes, exact same mechanics and underlying code

> Is saga state documents (in marten integration)? 

If using Marten, yes

**Comment by jeremydmiller** [comment]
For the Marten saga persistence, then ended up using `IRevisioned` for optimistic concurrency. I'm voting to punt exclusive concurrency for now
